### ISSUE TITLE
http status: 404

### ISSUE THREAD

**Issue by Tizioincognit0** [MiRO92/uYou-for-YouTube#1]
When I'm trying to download this video: https://youtu.be/2WGuW-eIoAM, I got "http status: 404" error.
![image](https://user-images.githubusercontent.com/40031873/128387410-486a2092-5c04-4e94-96a3-af1498c8f42e.png)

**Comment by MiRO92** [comment]
Please use another way to re-sign the IPA, such as AltStore.

**Comment by Tizioincognit0** [comment]
But I didn't use the IPA; I installed the tweak because I'm jailbroken!

**Comment by Tizioincognit0** [comment]
This issue has been fixed after last update.
