### ISSUE TITLE
Subscription tab - missing video length stamp

### ISSUE THREAD

**Issue by Khisss** [MiRO92/uYou-for-YouTube#101]
videos on subscription page are missing the little stamp on the thumbnail which shows how long the video is

![93BC9D2F-5D8C-4EC2-8CE4-8F02E2E9F068](https://user-images.githubusercontent.com/96706304/147424371-1a003578-0080-420b-b5a0-56739614698c.jpeg)

**Comment by XSilverlink** [comment]
Yeah, same issue here. Really annoying. Project hasnt been updated for a while. Maybe its abandoned?

**Comment by Khisss** [comment]
Miro was last active in November, so he probably just has other priorities at the moment. he is doing all this for free after all

**Comment by FrostBid** [comment]
I have also encountered the problem, and I would also like to add some information to this. 

I am using iPad iOS 13.5 taurine, tried downgrading YouTube app but the problem still persist. My only two other YouTube related tweaks are return YouTube dislike and iSponsorBlock.
![391A9446-BA61-4B06-8D24-4CF5919D818C](https://user-images.githubusercontent.com/83489811/153596214-5d80ecd5-ffc1-416f-bdd6-b206cc08332b.jpeg)
