### ISSUE TITLE
Background playback doesn't work correctly when using YouPIP

### ISSUE THREAD

**Issue by bendooms** [MiRO92/uYou-for-YouTube#109]
When in PIP mode (using the tweak [YouPIP](https://github.com/PoomSmart/YouPiP)), the background playback does not work when shutting the screen off. Background playback only works when the app is open when shutting the screen off.

**Steps To Repro:**

1. Have uYou and YouPIP installed
2. Open a video on the YouTube app
3. Go to the homescreen to watch the video in PIP mode
4. Turn your screen off

**Comment by qnblackcat** [comment]
This is iOS behavior. It's not a bug. You should contact Apple
