### ISSUE TITLE
[Bug] Search ads not removed after turning on disable YouTube Ads

### ISSUE THREAD

**Issue by nicknitewolf** [MiRO92/uYou-for-YouTube#11]
uYou 1.5 (Sideloaded version)
iOS 15 Beta 6

![photo6129469419101990149](https://user-images.githubusercontent.com/6513413/130358498-161e84ac-1b0b-4ff7-8671-4a1a965dd8a6.jpg)

**Comment by qnblackcat** [comment]
For me, these ads only shows up if I search for special keywords such as “4k”, “4k HDR”. Pretty weird 
![0DDF9075-BB9E-41F2-AA81-A5E4324D0C96](https://user-images.githubusercontent.com/52943116/130363301-2364cf37-0b50-4c71-bd9b-ff308b5dea08.png)

![80839213-877D-4863-BBE1-5C8AA3A2716E](https://user-images.githubusercontent.com/52943116/130363289-a20d5b44-e11f-4ef9-83fe-f6b6eae79190.png)

**Comment by DetachHead** [comment]
Same here, though I’m seeing video ads

![87E7716C-0F55-4712-A423-5BE7DAA10E4A](https://user-images.githubusercontent.com/57028336/147384330-b3d32323-52d4-4cb7-84a5-3445bdef1ce5.png)

**Comment by Macleykun** [comment]
I don’t seem to have this issue anymore (V2.1)

**Comment by Proaxel** [comment]
> I don’t seem to have this issue anymore (V2.1)

I am on 2.1 and I am still getting ad suggestions in search results.

![CCB53E4A-63E7-407F-8B75-E1DBD7C42634](https://user-images.githubusercontent.com/9545347/154964963-6aca2424-da28-4bfa-a0e6-8ebfaa6e4c0e.png)
![AE882A2D-61C0-41A8-8D59-E5326613C4CE](https://user-images.githubusercontent.com/9545347/154964997-34f5b72e-2e0f-454b-9c93-dcbef77773ae.png)
![59EB739B-56DF-42DD-975F-63BBF472176F](https://user-images.githubusercontent.com/9545347/154965013-bf230ab7-04e2-4517-b89f-8f89fdfc903f.png)

**Comment by DetachHead** [comment]
@nicknitewolf why close this if @Proaxel is still seeing the ads on v2.1
