### ISSUE TITLE
Is there a way to open YouTube links in uyou?

### ISSUE THREAD

**Issue by dpyy** [MiRO92/uYou-for-YouTube#110]
Is there a way to open YouTube links in uyou?

**Comment by dzej1** [comment]
I think there is only one option for now - shortcut https://shortcutsgallery.com/shortcuts/open-in-youtube/

**Comment by allefmatheus** [comment]
drugs

**Comment by Macleykun** [comment]
Close issue, this isn’t possible even with dev account.

**Comment by Skywalker8510** [comment]
https://github.com/qnblackcat/uYouPlus/issues/69#issue-1148871462 take a look at this
