### ISSUE TITLE
Background Playback Not Being Disabled When Turned Off in uYou Tab Settings

### ISSUE THREAD

**Issue by DKam92** [MiRO92/uYou-for-YouTube#114]
On iOS 15.3.1 the "Background Playback" button in the uYou section does not affect the background playback, as it always remains on, even after the setting has been turned off.

**Comment by qnblackcat** [comment]
Are you using the official version of uYou from this repo?

**Comment by DKam92** [comment]
@qnblackcat Yes

**Comment by FanToM1212** [comment]
I'm having the same problem. How to fix it?
