### ISSUE TITLE
Downloads fail on non jailbroken devices

### ISSUE THREAD

**Issue by romantra** [MiRO92/uYou-for-YouTube#117]
Device info:

iOS/iPadOS version: 15.1.1
Device model: iPhone 11 Pro Max
Sideload tool: ESign 4.3.7
Version of uYou: v16.42.3
Describe the bug:

When I try to download a video it starts downloading normally the video but when it finishes I'm getting an error that says:
Error 200 - Unable to move file from file:///var/mobile/Library/Caches/com.apple.nsurlsessionid/Downloads/com.latin.*/CFNetworkDownload_YTTMnk.tmp...
Full error in the link: https://youtu.be/PZxcfL_MnfY

How to reproduce the bug:
(Please attach videos or screenshots if possible)

I'm in a unjailbreak state and I have side loaded the app using esign an a dev cert, but I'm unable to download the video since I don't have some permissions to transfer the file downloaded from a cache folder to the app folder.

When I use cercube I can download the videos without issues but I like more uYou :)

**Comment by spamsgood** [comment]
Same issue
