### ISSUE TITLE
Video length is missing in History, Playlist

### ISSUE THREAD

**Issue by qnblackcat** [MiRO92/uYou-for-YouTube#12]
- iOS 14.3/checkra1n/Substitute
- YouTube 16.32.6
- uYou 1.5
- uYou is the only YouTube tweak I installed
![DAEE2DDC-767F-4843-8068-1D80F35BC23F](https://user-images.githubusercontent.com/52943116/130362767-34684f42-7b80-4656-acdf-5c885d53e6b2.png)
![3B779CAC-D2AB-4531-A6E8-BADEDBEF6183](https://user-images.githubusercontent.com/52943116/130362763-4cceba9e-2961-4063-a636-95d0ea92df59.png)

![74E1846E-E5BA-486E-B760-2370E0EF462E](https://user-images.githubusercontent.com/52943116/130362756-3ebe1a8d-db1b-4db5-803b-abb89a640f98.png)

**Comment by MiRO92** [comment]
This is has nothing to do with uYou, It's YT who removed it.

**Comment by qnblackcat** [comment]
Sorry, but I don’t get it. The video length shows up in the original YouTube (uYou is disabled)
![1F076216-B181-4B6B-998A-C87522BAF7A4](https://user-images.githubusercontent.com/52943116/130376613-8e29537c-8a6d-4219-ac6c-4a023686db18.png)
![43066F75-53F2-4215-B9BC-E68DE46FA9BA](https://user-images.githubusercontent.com/52943116/130376618-483a34c1-6f9e-43ef-8c55-c1bfe0c4c1a7.png)
