### ISSUE TITLE
CarPlay

### ISSUE THREAD

**Issue by jiggers84** [MiRO92/uYou-for-YouTube#122]
After talking with the dev for "carplayenable". They told me it would be possible to make this work with an unjailbroken device with some work.

"The tweak requires code injection into system processes (CarPlay) as well as injection into every app that is going to be forced onto the CarPlay display (to adapt the app’s window to the CarPlay unit screen size)

It would be possible, but complex, to modify individual apps to work with CarPlay on non-jb ios. If you have extensive experience with runtime modification development and an enterprise development certificate I can describe what is needed"

Using the new update to sideloadly which will allow you inject dylib & deb with substrate combined with an ipa. Is there anyway to combine all of this together, and allow YouTube++ to work with CarPlay as a new feature? Is this plausible?

**Comment by MiRO92** [comment]
Thanks a lot for your suggestion but currently I barely have the time to fix the current issues with uYou so am not interested to het involved with CarPlay stuff.
