### ISSUE TITLE
YouTube crashes when changing video speed with uYou

### ISSUE THREAD

**Issue by qnblackcat** [MiRO92/uYou-for-YouTube#13]
- iOS 14.3/checkra1n/Substitute
- YouTube 16.32.6
- uYou 1.5. uYou is the only YouTube tweak I installed

- How to reproduce the issue:
1. Play a video, change video speed with uYou.
2. Close the video.
3. Important: preview another video (few seconds) before opening it.
4. Changing the video speed, YouTube app will crash

- Crash log: https://ghostbin.com/paste/PHJK6

- Video

https://user-images.githubusercontent.com/52943116/130363137-6b9f2524-3d68-4c58-8b20-a67a83c545ca.MP4

**Comment by qnblackcat** [comment]
Everything is ok as long as I don’t preview any video 😊

**Comment by MiRO92** [comment]
Fixed!, thanks a lot for your report.
