### ISSUE TITLE
Cr4shed Report: uYouPlus (1.0.3)

### ISSUE THREAD

**Issue by SethWiiPlaza** [MiRO92/uYou-for-YouTube#130]
Your package (com.ichitaso.uyouplus) has been determined to be the culprit of the attached crash.

Additional Details:

[YouTube@2022-04-20_7:13 pm.log](https://drive.google.com/file/d/1OvhWdfy7ynHfms003g1NSkagTizli4dt/view?usp=drivesdk)

**Comment by qnblackcat** [comment]
Sir, [uYou] and [uYouPlus] is completely two different tweaks (except for
the name) uYou has nothing to do with your problem. If you have an issue
with [uYouPlus], by ichitaso, then contact ichitaso.

https://github.com/ichitaso/uYouPlus-for-JB

**Comment by Tweaker177** [comment]
Not to throw salt on an open wound but the package description mentions this, and not to bother you with issues related to the jailbreak tweak.
