### ISSUE TITLE
Background Playback Cannot be Turned Off (iOS 15.4.1)

### ISSUE THREAD

**Issue by DKam92** [MiRO92/uYou-for-YouTube#132]
When using uYou+ (most recent version) on an iPhone 13 with iOS 15.4.1 even when background playback is turned off in the menus the background playback still turns on when the phone is locked/put to sleep.

**Comment by qnblackcat** [comment]
**This is not an issue of uYou**: https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-why-cant-i-disable-background-playback-i-turned-off-background-playback-in-uyous-settings

Suggest close the issue. Please don’t bother MiRO with unrelated problems

**Comment by DKam92** [comment]
PiP is off on my end in all of the menus, which is what the fix is in the link you sent. This means that this is still an issue. if you have any updated advice please let me know.

**Comment by qnblackcat** [comment]
@DKam92 let make it clear: once you injected YouPiP, background playback cannot be disabled. 
Again, it is not an issue related to uYou, and you should not post it her. This repo is for uYou’s issue and uYou’s issue only. YouPiP is def not an issue of uYou

**Comment by DKam92** [comment]
Alright, marking as resolved.
