### ISSUE TITLE
Ads when streaming to TV?

### ISSUE THREAD

**Issue by will-ashworth** [MiRO92/uYou-for-YouTube#133]
uYou has been amazing since installing yesterday via AltServer on my Mac. Couldn't have been easier.

Ads are skipped when in handheld mode, but when broadcasting to my Roku they still play ads.

I'm also seeing an issue where uYou loses sync of the video on the TV and the video timeline won't update anymore on uYou until I dismiss (shrink) and then bring back the video on the phone. Then I see the correct timestamp updated, but then it freezes again. All the while the TV continues playing the broadcasted video.

Unsure if these are bugs, but felt worth sharing. Thank you!

**Comment by TheXires** [comment]
As off my understanding the Ads on TV are because the smartphone just sends the link to the video and syncs the progressbar, but the chrome cast, Roku tv, … streams the video and ads it's self.

But I am not 100% sure about that. YouTube Vanced for Android had the same issue.

**Comment by theoccurrence** [comment]
> As off my understanding the Ads on TV are because the smartphone just sends the link to the video and syncs the progressbar, but the chrome cast, Roku tv, … streams the video and ads it's self.

This is not true when OP uses AirPlay, which I think to be the case. I'm not using uYou for some time now, because it seemed to be abandoned, but skipping ads and sponsorblock work fine with AirPlay, when using Cercube.
