### ISSUE TITLE
Download speed is slow

### ISSUE THREAD

**Issue by lrs95** [MiRO92/uYou-for-YouTube#135]
I hope it can be optimized

**Comment by Skywalker8510** [comment]
I noticed this too I was downloading videos on 5G UW and 30-minute Netflix downloads were almost instant but a 30 minute yt video gave me a 20-minute time estimate.

**Comment by antondalov** [comment]
I have the same issue. Download speed is ridiculous slow even with 5G or fast WiFi-network.

**Comment by theoccurrence** [comment]
This is only speculation, but I think this tweak uses youtube-dl, which has been really slow for some time now. Also it seems to be abandoned now.

There are other tools like yt-dlp, which is a much faster fork of youtube-dl

**Comment by antondalov** [comment]
It would be great if the uYou worked with yt-dlp. The download speeds would be amazing..
