### ISSUE TITLE
Make the sponsorblock dialog smaller

### ISSUE THREAD

**Issue by nikhilcn5** [MiRO92/uYou-for-YouTube#136]
On my iP 13 mini, whenever I get a sponsor skip dialog it occupies a good 20% of the top of the screen. Request to make the text box smaller.
![WhatsApp Image 2022-05-15 at 8 17 37 PM](https://user-images.githubusercontent.com/36162439/168478879-23f01313-c383-4a97-9f0a-52305a2dcd90.jpeg)

**Comment by qnblackcat** [comment]
**uYou** doesn’t have sponsor block. You‘re using **uYouPlus**, a modified version of uYou, which has iSponsorBlock included. I highly suggest you close this issue since it‘s not the related to uYou at all.

**Comment by nikhilcn5** [comment]
Extremely sorry. Closed.
