### ISSUE TITLE
No option to download shorts

### ISSUE THREAD

**Issue by xxMR-IMPERFECTxx** [MiRO92/uYou-for-YouTube#139]
UYou version: 2.1
YouTube version: 17.20.3
Sideloading service: AltStore

I'm on the latest version and there's no option to download shorts, it used to work from watch history but now there's no way to do that.

![image](https://user-images.githubusercontent.com/105914255/170699957-7ef76199-eeb4-4fe0-8f15-cfa514f51a5f.jpeg)

**Comment by dayanch96** [comment]
> UYou version: 2.1 YouTube version: 17.20.3 Sideloading service: AltStore
> 
> I'm on the latest version and there's no option to download shorts, it used to work from watch history but now there's no way to do that.
> 
> ![image](https://user-images.githubusercontent.com/105914255/170699957-7ef76199-eeb4-4fe0-8f15-cfa514f51a5f.jpeg)

Workaround for now: Go to History - your Shorts video - Actions (⋮) - uYouLocal
