### ISSUE TITLE
Feature Request: Switchable tabs

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#14]
I think it would be very handy for a lot of users if we could switch the tabs from the bottom bar around as we like. It would be very useful for me at least, because I just can't get used to the library tab not being the rightmost one.

Bonus request: I'm seeing a lot of videos with a "Thanks" button below the player lately. Users should be able to hide that button as well.

![image](https://user-images.githubusercontent.com/16444679/130366208-de5d0b82-d124-4c8c-a40c-6a2c10fbffbe.jpeg)

Also the "Hide Create Shorts Button" option doesn't seem to work for me, as you can see.

**Comment by MiRO92** [comment]
Done!
