### ISSUE TITLE
Crashing when attempting a download with uYou local

### ISSUE THREAD

**Issue by TimestaticYT** [MiRO92/uYou-for-YouTube#140]
Im jailed and downloaded the app through AltStore. iOS Version 15.4.1
uYou+ version v17.20.3
I am using an iPhone 12

**Comment by schweppes-0x** [comment]
I have the same issue on iPhone 13 pro with iOS 15.5 and uYou+ version 17.20.3

**Comment by leapbtw** [comment]
same issue. iPhone 11 Pro @ iOS 14.6 jailed with unc0ver 8.0.2
