### ISSUE TITLE
Download problem SOLVED

### ISSUE THREAD

**Issue by 4shtray** [MiRO92/uYou-for-YouTube#141]
uYou Local, when tapped, crashes the entire app, when the uYou download button doesn’t download the actual video marking Zero KB
SOLVED

**Comment by 4shtray** [comment]
Device: iOS 15.4 iPhone 8

**Comment by t0mi** [comment]
What do you do to solve the problem?

**Comment by TimestaticYT** [comment]
How was the problem solved? Come on!

**Comment by MiRO92** [comment]
all above issues are fixed, an update will be released soon, so stay tuned.
