### ISSUE TITLE
[Appearance Request] Disable High-Contrast Icons Option - uYou Settings

### ISSUE THREAD

**Issue by arichorn** [MiRO92/uYou-for-YouTube#142]
When uYou obtains a new version, I’m just thinking that uYou deserves to have a new option to turn of High-Contrast Icons in Light/Dark Mode, these very bright icons in these hurt your eyes on some people with eye conditions, and YouTube hasn’t gave us an option to like darken the icons to even stop eye strain. I got concepts for uYou to have it

### The Following Images you see aren’t real.
![CC689336-9DA5-4B25-B234-9A8CAF21B23A](https://user-images.githubusercontent.com/78001398/171328715-d03b5f90-3da5-4799-b000-1719ef215eb2.jpeg)
![6706B915-1538-4811-AF36-BBD945B2D8BE](https://user-images.githubusercontent.com/78001398/171328717-5c011a0a-01e5-4269-be27-fdb0005c0b7f.jpeg)
![F1C74A7A-0870-49A5-A4A7-71C053736067](https://user-images.githubusercontent.com/78001398/171328718-f2d451ae-7a62-4822-b09c-66ab38eec670.jpeg)
![5CAC2B75-E0B6-4B0B-ABBA-F99C0C6AB37E](https://user-images.githubusercontent.com/78001398/171328720-c5f02d3f-7a8c-4e07-99f1-754212c63fca.jpeg)
I tried to do good examples and concepts about this, I’m just trying to make uYou as best as possible with something like this. MiRO if you’re reading this then you’re a good YouTube Modder/Tweaker!

**Comment by dayanch96** [comment]
> When uYou obtains a new version, I’m just thinking that uYou deserves to have a new option to turn of High-Contrast Icons in Light/Dark Mode, these very bright icons in these hurt your eyes on some people with eye conditions, and YouTube hasn’t gave us an option to like darken the icons to even stop eye strain. I got concepts for uYou to have it
> 
> ### The Following Images you see aren’t real.
> ![CC689336-9DA5-4B25-B234-9A8CAF21B23A](https://user-images.githubusercontent.com/78001398/171328715-d03b5f90-3da5-4799-b000-1719ef215eb2.jpeg) ![6706B915-1538-4811-AF36-BBD945B2D8BE](https://user-images.githubusercontent.com/78001398/171328717-5c011a0a-01e5-4269-be27-fdb0005c0b7f.jpeg) ![F1C74A7A-0870-49A5-A4A7-71C053736067](https://user-images.githubusercontent.com/78001398/171328718-f2d451ae-7a62-4822-b09c-66ab38eec670.jpeg) ![5CAC2B75-E0B6-4B0B-ABBA-F99C0C6AB37E](https://user-images.githubusercontent.com/78001398/171328720-c5f02d3f-7a8c-4e07-99f1-754212c63fca.jpeg) I tried to do good examples and concepts about this, I’m just trying to make uYou as best as possible with something like this. MiRO if you’re reading this then you’re a good YouTube Modder/Tweaker!

If you sure that it related to new YT’s navigate to settings - YouPiP and activate Fake YouTube version.

**Comment by arichorn** [comment]
Wait you actually have to have the fake YouTube version on? It works fine without it on. Sorry if i didn’t know if it was important

**Comment by dayanch96** [comment]
> Wait you actually have to have the fake YouTube version on? It works fine without it on. Sorry if i didn’t know if it was important

honestly, never saw high contrast icons on tft screens

**Comment by arichorn** [comment]
![3AD9863E-9735-4C9D-97C4-24517B0A7CB7](https://user-images.githubusercontent.com/78001398/174461779-f729e46e-0181-4740-84b7-6d2bd4f76966.jpeg)
![81F77C81-1D7E-4BD6-9622-212F55B397C2](https://user-images.githubusercontent.com/78001398/174461871-6d6b3adf-f079-4e8e-b512-10a55f476ab9.jpeg)
This is the settings. and it is uYouPlus but modified a slightly bit.

**Comment by dayanch96** [comment]
> ![3AD9863E-9735-4C9D-97C4-24517B0A7CB7](https://user-images.githubusercontent.com/78001398/174461779-f729e46e-0181-4740-84b7-6d2bd4f76966.jpeg)
> ![81F77C81-1D7E-4BD6-9622-212F55B397C2](https://user-images.githubusercontent.com/78001398/174461871-6d6b3adf-f079-4e8e-b512-10a55f476ab9.jpeg)
> This is the settings. and it is uYouPlus but modified a slightly bit.

Thanks for explanation. I know. I meant tab bar icons. YouPiP has Fake YT version feature. If that bright icons only in 17.x version you can make YT thinks you’re using 16.x version of YT.

**Comment by arichorn** [comment]
Fake YT version feature is a good thing for YTDisableHighContrastIcons but the reason why I’m telling y’all not to use it is because there’s a terrible issue where it breaks the YouTube Player.

Here’s an Example ![6697DC3B-AB7C-4C78-8DE1-D15A5E94873E](https://user-images.githubusercontent.com/78001398/174463500-eaf4ba3a-818c-4430-8a33-1b14b4f8f120.jpeg)

In order to fix this is too disable the YouTube Fake Version but for me I gotta somehow fix this problem because I don’t know why it makes all of the options on the YouTube Player invisible.

**Comment by arichorn** [comment]
This feature suggestion has been moved to #152 
This topic is now closed!
