### ISSUE TITLE
Pip black screen

### ISSUE THREAD

**Issue by bolognayballs** [MiRO92/uYou-for-YouTube#147]
When playing a video in pip there is no picture only black screen and then pauses when you move it to the side
![53553A7A-0253-4BFA-ADA5-772369D4936E](https://user-images.githubusercontent.com/69094717/174834345-fc9cc4b6-71cb-42c5-a003-5289946dc4c7.png)

**Comment by arichorn** [comment]
I think this isn’t caused by uYou, uYou force-enables this PiP option on the YouTube app and using pip with YouTube v16.42.3 is probably unstable and buggy, it could be fixed if MiRO92 updates the YouTube IPA with the current version but right now he’s busy
