### ISSUE TITLE
Compatibility with ios 16 beta?

### ISSUE THREAD

**Issue by skripter888** [MiRO92/uYou-for-YouTube#148]
I tried to install on ios 16 beta but it doesn't run. Is it available?

**Comment by francescospelta** [comment]
Works fine for me on iOS 16b2 iPhone 11. I sideload it weekly via AltStore using the `[.ipa](https://miro92.com/repo/depictions/com.miro.uyou/iPA/YouTube_16.42.3_uYou_2.1.ipa)` here on GitHub.

**Comment by skripter888** [comment]
Oh really… oh then I’m gonna download it

**Comment by ArmasF31** [comment]
Works fine on my phone (13 Pro) but crashes on my iPad (Pro 2021 12“ M1)

**Comment by johnzoki** [comment]
Doesn't matter if its through side loading via Mac or direkt install in Altstore, it won't work. App instantly crashes every time. (iPhone 11 Pro, iOS 16 public beta 2)
