### ISSUE TITLE
Quality Over Wifi doesn't show higher resolutions

### ISSUE THREAD

**Issue by SpaceN64** [MiRO92/uYou-for-YouTube#151]
When I open a Linus tech tips video on the regular YouTube app, I'm able to set the quality to 2160p, but on the uYou, I'm only able to set it to 1080p.

**Comment by PIORIGIN** [comment]
I made a request about it. There is a problem for higher resolution on IOS.

**Comment by SpaceN64** [comment]
> I made a request about it. There is a problem for higher resolution on IOS.

I figured it out. You just cage to turn on the codec in settings>video quality>turn the switch on
