### ISSUE TITLE
Impossible to have 4K or higher on iPhone 13 pro.

### ISSUE THREAD

**Issue by enzofrnt** [MiRO92/uYou-for-YouTube#155]
I already see an issue about that and someone talk about **YTUHD**, but apparently there is no way to add it manually to uYou.
So maybe we can make a request to have 4K in uYou ?
That really sad to have a great screen and a great Youtube app but without 4K.

**Comment by lawilson97** [comment]
Weirdly in the settings it lets you pick the quality up to 2160p 60 fps but when you go to play a video it does t support it.
