### ISSUE TITLE
Sharesheet for downloaded videos are not sized correctly

### ISSUE THREAD

**Issue by WoodpeckerBaby** [MiRO92/uYou-for-YouTube#157]
### Device info
- iOS/iPadOS version: 15.6
- Device model: iPad Pro 10.5
- Sideload tool: AltStore
- Version of uYou: 2.1

### Describe the bug

Sharesheet position and size is messed up for downloaded videos. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
![image](https://user-images.githubusercontent.com/14303318/182861941-946e555d-1d30-4032-a1ab-ae6b6c5fec18.png)

Download a video, then click share. 

### Does the issue happen with the official YouTube from AppStore?
Well, this has nothing to do with YouTube.

**Comment by arichorn** [comment]
Hey WoodpeckerBaby I have putted your listed issue in #152 because that topic will change uYou and I also list each issue I see just like this one in the topic

**Comment by arichorn** [comment]
Also the reason why the Sharesheet isn’t sized correctly is because it’s sized for the iPhones, that happens to a lot of apps though but it’s an easy fix
