### ISSUE TITLE
Swipe up to enter fullscreen on iPad

### ISSUE THREAD

**Issue by teodargent** [MiRO92/uYou-for-YouTube#158]
Hi, I recently reinstalled uyou and I can't get the swipe up to enter fullscreen feature to work anymore. I'm using an ipad pro ios 15.6. Can anybody help me? Thanks!

**Comment by arichorn** [comment]
This ain’t uYou’s problem. uYou is using the version YouTube v16.42.3 and in this version the feature called swipe up to enter fullscreen doesn’t exist. The only way for MiRO is fix this is if uYou updates its ipa for the current YouTube version.

I also have this #152 if you want to list bugs for MiRO to see. But have a great day though!

**Comment by teodargent** [comment]
ok my mistake, I was using uyou+ previously, sorry. Have a great day!
