### ISSUE TITLE
YouTube crashes when scrolling a few videos on shorts

### ISSUE THREAD

**Issue by sergealagon** [MiRO92/uYou-for-YouTube#159]
Whenever I scroll on YouTube shorts, the app crashes after 3 videos (there are some lucky cases that it takes 5-10 scrolls before the app crashes)

Tried disabling all of my tweaks (except for uYou), the issue is still there.

### **Details:**
Device: iPhone 7 Plus
iOS version: 14.4.2 (Checkra1n)
YouTube app version: 17.32.2 (official app from App Store)
uYou version: 2.1

I've seen that even people that uses uYouPlus experience the same [issue.](https://github.com/qnblackcat/uYouPlus/issues/253)

**Comment by paulscholes0258** [comment]
I confirm with same issue. 
Uyou+ Log & video
iphone xs max, ios 15.6.1
uyou+ lasted version.
https://drive.google.com/drive/folders/16TW9fvvLcakkHIvnj48E0QF94cwmODWr?usp=sharing

**Comment by tresenblanco** [comment]
Same issue with the update 17.33.2 ipa via AltStore iPhone 11 iOS 16

**Comment by arichorn** [comment]
This might be due to a uYou issue, I placed the issue in #152
I do hope MiRO92 fixes these.
