### ISSUE TITLE
(bug) can't pause music through headphones with play downloaded music

### ISSUE THREAD

**Issue by jimnychen** [MiRO92/uYou-for-YouTube#160]
Device info:

iOS/iPadOS version: 16 bata7
Device model: iPhone 8 wi-c600n
Sideload tool: Altstore
Version of uYou: v2.1
Describe the bug:
when I play downloaded music I can't pause music through the Bluetooth handphone's pause button

**Comment by arichorn** [comment]
That might be a cause from iOS 16
