### ISSUE TITLE
MiRO92’s uYou 2.4 Update + Decrypted YouTube IPA v18.09.4 [QOL/BugFixes Important Requests]

### ISSUE THREAD

**Issue by arichorn** [MiRO92/uYou-for-YouTube#164]
Not Much will be on here but some of the issues from #152 is moved here ;(

## iPhoneOS 16.2 SDK (an SDK that may be needed for building the YouTube IPA version of uYou and giving the ability to make uYou work with all of the iPhone 14 users) `https://github.com/xybp888/iOS-SDKs/releases/download/iOS-SDKs/iPhoneOS16.2.sdk.zip`

# uYou 2.4 Topic
uYou 2.3~1 has been crashing lately so I made uYou 2.4 exist. Read anything that may help you below.

## Feature(s)
-  **Low Contrast Mode** - definitely needed for some users. More info here. #189 

## Needed Quality Of Life Changes (uYou 2.4 Suggestion)
- **iOS/iPadOS 16 Support, users who use uYou 2.3~1 cannot run uYou on iOS 16 #148 - code to fix this issue can be found in #174**
- **New YouTube UI support for uYou (v18.09.4) #184**
- **options that need to be fixed on uYou is “removeYouTubeAds” & “disableAgeRestriction” since they do not work no more.**
- **Ability to hide The Download Button on the YouTube App** #181 
- **Ability to actually move the Upload Button anywhere on the bottom tab** #181 

## All Current Bugs that are in uYou 2.1-2.3~1
- **uYou Buttons not appearing under VideoPlayer, in the VideoPlayer, in YouTube ContextMenu & in VideoPlayer Settings menu**
- **Unable to post Videos/Shorts inside uYou #186**
- **Navigation Bar Disappearing within uYou Tab.** #46
- **Video Timestamps don‘t show up in Playlist and History previews. - Disable YouTube Ads Setting** #54 
- **Sharesheet for downloaded videos are not sized correctly.** #157
- **uYou can crash when scrolling a few videos on shorts.** #159 
- **Notification Crash, tapping notifications button on uYou 2.1 can crash. https://github.com/MiRO92/uYou-for-YouTube/issues/94**
- **YouTube Profile & Banner Customization Crash, changing your banner or profile picture on uYou 2.1 can crash aswell.**

not all the bugs are in here I only shared some of them so I wouldn’t give you a hard time asking to fix so many bugs that we all deal with in uYou but MiRO92 I hope this helps out if you’re doing a improvement update. Cheers ✌️

**Comment by arichorn** [comment]
Alright so everyone that’s having the issue in #171 is probably caused by YouTube’s Server-Side changes. Unfortunately there is no fix for this crash problem unless you use uYou+ but the reason why the crash cannot be fixed in 16.42.3 is because YouTube is ending its support on that version so therefore uYou will no longer work as intended. so if uYou stops working at any time then it might be the time to start using this. https://github.com/qnblackcat/uYouPlus/releases

**Comment by yodaluca23** [comment]
What's the tweak for the "Update App" menu bypass?

**Comment by arichorn** [comment]
> What's the tweak for the "Update App" menu bypass?

Well it’s not more of a tweak, it’s just a small piece of code but it really changes the app to disable the YouTube update menu.

```
// Hide YouTube’s Force-Update Menu (best for older versions of youtube)
 %hook YTGlobalConfig
 - (BOOL)shouldBlockUpgradeDialog { return YES;}
 %end
```

**Comment by arichorn** [comment]
> > What's the tweak for the "Update App" menu bypass?
> 
> Well it’s not more of a tweak, it’s just a small piece of code but it really changes the app to disable the YouTube update menu.
> 
> ```
> // Hide YouTube’s Update Menu (best for older versions of youtube)
> %hook YTGlobalConfig
> - (BOOL)shouldBlockUpgradeDialog { return YES;}
> %end
> ```

This won’t work anymore unfortunately

**Comment by arichorn** [comment]
So @MiRO92 it’s been 14 months since the last uYou update. Just gonna let you know that iOS 16 & iPhone 14 models aren’t compatible with uYou. I needed to tell you when will uYou return to patch these things? I did wait but I will never know if uYou will return.

**Comment by MiRO92** [comment]
@arichorn Yes, sure it did!, thanks a lot for your amazing help and support

**Comment by Yoddikko** [comment]
Is there a new decrypted ipa link?

**Comment by gmanc2** [comment]
@arichornlover you're a homie. In case this gets taken down, can you point me in the right direction to get the decrypted IPA myself? Let me know if you want to take this off platform.

**Comment by arichornlover** [comment]
I may stop sending the link here. This issue keeps generating high traffic when y’all download the url. I had to remove it so I wouldn’t keep getting my account suspended from Dropbox.

**Comment by Yoddikko** [comment]
> I may stop sending the link here. This issue keeps generating high traffic when y’all download the url. I had to remove it so I wouldn’t keep getting my account suspended from Dropbox.

Can you please share this link on other platforms? Google Drive should be safe to use/share?

**Comment by chlebta** [comment]
Or could you shared a tutorial for decrypting the ipa ?

**Comment by JakeAi** [comment]
> I may stop sending the link here. This issue keeps generating high traffic when y’all download the url. I had to remove it so I wouldn’t keep getting my account suspended from Dropbox.

Can you share how to decrypt the ipa?
