### ISSUE TITLE
4K playback audio issue

### ISSUE THREAD

**Issue by LancerLucky** [MiRO92/uYou-for-YouTube#165]
I turned on vp9 codec to enable 4K playback but the audio started to stutter and out of sync. I'm on iPhone 13 Pro, iOS 15.6.1.

**Comment by haomuch** [comment]
How did you turned on the vp9 codec? I can't find it in the whole app settings

**Comment by haomuch** [comment]
> I turned on vp9 codec to enable 4K playback but the audio started to stutter and out of sync. I'm on iPhone 13 Pro, iOS 15.6.1.

How did you turned on the vp9 codec? I can't find it in the whole app settings
