### ISSUE TITLE
App crashes upon opening 

### ISSUE THREAD

**Issue by Lu-Kali** [MiRO92/uYou-for-YouTube#168]
When opening the YouTube app it instantly crashes.
Im Running iOS 16.0.1 on an iPhone 14 pro. I have installed the ipa via AltStore and used version: 16.4.2.3

**Comment by mpekaros** [comment]
Alt store’s problem try with sideloadly

**Comment by futurepr0n** [comment]
Im afraid its also crashing with sideloadly too. Just tested. iOS 16.0

**Comment by rahul-sha** [comment]
I went back to uYouPlus_17.25.1_2.1 and this works on iOS 16. Not sure why.

**Comment by xSignificant** [comment]
Crashing on iOS 15.4 too

**Comment by bluepie45** [comment]
I have the latest version of the app and anytime I try to play a normal youtube video the app will instantly crash. However, all youtube shorts will play as normal. I am on IOS version 16.2 and I have uninstalled and reinstalled the app and I am still having the same issue.

**Comment by LABCN** [comment]
Same experience here. Crashing upon opening video

**Comment by lex-dj** [comment]
same problem, app crashes when I try to open it.

**Comment by MiRO92** [comment]
fixed
