### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by LABCN** [MiRO92/uYou-for-YouTube#169]
![fe267baf-690f-42f0-82eb-999e5effbacb](https://user-images.githubusercontent.com/51227126/192380505-5389fdc3-6930-472a-a40c-fd23208862d3.jpg)

**Comment by GabrielRuizVarela** [comment]
Any update on this?

**Comment by lphuctai** [comment]
I have the same error

**Comment by lphuctai** [comment]
I have the same error and with multiple old version before @@
I try to restart my phone, Reinstall Altstore, try another version, still the same @@
