### ISSUE TITLE
Watching video crashes the app

### ISSUE THREAD

**Issue by LOKSTED** [MiRO92/uYou-for-YouTube#171]
It was fine yesterday and Shorts still works

**Comment by Maxokaan** [comment]
Same issue here. Can’t use the application anymore

**Comment by KyroLYG** [comment]
Okay, im not the only one. You guys using any  working alternatives?

**Comment by Maxokaan** [comment]
@KyroLYG I downloaded the latest version and itMs working again.‘

**Comment by arichorn** [comment]
I knew this was happening, when I was on 16.42.3 YouTube couple days ago I was having trouble playing videos and now it is now showing a pop up to update YouTube aswell. We really gotta contact MiRO92

**Comment by Moisty-Macros** [comment]
same thing with me I'm going to try a newer version
