### ISSUE TITLE
[Feature Request] UI color settings

### ISSUE THREAD

**Issue by iRayanKhan** [MiRO92/uYou-for-YouTube#18]
Tweaks like YTReborn would allow you to modify the UI's color (mainly to get OLED black), but it's no longer updated, and uYou is better. 

Thanks,
   Rayan

**Comment by MiRO92** [comment]
Am sorry but I have no interest /plans to add UI coloring into uYou.

**Comment by iRayanKhan** [comment]
Thanks for the reply. 

If a donation gives you incentive I'd be happy to, but I understand.
