### ISSUE TITLE
[Feature] Option to hide download buttons | other QOL enhancements

### ISSUE THREAD

**Issue by yodaluca23** [MiRO92/uYou-for-YouTube#181]
1. Have the option to move the download video buttons seen on shorts and full lengths to the video's "3 Dot" menu...
2. Have the option to make the uYou settings and downloaded videos menu accessed from YouTube settings and not take up a bottom tab.
3. Fix the bug where when showing the "Create" button it sticks to the right and will refuse to move to the designated position...

**Comment by arichorn** [comment]
Alright I’ll put this in uYou 2.2 Suggestions —> #164
I put everything in there so MiRO92 can easily improve uYou with this
