### ISSUE TITLE
Introduction Page(?) on first launch

### ISSUE THREAD

**Issue by selnisa** [MiRO92/uYou-for-YouTube#185]
![16714FD8-60F6-482B-AFC3-3D31CE5EE0BF](https://user-images.githubusercontent.com/116909637/198696329-8fdfb646-95ae-46c4-a070-da98c6f1009f.png)

It’s not possible to slide down or close. I can limitedly browse with some tricks but it always comes back. What can I do about it?

**Comment by arichorn** [comment]
Ummm.. @qnblackcat check this out.
Wish I could tell MiRO about this but they’re not online.

**Comment by selnisa** [comment]
It disappeared after a day of using the app. Hope it won’t come again
