### ISSUE TITLE
Unable to post from inside uYou

### ISSUE THREAD

**Issue by Straunge** [MiRO92/uYou-for-YouTube#186]
I am unable to post videos and/or shorts content using the uyou app. No menu options are currently present to navigate to a menu to upload content.

**Comment by arichorn** [comment]
Yeah. uYouPlus does fix this issue but I do want normal ui to fix it.

**Comment by Straunge** [comment]
> Yeah. uYouPlus does fix this issue but I do want normal ui to fix it.

Can I ask how/where? I’m currently using UY+ and I am unable to upload from within the app.

**Comment by arichorn** [comment]
go to uYou Settings and go to Hide Tabs and then toggle off "Hide Create Tab"
