### ISSUE TITLE
Can't login - Google states it is not safe

### ISSUE THREAD

**Issue by bleidzki** [MiRO92/uYou-for-YouTube#190]
Hello, 
When trying to log in using Google account, right after putting email in, I get error that I cannot login here because it is not a safe application.

Did anyone have this? Thanks a lot.

**Comment by Xykrotik** [comment]
Hey!

I also received this message when attempting to log in just now. 

"You can't sign in to this app because Google can't confirm that it's safe" 

Unsure why, perhaps I missed a step, going to comb the install guides again just in case.

**Comment by Xykrotik** [comment]
[Found this in the FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-you-cant-sign-in-to-this-app-because-google-cant-confirm-that-its-safe-warning-when-signing-in)

**Comment by Bick-Tore** [comment]
It still gives me the same error even after trying the method in the FAQ. I've transferred to a new phone and it didn't keep me signed in on uyouplus.

**Comment by JMcrafter26** [comment]
Hi there, 
I found an updated version of this, by qnblackcat. Beside the many tweaks added, it removes the "can't confirm that it's safe" error.

Project: https://github.com/qnblackcat/uYouPlus

Happy coding!

**Comment by ubudee** [comment]
> 

How can i get the IPA file of his version?

**Comment by JMcrafter26** [comment]
> How can i get the IPA file of his version?

Just go to the release tab and select a version (the newest is the best). At the bottom of the selected version you can find the ipa file.

Or to keep it simple, here is the direct link of the newest ipa file: 
https://github.com/qnblackcat/uYouPlus/releases/download/v17.43.1-2.1/uYouPlus_17.43.1_2.1.ipa

**Comment by ubudee** [comment]
> > How can i get the IPA file of his version?
> 
> Just go to the release tab and select a version (the newest is the best). At the bottom of the selected version you can find the ipa file.
> 
> Or to keep it simple, here is the direct link of the newest ipa file: https://github.com/qnblackcat/uYouPlus/releases/download/v17.43.1-2.1/uYouPlus_17.43.1_2.1.ipa

Hi JMcraft26,

I just noticed that i had the last version already by looking at the version number.
Unfortunately i still have the error and can't login on Google.
Could it be that i am doing something wrong? Or is it Google?

**Comment by JMcrafter26** [comment]
> > > How can i get the IPA file of his version?
> > 
> > 
> > Just go to the release tab and select a version (the newest is the best). At the bottom of the selected version you can find the ipa file.
> > Or to keep it simple, here is the direct link of the newest ipa file: https://github.com/qnblackcat/uYouPlus/releases/download/v17.43.1-2.1/uYouPlus_17.43.1_2.1.ipa
> 
> Hi JMcraft26,
> 
> I just noticed that i had the last version already by looking at the version number. Unfortunately i still have the error and can't login on Google. Could it be that i am doing something wrong? Or is it Google?

Hi there,
What tool are you using to sign and get the ipa on your device?

I would recommend using sideloadly, because I don't have any problems with it

**Comment by ubudee** [comment]
> > > > How can i get the IPA file of his version?
> > > 
> > > 
> > > Just go to the release tab and select a version (the newest is the best). At the bottom of the selected version you can find the ipa file.
> > > Or to keep it simple, here is the direct link of the newest ipa file: https://github.com/qnblackcat/uYouPlus/releases/download/v17.43.1-2.1/uYouPlus_17.43.1_2.1.ipa
> > 
> > 
> > Hi JMcraft26,
> > I just noticed that i had the last version already by looking at the version number. Unfortunately i still have the error and can't login on Google. Could it be that i am doing something wrong? Or is it Google?
> 
> Hi there, What tool are you using to sign and get the ipa on your device?
> 
> I would recommend using sideloadly, because I don't have any problems with it

Ah, i am using alt store since my device is not jailbreaked.

**Comment by ubudee** [comment]
> > > > > > How can i get the IPA file of his version?
> > > > > 
> > > > > 
> > > > > Just go to the release tab and select a version (the newest is the best). At the bottom of the selected version you can find the ipa file.
> > > > > Or to keep it simple, here is the direct link of the newest ipa file: https://github.com/qnblackcat/uYouPlus/releases/download/v17.43.1-2.1/uYouPlus_17.43.1_2.1.ipa
> > > > 
> > > > 
> > > > Hi JMcraft26,
> > > > I just noticed that i had the last version already by looking at the version number. Unfortunately i still have the error and can't login on Google. Could it be that i am doing something wrong? Or is it Google?
> > > 
> > > 
> > > Hi there, What tool are you using to sign and get the ipa on your device?
> > > I would recommend using sideloadly, because I don't have any problems with it
> > 
> > 
> > Ah, i am using alt store since my device is not jailbreaked.
> 
> Just like I said, I would recommend using sideloadly. It's a free tool available for Mac and PC. When signing uYou+ using sideloadly make sure to activate Sideload Spooner.

Thank you very much JMcrafter, i will try it out.

**Comment by JMcrafter26** [comment]
> > > > > > > How can i get the IPA file of his version?
> > > > > > 
> > > > > > 
> > > > > > Just go to the release tab and select a version (the newest is the best). At the bottom of the selected version you can find the ipa file.
> > > > > > Or to keep it simple, here is the direct link of the newest ipa file: https://github.com/qnblackcat/uYouPlus/releases/download/v17.43.1-2.1/uYouPlus_17.43.1_2.1.ipa
> > > > > 
> > > > > 
> > > > > Hi JMcraft26,
> > > > > I just noticed that i had the last version already by looking at the version number. Unfortunately i still have the error and can't login on Google. Could it be that i am doing something wrong? Or is it Google?
> > > > 
> > > > 
> > > > Hi there, What tool are you using to sign and get the ipa on your device?
> > > > I would recommend using sideloadly, because I don't have any problems with it
> > > 
> > > 
> > > Ah, i am using alt store since my device is not jailbreaked.
> > 
> > 
> > Just like I said, I would recommend using sideloadly. It's a free tool available for Mac and PC. When signing uYou+ using sideloadly make sure to activate Sideload Spooner.
> 
> Thank you very much JMcrafter, i will try it out.

No problem, let me know if it works

**Comment by ubudee** [comment]
> > > > > > > > How can i get the IPA file of his version?
> > > > > > > 
> > > > > > > 
> > > > > > > Just go to the release tab and select a version (the newest is the best). At the bottom of the selected version you can find the ipa file.
> > > > > > > Or to keep it simple, here is the direct link of the newest ipa file: https://github.com/qnblackcat/uYouPlus/releases/download/v17.43.1-2.1/uYouPlus_17.43.1_2.1.ipa
> > > > > > 
> > > > > > 
> > > > > > Hi JMcraft26,
> > > > > > I just noticed that i had the last version already by looking at the version number. Unfortunately i still have the error and can't login on Google. Could it be that i am doing something wrong? Or is it Google?
> > > > > 
> > > > > 
> > > > > Hi there, What tool are you using to sign and get the ipa on your device?
> > > > > I would recommend using sideloadly, because I don't have any problems with it
> > > > 
> > > > 
> > > > Ah, i am using alt store since my device is not jailbreaked.
> > > 
> > > 
> > > Just like I said, I would recommend using sideloadly. It's a free tool available for Mac and PC. When signing uYou+ using sideloadly make sure to activate Sideload Spooner.
> > 
> > 
> > Thank you very much JMcrafter, i will try it out.
> 
> No problem, let me know if it works

Hi JMcraft26, i just tried it out with sideloadly.
Unfortunately that did not work.
You also said something about Sideload Spooner.
Could you please tell what that is and how i can activate it?

**Comment by JMcrafter26** [comment]
> > > > > > > > > How can i get the IPA file of his version?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Just go to the release tab and select a version (the newest is the best). At the bottom of the selected version you can find the ipa file.
> > > > > > > > Or to keep it simple, here is the direct link of the newest ipa file: https://github.com/qnblackcat/uYouPlus/releases/download/v17.43.1-2.1/uYouPlus_17.43.1_2.1.ipa
> > > > > > > 
> > > > > > > 
> > > > > > > Hi JMcraft26,
> > > > > > > I just noticed that i had the last version already by looking at the version number. Unfortunately i still have the error and can't login on Google. Could it be that i am doing something wrong? Or is it Google?
> > > > > > 
> > > > > > 
> > > > > > Hi there, What tool are you using to sign and get the ipa on your device?
> > > > > > I would recommend using sideloadly, because I don't have any problems with it
> > > > > 
> > > > > 
> > > > > Ah, i am using alt store since my device is not jailbreaked.
> > > > 
> > > > 
> > > > Just like I said, I would recommend using sideloadly. It's a free tool available for Mac and PC. When signing uYou+ using sideloadly make sure to activate Sideload Spooner.
> > > 
> > > 
> > > Thank you very much JMcrafter, i will try it out.
> > 
> > 
> > No problem, let me know if it works
> 
> Hi JMcraft26, i just tried it out with sideloadly. Just wanted to let you know that it worked! Thanks!

Hi there,
I have added an image to this message.
The red circled options mean, that you need to activate them. When doing this it works fine for me. (This is not my Screenshot, I found it on the internet so the spoofer setting isn't there, but you should activate it)

**Comment by Saud-97** [comment]
I just wanted to add that I have it on Altstore and it works just fine. Try to remove Extension during install or install official youtube first and login there then try it again.

**Comment by pejeio** [comment]
Not working for me on Altstore. Tried to copy and paste the URL in a Safari incognito window, but the same "Unsafe" message is shown. 😞

**Comment by JustJ45on** [comment]
> 

How do you enable Sideload Spooner?
