### ISSUE TITLE
Why does it take so long to refresh via AltStore?

### ISSUE THREAD

**Issue by mili988** [MiRO92/uYou-for-YouTube#192]
Hey,

i am using ios 16.1.1 + iphone 14.
The installation was not a big deal, and it works whithous issues - but after manual refresh it takes hours to refresh,it also can happen, that the refresh does not work in a way.

Can you help out here?
Thx!

**Comment by heIlo** [comment]
same here, i can't update the app recently because it takes forever to install

**Comment by AndresGarciaSobrado91** [comment]
and close to finishing the installation crashes 😞

**Comment by jly26** [comment]
same issue here..any work around??
