### ISSUE TITLE
[iOS 16.2 b4] uYou Crashed when open app.

### ISSUE THREAD

**Issue by james2811** [MiRO92/uYou-for-YouTube#193]
I install uYou through BullFrog Assistant. But it keep crashing on iOS 16.2 b4. Others app works fine. Please help me.

**Comment by arichorn** [comment]
uYou might not be supported with iOS 16 (including iPhone 14 Pro/Pro Max)
Wish MiRO had time to update it so I could use it again on modern iOS versions.

**Comment by Khanhdeptrai95** [comment]
Same problem
