### ISSUE TITLE
uYou crashing (along with other apps) on iOS 16.1 on iPhone 14 PM with AltStore

### ISSUE THREAD

**Issue by skripter888** [MiRO92/uYou-for-YouTube#194]
Gey guys! I installed uYou as usual and as soon as I launch the app it crashes, popping this message for a second. 
I also downloaded Twitch++ and it also crashes. 
It was all good with iOS 15 on my previous iPhone 13 PM, but now all crashes. 

Any idea what can be the issue? 
The altstore app itself runs smoothly without issues, but the ipas I install get crashed immediately. 
TYIA❤️🙏
https://user-images.githubusercontent.com/6491850/205903265-dc6a63e9-a244-4421-9cf9-4b70cc474c42.MOV

**Comment by r4f4w** [comment]
Same phone, same iOS, and same problem here! Hope they fix this soon!

**Comment by arichorn** [comment]
uYou doesn’t support iPhone 14s and iOS 16 
That’s how it crashes ;/

**Comment by ashrafur89** [comment]
uYou doesn’t work on iPhone 14 Pro Max and iOS 16.2. Keeps crashing at load window.

**Comment by skripter888** [comment]
Got it! It didn’t work on my phone model and iOS. 
I acknowledged to download uYou Plus but can’t log in. Pity

**Comment by chigo96** [comment]
It should have been sated that it doesn't work for ios 16.2. I had the old version working on my ipad so I deleted it to download the new one and it crashes so I went back to install the old one and that crashes too now

**Comment by ashrafur89** [comment]
@chigo96 Same....been trying the ipa all day everyday hoping there change made but still no luck. until devs fix it for 16.2 on iPhone 14 we are on holding pattern

**Comment by chigo96** [comment]
> @chigo96 Same....been trying the ipa all day everyday hoping there change made but still no luck. until devs fix it for 16.2 on iPhone 14 we are on holding pattern

at least you if you're only interested in blocking ads you can still watch YouTube on safari with the ad guard extension

**Comment by ashrafur89** [comment]
Oh I didn't know we could do that. i use it mainly for AdBlock. thank you. let me try that.

**Comment by skripter888** [comment]
> @chigo96 Same....been trying the ipa all day everyday hoping there change made but still no luck. until devs fix it for 16.2 on iPhone 14 we are on holding pattern

Or you can just download uyou+ via appbd, works without a mac and sideloadly app, directly from safari. First you link device by downloading a certificate and then download any apps (30/monthly). 

I live you a link: https://appdb.to/app/cydia/1900000830

You can download any app from there.

**Comment by chigo96** [comment]
@skripter888 thanks for the suggestion, I just tried it and it works although I tried to download youtube music and it downloaded but it crashes as soon as I try to open it

**Comment by skripter888** [comment]
![295337C3-444F-4FF3-958B-0E4F5EC8E723](https://user-images.githubusercontent.com/6491850/211129680-067a1fb7-3881-42d0-a586-954a48c91274.jpeg)


Every app has it’s tweaked option. When you enter the youtube music app page, scroll down and you will see tweaked versions that exist. Try each one in this case till you make it work, they’re only 3 tweaked versions available for Youtube Music. 

https://appdb.to/app/ios/1017492454

**Comment by chigo96** [comment]
@skripter888 Hi, I got the message yesterday when I tried to open one of the apps I downloaded from appdb

![IMG_0372](https://user-images.githubusercontent.com/122126841/211841515-cd187064-26d1-49c6-b366-4977e8829627.png)

**Comment by skripter888** [comment]
> @skripter888 Hi, I got the message yesterday when I tried to open one of the apps I downloaded from appdb
> 
> ![IMG_0372](https://user-images.githubusercontent.com/122126841/211841515-cd187064-26d1-49c6-b366-4977e8829627.png)

Dis you try yet “Scarlet”? 
that app is the biggest achievement i’ve ever seen for installing .ipa on an iOS till this moment. 

You don’t need to download anything in the computer nor anything else besides of directly installing it in your phone and right after select an ipa to install it directly in the phone 


Till now it hasnt failed or needed any reinstalling due to a revoke or anything like that. 

After 7 days I’ll see if it needs refreshing or not, or if on the contrary it doesn’t get revoked. 

Try that thing. It’s by far the best tool 8’ve ever used as an alternative ipa installer. By far better than appdb or Altstore itself

**Comment by chigo96** [comment]
> > @skripter888 Hi, I got the message yesterday when I tried to open one of the apps I downloaded from appdb
> > ![IMG_0372](https://user-images.githubusercontent.com/122126841/211841515-cd187064-26d1-49c6-b366-4977e8829627.png)
> 
> Dis you try yet “Scarlet”? that app is the biggest achievement i’ve ever seen for installing .ipa on an iOS till this moment.
> 
> You don’t need to download anything in the computer nor anything else besides of directly installing it in your phone and right after select an ipa to install it directly in the phone
> 
> Till now it hasnt failed or needed any reinstalling due to a revoke or anything like that.
> 
> After 7 days I’ll see if it needs refreshing or not, or if on the contrary it doesn’t get revoked.
> 
> Try that thing. It’s by far the best tool 8’ve ever used as an alternative ipa installer. By far better than appdb or Altstore itself

do you mind dropping a link to where I can download it

**Comment by skripter888** [comment]
> > > @skripter888 Hi, I got the message yesterday when I tried to open one of the apps I downloaded from appdb
> > > ![IMG_0372](https://user-images.githubusercontent.com/122126841/211841515-cd187064-26d1-49c6-b366-4977e8829627.png)
> > 
> > 
> > Dis you try yet “Scarlet”? that app is the biggest achievement i’ve ever seen for installing .ipa on an iOS till this moment.
> > You don’t need to download anything in the computer nor anything else besides of directly installing it in your phone and right after select an ipa to install it directly in the phone
> > Till now it hasnt failed or needed any reinstalling due to a revoke or anything like that.
> > After 7 days I’ll see if it needs refreshing or not, or if on the contrary it doesn’t get revoked.
> > Try that thing. It’s by far the best tool 8’ve ever used as an alternative ipa installer. By far better than appdb or Altstore itself
> 
> do you mind dropping a link to where I can download it. I tried downloading it and I get the same error message


here you go: https://usescarlet.com/

**Comment by chigo96** [comment]
@skripter888 thanks for  your help but my phone still won't let me verify the app probably resetting it would fix it but I'm not willing to do  that. Thanks anyway

**Comment by skripter888** [comment]
> @skripter888 thanks for your help but my phone still won't let me verify the app probably resetting it would fix it but I'm not willing to do that. Thanks anyway

Did you go to settings --> profiles --->  whatever it says (look it up) ---> trust this ?

if you do not do that of course it won't open.
try doing it first

**Comment by chigo96** [comment]
> > @skripter888 thanks for your help but my phone still won't let me verify the app probably resetting it would fix it but I'm not willing to do that. Thanks anyway
> 
> Did you go to settings --> profiles ---> whatever it says (look it up) ---> trust this ?
> 
> if you do not do that of course it won't open. try doing it first

I did that and it even says it is verified when you go there
![IMG_0387](https://user-images.githubusercontent.com/122126841/212158701-818ed620-c575-4741-aacb-1c6b6c40ad0e.png)

**Comment by chigo96** [comment]
I got an older version of the youtube app to work using altstore. If anyone is interested I can share the IPA file

**Comment by ManishwarG** [comment]
> I got an older version of the youtube app to work using altstore. If anyone is interested I can share the IPA file

Does the ipa file work with ios 16.3 ?? if yes can you please share the ipa. @chigo96

**Comment by chigo96** [comment]
@ManishwarG I have not updated to ios 16.3 yet but the one I'm currently using works on ios 16.2
