### ISSUE TITLE
Downloads are really slow compared to other Youtube download apps

### ISSUE THREAD

**Issue by PalmTamino** [MiRO92/uYou-for-YouTube#196]
https://streamable.com/9pvukn

**Comment by leo04real** [comment]
Hello, can I have the ipa version of the cercubePlus that you used to show a higher downloading speed?

**Comment by PalmTamino** [comment]
> Hello, can I have the ipa version of the cercubePlus that you used to show a higher downloading speed?

Hey, this was the original while being jailbroken on XinaA15 (Injected as tweak)

**Comment by leo04real** [comment]
Okay, thanks for your response.

**Comment by aaronliu0130** [comment]
@MiRO92 Is there a reason this was closed?
