### ISSUE TITLE
uyou 2.1 "update available" but no new link to ipa

### ISSUE THREAD

**Issue by Chad90b** [MiRO92/uYou-for-YouTube#198]
as title suggests the app is now informing users of a new version being out but there are no links to the ipa anywhere on the update page nor on github. where is this new version "2.3~1" and how do we get it?

**Comment by hfagelnour** [comment]
up

**Comment by Alexei32** [comment]
same here

**Comment by tyhallcsu** [comment]
Same

**Comment by iyuki0430** [comment]
same here

**Comment by sadeepdarshana** [comment]
same

**Comment by CoolandonRS** [comment]
Same here

**Comment by mozbius** [comment]
Same here. I have also tried https://miro92.com/repo/depictions/com.miro.uyou/iPA/YouTube_16.42.3_uYou_2.3~1.zip but that didn’t help.

**Comment by Snehasis124** [comment]
Same here

**Comment by tuobraun** [comment]
Same here
