### ISSUE TITLE
[Sideloading issue]

### ISSUE THREAD

**Issue by turannul** [MiRO92/uYou-for-YouTube#20]
![A3693BF8-9BCD-4491-BFA9-2EE623433AFF](https://user-images.githubusercontent.com/84424530/131484979-6dec529f-48b7-44ac-8302-f8e8f385db5a.png)
I tried keep & remove extensions, I still couldn't install it :(
uYou 1.4-1.6 Same error

**Comment by turannul** [comment]
I hate windows,
 It’s Altstore error caused iCloud for windows app. 
 Reinstalling iCloud Fixes this

**Comment by qnblackcat** [comment]
Hi! Have you tried uYou v1.6? Did it work with AltStore? (free developer account)

**Comment by turannul** [comment]
> Hi! Have you tried uYou v1.6? Did it work with AltStore? (free developer account)
> 
> The app crashes on launching on my phone

I not tried yet

**Comment by qnblackcat** [comment]
Ok. Please tell me the result after you try it

**Comment by turannul** [comment]
> Ok. Please tell me the result after you try it

I installed with (keep app extensions) It works 
on iOS 14.7.1 
![6C1A13FC-695F-4D25-AEF9-B7B0D9CB14F8](https://user-images.githubusercontent.com/84424530/131524757-481059c3-bf6e-47ba-81f9-49e93ff844e3.png)
