### ISSUE TITLE
Error: 503 when downloading video

### ISSUE THREAD

**Issue by KECakes59** [MiRO92/uYou-for-YouTube#200]
I don't know if this happens to some, but there are specific videos that show up the 503 error whenever I get to the video portion of the download. I'm aware of the 403 error that sometimes occurs and can easily fix the problem, but I'm lost as to solving the 503 error whenever using uYou. I've provided an image below of a video that always gets the 503 error.

This is on the jailbroken version, if it helps.

![IMG_8EBE24BEB5F7-1](https://user-images.githubusercontent.com/64921200/209862458-b68848b9-9198-4465-8beb-beeda060d771.jpeg)

**Comment by bromptonista** [comment]
How do you fix the 403 error?
