### ISSUE TITLE
uYou crashes immediately

### ISSUE THREAD

**Issue by gPhantasm** [MiRO92/uYou-for-YouTube#201]
Using the newest IPA for uYou on an iPhone XS with AltStore. Upon opening, the app crashes after displaying the sign in menu for about half a second. This occurs in iOS 16.1 and iOS 16.2. It's also worth noting that all of my other sideloaded apps do not have this issue.

**Comment by RexLuscus56** [comment]
There are/were similar issues with cercube. Try turning on airplane mode, start the app, then turn off airplane mode. Note that YouTube is constantly changing details of its login system to frustrate users of ‘unofficial’ apps

**Comment by fabiantran5200** [comment]
I experience the same issue. Turning on airplane mode doesnt seem to help

**Comment by mikajx** [comment]
Same here

**Comment by benoitvinc** [comment]
Same here

**Comment by Khanhdeptrai95** [comment]
Same here

**Comment by abhishek7791** [comment]
SAME ISSUE...IOS 16.2 iphone 14 plus...

**Comment by abhishek7791** [comment]
> There are/were similar issues with cercube. Try turning on airplane mode, start the app, then turn off airplane mode. Note that YouTube is constantly changing details of its login system to frustrate users of ‘unofficial’ apps

Not Working

**Comment by johnzoki** [comment]
I deinstalled the app when I tried to install "the new version" everyone was prompted to install. This version turned out non existing. So by reinstalling the "old version" I was welcomed back with this error. Love it

**Comment by jbells2k** [comment]
Same problem. Immediately  crashes on launch. 16.2 Ipad pro 10.5. Aitplane mod does not help.

**Comment by Dem3105** [comment]
Crashes, same here

**Comment by kftX** [comment]
Same issue here, iPhone 12 Pro. Running iOS 16.3b but since it's happening on stable too I assume it's not that.

**Comment by Vis-42** [comment]
Same issue

**Comment by abdo71999** [comment]
same issue

**Comment by Maxokaan** [comment]
Any fixes for this already? Using the vanilla Youtube makes me depressed...

**Comment by Maxokaan** [comment]
The old version opens fine, with the update pop up, but when I try to watch video's the app crashes. Shorts seem fine

**Comment by vahotm** [comment]
Where to download previous version?

**Comment by abhishek7791** [comment]
> Where to download previous version?

You can download older version from here... I would recommend to download 2.1 version...
https://github.com/qnblackcat/uYouPlus/releases
