### ISSUE TITLE
Why IPA File not work 7 to 8 days after that the file is no longer available.

### ISSUE THREAD

**Issue by banikajay039** [MiRO92/uYou-for-YouTube#202]
when i install ipa file thn the app work 7 to 8 days . after that the file is no longer available.

**Comment by JimDude7404** [comment]
Either your stupid or you dont read or both! The readme says you need a paid Apple Developer account or you have to resign every 7 days. So pay Apple $100 then it no longer expires! 😃

**Comment by johnzoki** [comment]
Could somebody close this issue 😂😂😂
