### ISSUE TITLE
Speed of video not persistent 

### ISSUE THREAD

**Issue by romantra** [MiRO92/uYou-for-YouTube#210]
![3736C094-80CF-48DC-A49C-14602CCB564D](https://user-images.githubusercontent.com/48365913/211208828-a238938f-e0b1-4f18-b48e-46708ce2eabb.jpeg)

**Comment by romantra** [comment]
In the previous versions when you play a video and modify the speed of play and you switch to other video (without closing the previous video) the speed remains as you previously configure. But now in this latest version the speed resets to default speed every time you switch of video. Is this a bug of the new uYou 2.3~1 version ?

**Comment by MiRO92** [comment]
fixed
