### ISSUE TITLE
Crashes on start and takes forever to import on altstore

### ISSUE THREAD

**Issue by RTRoach** [MiRO92/uYou-for-YouTube#214]
Crashes after opening on both unjailbroken on ios 16.0.2 and jailbroken on ios 14.2

**Comment by Ungeneer** [comment]
Same here

**Comment by BubbyWoodz** [comment]
Yes it crashes on opening on non jailbroken with altstore.

**Comment by Soltra45** [comment]
iPhone 12 Pro Max non-jailbroken using AltStore to sideload. Crash on start every time.

**Comment by Long18** [comment]
Iphone 11 non-jailbreak ios 16.2 using AltStore to install. Crash on start
