### ISSUE TITLE
Remap Native YouTube Download With uYou's

### ISSUE THREAD

**Issue by yodaluca23** [MiRO92/uYou-for-YouTube#215]
Remap [this button](https://ibb.co/2crzJXF) shown underneath any full-length video, that [when clicked on](https://ibb.co/FkrsZTS) gives an advertisement for YouTube Premium, to that of the uYou downloader...

**Comment by GreenDiscord** [comment]
+!, very helpful

**Comment by MiRO92** [comment]
sorry i can't
