### ISSUE TITLE
Feature request: option to remove YouTube Search Suggestions

### ISSUE THREAD

**Issue by thesoloist-1** [MiRO92/uYou-for-YouTube#219]
YouTube has lost it's mind with search results. You search for something and it shows you an infinite list of suggested videos that have nothing to do with your search topic. Adding this feature would relieve a lot of annoyance while trying to search for a video on YouTube. This is possible by example from the Firefox extension  "YouTube Search Fixer". It does just that, removes the suggested videos and only leaves you with the results from what you searched just like the old days.

**Comment by mystrd** [comment]
+1 for YouTube Search Fixer intergration, currently you kindly get this function by changing the sort options
