### ISSUE TITLE
v1.6.1 update

### ISSUE THREAD

**Issue by birdfly** [MiRO92/uYou-for-YouTube#22]
I got a update tips for v 1.6.1,but where I can find this version

**Comment by theoccurrence** [comment]
I recommend this version for sideloading. It has uYou 1.6.1 in it. https://appdb.to/app/cydia/1900000830

**Comment by Dangduytoan12l** [comment]
Why there is no sponsorblock and auto pip when i use uyou 1.6

**Comment by qnblackcat** [comment]
> Why there is no sponsorblock and auto pip when i use uyou 1.6

This is the official version of uYou. Obviously, it only has uYou injected. read the description carefully next time

**Comment by theoccurrence** [comment]
> Why there is no sponsorblock and auto pip when i use uyou 1.6

Every sideloadable IPA, that includes isponsorblock and youPiP, that I'm aware of, have already been updated to uYou 1.6.1.

These are uYou+ and RebornAgain.

**Comment by Dangduytoan12l** [comment]
But these features have on uyou 1.4> > Why there is no sponsorblock and auto pip when i use uyou 1.6
> 
> 
> 
> This is the official version of uYou. Obviously, it only has uYou injected. read the description carefully next time

**Comment by qnblackcat** [comment]
> But these features have on uyou 1.4> > Why there is no sponsorblock and auto pip when i use uyou 1.6
> 
> > This is the official version of uYou. Obviously, it only has uYou injected. read the description carefully next time

It means you used the modified version of uYou (1.4), not the official version of uYou.
