### ISSUE TITLE
Brightness in Gesture control doesn’t work on iOS 16

### ISSUE THREAD

**Issue by daylightsss** [MiRO92/uYou-for-YouTube#220]
The volume gesture works fine but the brightness can only turn it a little bright or dark. It’s like a switch instead of percentages.

**Comment by Ljfe** [comment]
Me too. iPhone 14 pro max ios 16.2.

**Comment by schweppes-0x** [comment]
same here! I am experiencing this since a long time now. hopefully will be fixed soon!

**Comment by Yaron2334** [comment]
Still not working, is it beeing worked on?

**Comment by schweppes-0x** [comment]
experiencing the same issue

**Comment by Aransh** [comment]
@MiRO92 Still seeing this on v3.0.2

**Comment by daylightsss** [comment]
> @MiRO92 Still seeing this on v3.0.2

Same here. Sorry.
