### ISSUE TITLE
iOs 16.2 iphone 14prom max couldn't sign in

### ISSUE THREAD

**Issue by aelkorchi** [MiRO92/uYou-for-YouTube#221]
Dear developer please i have a problem in youtube i cant access with my gmail account IN IPHONE 14 PRO MAX IOS 16.2 see photo below![image](https://user-images.githubusercontent.com/32000724/213410833-08a3a600-8b99-4942-ba5f-20c6cb0f3e99.jpeg)

I have folow up the method of shortcuts and Sideloadly... but can't sing in

Could you help please

**Comment by aelkorchi** [comment]
https://user-images.githubusercontent.com/32000724/213431132-518c6def-2dbe-443a-875b-4aec31f25ea1.MOV

I tried sideloadly but the app not opened

**Comment by mr-utilman** [comment]
Same

**Comment by stormv777** [comment]
Sabe

**Comment by Ronygithu** [comment]
I have solution about this problem ****

**Comment by aelkorchi** [comment]
Share it please

**Comment by Ronygithu** [comment]
> Share it please 

Wait

**Comment by Ronygithu** [comment]
https://github.com/qnblackcat/uYouPlus/discussions/683
