### ISSUE TITLE
Crash on start iPhone 14 Pro Max

### ISSUE THREAD

**Issue by mr-utilman** [MiRO92/uYou-for-YouTube#224]
Hello
It still crashes after launch on iPhone 14 Pro Max with iOS 16.3 and updated AltStore 1.6

Would be nice if there is a solution soon!

thx

**Comment by DragonGaming88** [comment]
Same here.

**Comment by KidCale04** [comment]
Just downloaded the newest version and it crashed on my 14 pro max as well.

**Comment by KidCale04** [comment]
Crashes on iPhone 14 pro max 16.4 beta 1

**Comment by gabelaw** [comment]
Crashes on iPhone 14 pro max 16.3.1 on start

**Comment by mcolella89** [comment]
hi, just updated to latest version on IOS 16.4 beta 1 and can confirm that crashes on start

Previous version of ipa worked fine

**Comment by awsumbill** [comment]
Same here
