### ISSUE TITLE
latest version download?

### ISSUE THREAD

**Issue by csuka** [MiRO92/uYou-for-YouTube#227]
Where can we download the latest version as of now?
`2.3~1`?

I've tried the following URL's, no hits:

https://miro92.com/repo/depictions/com.miro.uyou/iPA/YouTube_17.49.6_uYou_2.3.ipa  
https://miro92.com/repo/depictions/com.miro.uyou/iPA/YouTube_17.49.6_uYou_2.3~1.ipa

**Comment by IkenHuub** [comment]
Why no answer?

**Comment by MiRO92** [comment]
v2.3~1 is a beta version that I released to fix some important crashes.

currently am still working on another update for uYou and once I finish it I'll release it here
