### ISSUE TITLE
[Feature Request] Disable Auto Captions

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#23]
YouTube's automatic subtitles are really annoying, and the worst part, they can't be disabled for the app.

The desktop version for browsers has a feature like that, but unfortunately it only gets applied to the browser.

Please add an option to disable auto captions for the YouTube app.

**Comment by MiRO92** [comment]
You already can disable captions from here ![image](https://user-images.githubusercontent.com/3205572/131878433-eeb359bc-9a80-4c91-ae5e-b266ae53e3b2.jpeg)

**Comment by theoccurrence** [comment]
I know, but that gets only saved for this video and only once. I have to disable the subtitles on every video manually.
