### ISSUE TITLE
It crashes.

### ISSUE THREAD

**Issue by uncrypt3d** [MiRO92/uYou-for-YouTube#233]
YouTube_16.42.3_uYou_2.1.ipa

**Comment by uncrypt3d** [comment]
and 2.3.1 too

**Comment by leo04real** [comment]
I just don't know why InstagramElite and YouTubeElite IPA don't work on my iPhone 12 Pro, iOS 15.1 Am I the only one having this problem? If yes, may I know how to resolve that? Thank you!

**Comment by khaiphan9x** [comment]
> YouTube_16.42.3_uYou_2.1.ipa

[Try this](https://terabox.com/s/1T5mUihyRF4FMz-40hD1LNA)
