### ISSUE TITLE
authorization is still not working

### ISSUE THREAD

**Issue by katr1nge** [MiRO92/uYou-for-YouTube#237]
![IMG_0252](https://user-images.githubusercontent.com/38489257/222208145-a55dba94-95cf-4f56-a239-842dc49e6419.png)
![IMG_0253](https://user-images.githubusercontent.com/38489257/222208155-58933701-9dfd-4144-8edc-71e42e2f5971.jpeg)

**Comment by khaiphan9x** [comment]
use widget

**Comment by yrmuq** [comment]
> use widget

what widget?

**Comment by bladeru99er** [comment]
> > @katr1nge Здравствуйте, вы решили эту проблему??
> 
> Добрий вечір не розумію російської

Привіт, радий що ви відповіли, Ви знайшли рішення проблеми??

Перекладав через перекладач, вибачте за помилки якщо вони є!

**Comment by yrmuq** [comment]
> > > > @katr1nge Здравствуйте, вы решили эту проблему??
> 
> > > 
> 
> > > 
> 
> > > Добрий вечір не розумію російської
> 
> > 
> 
> > Привіт, радий що ви відповіли, Ви знайшли рішення проблеми??
> 
> > 
> 
> > Перекладав через перекладач, вибачте за помилки якщо вони є!
> 
> 
> 
> Не використовуй Scarlet та подібні. Для підписування використовуй або телеграм бот @ipawind_bot, або AltStore.

Эх, вообще не понятно, что ты здесь написал
Не понимаю я ваш казахский
