### ISSUE TITLE
Crashing at start in iphone 12 pro

### ISSUE THREAD

**Issue by KQNV** [MiRO92/uYou-for-YouTube#238]
When I try to open the app, it closes automatically, it doesn't even leave the email to log in.

The device is an Iphone 12 Pro with IOS 16.3.1

The original Youtube app works normally.

I attached a video of the error.

https://user-images.githubusercontent.com/121523048/222582066-1fef059d-c120-48b1-bc99-4121a798d40d.MP4

**Comment by widyasanjaya** [comment]
How to install bro ?

**Comment by KQNV** [comment]
> How to install bro ?

I install it using alt store 
You can look for some tutorials in youtube, there´s a ton of them 👍

**Comment by widyasanjaya** [comment]
How to install not using pc

**Comment by khaiphan9x** [comment]
> error.

Try with Youtube v18.08.1 and Dylib v2.1

**Comment by khaiphan9x** [comment]
> 

[Download this](https://terabox.com/s/1T5mUihyRF4FMz-40hD1LNA)
