### ISSUE TITLE
[Feature Request] Saving images/gifs from creators' community posts

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#24]
Creators sometimes posts images or gifs as community posts, looking like this:

![image](https://user-images.githubusercontent.com/16444679/131811975-328d9ba2-ded0-468a-ae1c-08a6fb179868.jpeg)

It would be great to have an option to save these media to the camera roll, especially for gifs.

**Comment by MiRO92** [comment]
Done! Long pressing on the image will ask you to save the image! ![image](https://user-images.githubusercontent.com/3205572/131873737-a384b0ae-52d3-4cce-81b9-1ee4abd1eea5.jpeg)

**Comment by theoccurrence** [comment]
Great work as always 👍
