### ISSUE TITLE
[Bug] Crash on iOS 16.1.2

### ISSUE THREAD

**Issue by CatAnonymous** [MiRO92/uYou-for-YouTube#242]
Device info

* iOS/iPadOS version: 16.1.2
* Device model: XR
* Sideload tool: BullfrogAssistant, ESign
* The specific version of uYouPlus: 18.08.1-2.3~1

Describe the bug

- Can not open app

Steps to reproduce the issue

1. Sideload youtube v18.08.1 with v2.3~1 dylib
Install successfully
2.  Crash immediately when opening the app
3. Try with v18.08.1-2.1
4. Its working

**Comment by MINXYdug** [comment]
i have same issue how do i fix
