### ISSUE TITLE
can not refresh the app in AltStore

### ISSUE THREAD

**Issue by riddlejon** [MiRO92/uYou-for-YouTube#245]
I'm trying to refresh it, but it says "there is no provisioning profile with the requested identifier on this team"  can someone help me

**Comment by yTallBalls** [comment]
Known issue with Apple and Altstore.io. Fix coming soon!

https://twitter.com/altstoreio/status/1638237156777816071

**Comment by MiRO92** [comment]
am sorry but i don't give support for sideload services
