### ISSUE TITLE
[Bug] Downloaded videos not in the right order

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#25]
I found a small bug in the video sorting algorithm. It seems to ignore the difference between AM and PM. For example videos downloaded at 11 AM will be shown as newer than videos downloaded at 3 PM on the same day, I assume because 11 gets interpreted as later than 3.

![image](https://user-images.githubusercontent.com/16444679/131813396-011a71b0-df13-4e20-aab0-a6bc4e6faac1.jpeg)

Maybe this has something to do with me being in a region, that doesn't use AM and PM, but the 24h format instead.

**Comment by MiRO92** [comment]
Fixed!

**Comment by theoccurrence** [comment]
Awesome 👏
