### ISSUE TITLE
14 pro max crashes uYou 3.0

### ISSUE THREAD

**Issue by FzzyLizzy** [MiRO92/uYou-for-YouTube#251]
iOS 16.4.1 (20E252)

app closes immediately after opening

**Comment by PlexusGH** [comment]
Having same issue with iPhone 14 Pro Max on iOS 16.1

**Comment by dizzafizza** [comment]
having same issue too on iphone 12, ios 16.4

**Comment by akot69** [comment]
I have iPhone 11 on newest version same problem

**Comment by Zmmen** [comment]
> 

me too

**Comment by youngshxy** [comment]
found a fix: 
locate the folder where you have downloaded files from uyou before and delete them (or copy them and save them somewhere else if you want)
then reinstall the app without uninstalling the updated uyou and it should work

**Comment by sicole1804** [comment]
> found a fix:
> locate the folder where you have downloaded files from uyou before and delete them (or copy them and save them somewhere else if you want)
> then reinstall the app without uninstalling the updated uyou and it should work

This won’t work for me as I came from uYou+
I did however remove uYou+ from my iPhone before sideloading and removed the downloaded copy of it too but still crashes

**Comment by sicole1804** [comment]
> iOS 16.4.1 (20E252)
> 
> app closes immediately after opening

I recently saw on the closed issues thread that uYou isn’t compatible with iOS 16.. 

Hoping that’s addressed real soon

**Comment by mirifem** [comment]
iOS 16.3 iPhone 11
Error log
~~~~~~~~~~~~~~~~~~
Failed to load Info.plist from bundle at path /private/var/containers/Bundle/Application/B91F2AD8-745E-4CA6-AEDE-558C45793B0E/App.app/PlugIns/MessagesExtension.appex; Extra info about "/private/var/containers/Bundle/Application/B91F2AD8-745E-4CA6-AEDE-558C45793B0E/App.app/PlugIns/MessagesExtension.appex/Info.plist": Couldn't stat /private/var/containers/Bundle/Application/B91F2AD8-745E-4CA6-AEDE-558C45793B0E/App.app/PlugIns/MessagesExtension.appex/Info.plist: No such file or directory

**Comment by solomrdolo** [comment]
Same issue here

**Comment by birdfly** [comment]
same here on iOS 16.5 beta

**Comment by MarcoCornacchiaTanga** [comment]
same issue here on iPhone 11 iOS 16.4.1

**Comment by theRiggg** [comment]
> > iOS 16.4.1 (20E252)
> 
> > 
> 
> > app closes immediately after opening
> 
> 
> 
> I recently saw on the closed issues thread that uYou isn’t compatible with iOS 16.. 
> 
> 
> 
> Hoping that’s addressed real soon

I am on ios16.4.1 on iphone 14 promax and you ou is working fine. Not the latest version tho. im on 2.3.1
