### ISSUE TITLE
IPA shows up as .ipa.zip when downloaded and there is no way to have it open by TrollStore

### ISSUE THREAD

**Issue by Rex-91** [MiRO92/uYou-for-YouTube#253]
Hi,
I am on iOS 15.3
When i try to download the IPA it gets read as a zip file in the file manager and there is absolutely no way of changing that I tried, i have the previous version of uYou and this issue was not present then.
Is there anything i can do?

Cheers

**Comment by Rex-91** [comment]
Issue resolved by using the third party free app FileMaster to remove the .zip portion from the filename
https://apps.apple.com/us/app/filemaster-privacy-protection/id582219355

Still, would be good to find a solution that did not involve using an app.

Cheers

**Comment by ZJPat** [comment]
You can copy the link directly to TrollStore and that would download and install the IPA. 


the issue is it crashing non stop if you try to edit anything
