### ISSUE TITLE
[bug] new version crashes often when opened

### ISSUE THREAD

**Issue by Pogchamp2000** [MiRO92/uYou-for-YouTube#255]
My device iPhone XR is 16.1.2

**Comment by dhawan1997** [comment]
Same issue when signing using e-sign

**Comment by Yit83** [comment]
Same here :(

**Comment by ckaptann** [comment]
My device is Ipad Air 5th Gen. I can download app but i can not sign-in because app always crush.

**Comment by theallen77** [comment]
same, ipad 8th gen 16.1

**Comment by HahhVwgwg** [comment]
Same here Iphone 13 iOS 16

**Comment by ErikTellas** [comment]
Same problem here. Iphone 11, ios 16.1.2. I haven't even been able to open it once.

**Comment by theRiggg** [comment]
Same here on ipadpro
