### ISSUE TITLE
[Bug] Hide buttons under video player not working for some buttons

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#26]
The feature to hide buttons under the video player seems to not work for some buttons.

It doesn't work for the "save", "share" and "create short" buttons. No matter what I do, these buttons will always get shown to me. Even disabling every single button (which normally should crash the app) gives me the following results:

![image](https://user-images.githubusercontent.com/16444679/131815244-1c96ff4c-4ac5-403f-81b7-a894675f6a0d.jpeg)

![image](https://user-images.githubusercontent.com/16444679/131815264-57a21236-91fc-452c-a5d2-809bca957dc0.jpeg)

**Comment by sevenpastzeero** [comment]
Same for me. Both the Live Chat and the Create buttons still appear.
Example for a video where the Create button still appear: https://youtu.be/OiFyXdUkcpk
This one still shows Live Chat button: https://youtu.be/UXiwRmlCZ7E
Here are my settings: 
![IMG_6987](https://user-images.githubusercontent.com/34801304/132333231-25d580fc-5b1b-485f-bbf4-b28ae6d58d75.PNG)

**Comment by MiRO92** [comment]
I've re-wrote the hiding code from scratch, now it should works flawlessly
