### ISSUE TITLE
[Bug] no uYou button on playlists in new YouTube ui

### ISSUE THREAD

**Issue by reticivis-net** [MiRO92/uYou-for-YouTube#262]
![IMG_7595](https://user-images.githubusercontent.com/35177464/234467202-942aab5a-243b-47de-8f08-57c0067dca91.png)
![IMG_7596](https://user-images.githubusercontent.com/35177464/234467209-96b4ef95-a3e0-4775-8a53-73a1f354566f.png)
![IMG_7597](https://user-images.githubusercontent.com/35177464/234467216-e95083d9-a993-4b95-9e0e-db45f35dc180.png)
![IMG_0942](https://user-images.githubusercontent.com/35177464/234468410-32f85d63-e129-4a20-8085-daf9535a46c0.png)
![IMG_0943](https://user-images.githubusercontent.com/35177464/234468427-28c7ef9f-91c6-4839-8198-3b63be885c44.png)

using uYouPlus 18.15.1_3.0, uYou 3.0, YouTube 18.15.1
Bug reproducible on iPad Pro (11-inch) (2nd generation) with iPadOS 16.5 (20F5039e) and iPhone 14 Pro with iOS 16.5 (20F5039e)

**Comment by lts20050703** [comment]
Can reproduce

**Comment by lts20050703** [comment]
Is there any update on this?
