### ISSUE TITLE
ADS in version 3.0

### ISSUE THREAD

**Issue by helixxger** [MiRO92/uYou-for-YouTube#264]
iOS 16.4 | I got ads when watching a video. 

![image](https://user-images.githubusercontent.com/76208371/234782328-096082fd-4876-4eac-b466-fd014ea07149.png)

**Comment by lupus0802** [comment]
That's interesting, I can't reproduce the issue, can you try re-sideloading/-installing the app and/or checking if the ad block switch is actually activated?

**Comment by helixxger** [comment]
> That's interesting, I can't reproduce the issue, can you try re-sideloading/-installing the app and/or checking if the ad block switch is actually activated?

Seems like the update on version 2 caused that "Remove YouTube ads" switch got turned off
