### ISSUE TITLE
Pending downloads cause the app to break / don't resume

### ISSUE THREAD

**Issue by lupus0802** [MiRO92/uYou-for-YouTube#266]
uYou Version: 3.0

When having a pending download upon startup of the app, the app simply times out, appearently because it doesn't know how to handle the pending download. Upon checking the log on a Mac I was able to see that the app made some requests which returned the error `YouTube	Task <C9BA4E24-BCF4-40EC-9756-E68AE38D5219>.<1> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 UserInfo={_NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>, _NSURLErrorFailingURLSessionTaskErrorKey=<private>}` - I assume that this is uYou trying to resume the download. Another approach might be that the downloaded blob/part is malformed thus uYou not being able to handle it.

I had this problem myself and had to open the sqlite file and remove the row regarding the download in the downloading table for the app to start properly. 

Another thing I noticed is that upon backgrounding the app for a few seconds, the download immediately stops and fails with error code 403 (if I recall the code correctly). When telling uYou to retry the download, it does show the previous downloading state with percentage downloaded, however, no new data is downloaded. This might be related to the app breaking when there's a pending download upon startup.

**Comment by HexCodeFFF** [comment]
Can repro
iPad Pro (11-inch) (2nd generation)
iPadOS 16.5 (20F5059a)
uYou 3.0
uYouPlus [v18.14.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.14.1-3.0)

**Comment by MiRO92** [comment]
fixed
