### ISSUE TITLE
YouTube v18.17.2 crashes

### ISSUE THREAD

**Issue by leandroprz** [MiRO92/uYou-for-YouTube#268]
Hi,

I just updated YouTube to the last version and it crashes because of uYou according to Cr4shed.

Here's the crash log:

[Note 2023-04-30 21-09-59.txt](https://github.com/MiRO92/uYou-for-YouTube/files/11375991/Note.2023-04-30.21-09-59.txt)

**Comment by cemerson** [comment]
I'm guessing this info isn't needed but in addition to adding my own +1 to this issue just FYI I tried all the following older version of YouTube (via AppStore++) and they all crash when uYou 3 is enabled as well:

* 18.16.2
* 18.15.1 --> * 18.1.2
* 17.10.2  
* 16.45.x

**Comment by kasteckis** [comment]
`YouTube_18.14.1_uYou_3.0.ipa`

Closes like 1 second after opening.

**Comment by cemerson** [comment]
This may not be necessary to mention but in case anyone else in same/similar boat I installed this IPA via Trollstore and now I have YouTube + uYou back again. Realize it's old but least it works: 

https://miro92.com/repo/depictions/com.miro.uyou/iPA/YouTube_16.42.3_uYou_2.1.ipa

**Comment by MiRO92** [comment]
fixed
