### ISSUE TITLE
YouTube stopped working after killing uYou while downloading

### ISSUE THREAD

**Issue by dora727** [MiRO92/uYou-for-YouTube#269]
title.
when opening youtube again after killing youtube, it stucked at the logo, and you will have to uninstall and install again!

**Comment by HexCodeFFF** [comment]
Can repro
iPad Pro (11-inch) (2nd generation)
iPadOS 16.5 (20F5059a)
uYou 3.0
uYouPlus [v18.14.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.14.1-3.0)

**Comment by MiRO92** [comment]
fixed
