### ISSUE TITLE
[Feature Request] Option to deactivate **automatic** subtitles for Videos, that are not in the same language, as the system

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#27]
I made a very similar suggestion yesterday, but it seems I wasn't clear enough, I'm sorry.

YouTube has this very annoying habit of **automatically** enabling subtitles **every single time** I start a video (if english subtitles are available), even for *the same videos* I already disabled subtitles for.

When I deactivate subtitles for the video (as you suggested yesterday) it only works for *this one* video, and only for *one time*.

I recorded my screen to show this behavior to you:

https://user-images.githubusercontent.com/16444679/131990852-ee17325d-c328-4ed6-b9a7-3275a46f23fc.MOV

I hope what I meant is understandable now. An option to deactivate these automatic subtitles would be great, it's one of the last things that drive me crazy.

**UPDATE:**

Changing the system language to english (which is not optimal for me) fixed the problem **for english videos only**.

Now German videos get automatic subtitles. I didn't get automatic subtitles on German videos before, probably because my system language has been set to German.

I can conclude that subtitles, as far as they exist, are automatically enabled for videos, that are in a different language than your system.

You can encounter this behavior with this German video: https://youtu.be/M2PYkZ2Y_Ls

**Comment by qnblackcat** [comment]
Did it happen with the original YouTube?

**Comment by theoccurrence** [comment]
> Did it happen with the original YouTube? 

Yes, it happens with regular untweaked YouTube as well. It has been a problem for a while (https://www.reddit.com/r/youtube/comments/5i0bg8/disable_closed_captions/) but YouTube still doesn't provide a way to turn auto captions off.

The desktop browser version of YouTube has an option in Settings > Playback and performance to turn "Always show captions" off, but unfortunately that's only for that specific browser, and doesn't change anything in the app.

I also tried to change my region in the YouTube settings to "USA", but that doesn't help.

**Comment by theoccurrence** [comment]
Update: setting the system language to English fixed the problem **for english videos** only.

This is a fix for a big part of the content I consume on YouTube, but now I get automatic subtitles on other channels, where I didn't get automatic subtitles before. Also I would prefer if the system language was my in my mother language ...

Anyways, this seems to be connected to the system language setting.
With english system language you can probably encounter this behavior in this video: https://youtu.be/M2PYkZ2Y_Ls

**Comment by MiRO92** [comment]
Done! :) please wait for v1.8 which will be released soon

**Comment by theoccurrence** [comment]
Whoa, amazing!
