### ISSUE TITLE
iOS 16.4.1 (Iphone XS)

### ISSUE THREAD

**Issue by minhnhat2904** [MiRO92/uYou-for-YouTube#270]
App closes immediately after opening

**Comment by NICKNAME5166** [comment]
Same for me, iPhone X IOS 16.4.1

**Comment by WJSWebster** [comment]
Same here

**Comment by NICKNAME5166** [comment]
You can still access youtube app, when long holding icon, and choosing shorts

**Comment by AngeloAndreaIsola** [comment]
Same here

**Comment by spedor123** [comment]
same here with XS

**Comment by MiRO92** [comment]
fixed
