### ISSUE TITLE
PIP is not working

### ISSUE THREAD

**Issue by diegogarciaarriaza** [MiRO92/uYou-for-YouTube#273]
From update to v3 at change the app now you only can listen the audio of YouTube but not the video

Dopamine 1.0.4,
iPhone 12,
iOS 15.3.1

Thnaks

**Comment by Stanlyv** [comment]
The same issue for me. I used 16x version of uYou and everything was fine but after update it to 18x I can only listen audio but not pip video.

iPhone 13
iOS 15.7
Installed by Altstore

**Comment by ch-gz** [comment]
some issue with 18.29.1, previous version was fine.

Iphone x
IOS16.5.1(c)
installed by AltStore

**Comment by Bumbalaaa** [comment]
Same issue, PiP button doesn’t work and doesn’t auto pip when exiting app.

iPhone 13 Pro
iOS 16.0
Installed via AltStore

**Comment by dp-engineering** [comment]
Same problem here, Updated to version 18.29.1 now PiP doesn't appear. Last version 18.14.1. worked fine.

iPhone 11 Pro
iOS 16.5
Installed via Sideloaded iPA
