### ISSUE TITLE
YouTube crashing

### ISSUE THREAD

**Issue by DeltaOn3X** [MiRO92/uYou-for-YouTube#274]
Hello,

whenever im in the uYou settings under "YT Settings" and click on "Hide Tabs" or "Home" the app just crashes, i dont know how to generate a crash log since cr4shed does not work on dopamine afaik

Dopamine 1.0.5
iOS 15.1.1
iPhone 13 Pro Max
uYou 3.0
YouTube 18.19.1 (alos on older versions, i have this problem since the release of uYou 3.0)

If you need any more infos i can provide please let me know! 

Thank you very much

**Comment by cbtham** [comment]
FIX: Use youtube 18.14.1
Appstore++ to downgrade

**Comment by DeltaOn3X** [comment]
It also crashes with version 18.14.1 :/

**Comment by doggy** [comment]
Dopamine 1.0.5
iOS 15.1.1
iPhone 13 Pro Max
uYou 3.0
Youtube 18.14.1 (Appstore++ downgrade)

Same crash on uYou Setting menu...

Just curious why uYouPlus v18.14.1-3.0 works properly, no any clue

https://github.com/qnblackcat/uYouPlus/releases/tag/v18.14.1-3.0

**Comment by DeltaOn3X** [comment]
Yes i can confirm @doggy,

when i downgrade the appstore version to 18.14.1 and use uYou 3.0 installed trough Sileo it crashes, when i install the sideload version 18.14.1-3.0 it works fine.

Very weird

**Comment by doggy** [comment]
> Yes i can confirm @doggy,
> 
> when i downgrade the appstore version to 18.14.1 and use uYou 3.0 installed trough Sileo it crashes, when i install the sideload version 18.14.1-3.0 it works fine.
> 
> iPhone 13 Pro Max iOS 15.1.1
> 
> What weird is, is that its working fine on iOS 14 (iPhone 8 Plus) with the latest version of youtube and uYou 3.0.

Lol, I will test on my device with "sideload version + Sileo uYou3.0" then post the result later.

Where did you download the working version of sideload ipa?

**Comment by DeltaOn3X** [comment]
> > Yes i can confirm @doggy,
> > when i downgrade the appstore version to 18.14.1 and use uYou 3.0 installed trough Sileo it crashes, when i install the sideload version 18.14.1-3.0 it works fine.
> > iPhone 13 Pro Max iOS 15.1.1
> > What weird is, is that its working fine on iOS 14 (iPhone 8 Plus) with the latest version of youtube and uYou 3.0.
> 
> Lol, I will test on my device with "sideload version + Sileo uYou3.0" then post the result later.
> 
> Where did you download the working version of sideload ipa?

With the Sideload version i mean the version you posted above my last reply

https://github.com/qnblackcat/uYouPlus/releases/tag/v18.14.1-3.0

This is the Sideload version that works

**Comment by DeltaOn3X** [comment]
Any fix for this ? :)

**Comment by DeltaOn3X** [comment]
Updated uYou to 3.0.1 and it still crashes :/
