### ISSUE TITLE
Install issue with AltStore

### ISSUE THREAD

**Issue by ffernn-dev** [MiRO92/uYou-for-YouTube#276]
Hey I'm getting some sort of error indicating that maybe a plots file is missing in the messages extension? Trying to install the latest ver of uyou through AltStore on an iPhone 8.

`Failed to load Info.plist from bundle at path /private/var/containers/Bundle/Application/CD07273D-692D-4D5F-AE00-19C814FBB147/App.app/PlugIns/MessagesExtension.appex; Extra info about "/private/var/containers/Bundle/Application/CD07273D-692D-4D5F-AE00-19C814FBB147/App.app/PlugIns/MessagesExtension.appex/Info.plist": Couldn't stat /private/var/containers/Bundle/Application/CD07273D-692D-4D5F-AE00-19C814FBB147/App.app/PlugIns/MessagesExtension.appex/Info.plist: No such file or directory`

**Comment by ielgnaw** [comment]
same error in iphone 14

**Comment by theoccurrence** [comment]
Might be the same reason as for the staging issues uYouPlus causes with AltStore and SideStore, the dirtily removed app extensions.

**Comment by therealFoxster** [comment]
It's likely an issue with the original YouTube IPA that was used to inject tweaks into. Try [my build of uYouPlus](https://therealfoxster.github.io/altsource-viewer/app.html?source=https://therealfoxster.github.io/altsource/apps.json&id=com.google.ios.youtube).
