### ISSUE TITLE
When he tries to turn on uyoutube it turns off right away

### ISSUE THREAD

**Issue by Wladziuu** [MiRO92/uYou-for-YouTube#286]
No working on 16.6 iOS, When he tries to turn on uyoutube it turns off right away

**Comment by prodigy-k** [comment]
may i know how you installed your uyou?...because i found a solution for sideloading jailbreak rootless and..on here they show you how to fix it using userscript app

**Comment by Wladziuu** [comment]
hi, via altstora

W dniu pon., 3.07.2023 o 14:53 prodigy-k ***@***.***>
napisał(a):
