### ISSUE TITLE
Stretched album art in uYou's player view

### ISSUE THREAD

**Issue by therealFoxster** [MiRO92/uYou-for-YouTube#287]
Hey! I hope you're doing well. I noticed that the album art was stretched in uYou's player view and implemented a fix for it in [uYouPlus](https://github.com/qnblackcat/uYouPlus/commit/a12b359ad78f99de231dff1fff9dc6489574002e). All I did was set the image view's content mode to `UIViewContentModeScaleAspectFit`. I also tried to make the album art a bit bigger so it's more inline with the elements beneath it. Let me know what you think!

Before |  After
-|-
![IMG_3241](https://github.com/MiRO92/uYou-for-YouTube/assets/77606385/036439ad-77d1-448e-927d-67d320ffe0a8) | ![IMG_3253](https://github.com/MiRO92/uYou-for-YouTube/assets/77606385/f2f22a21-314c-42ba-a19c-8d9f0dd72e9c)

**Comment by MiRO92** [comment]
fixed, thanks a lot for your help
