### ISSUE TITLE
[bug] YT Video Quality option doesn’t do anything

### ISSUE THREAD

**Issue by Nixuge** [MiRO92/uYou-for-YouTube#29]
The option works on cercube but not on uyou.  
YouTube 16.34.7, uYou 1.6.1

**Comment by Macleykun** [comment]
In uYou going to YT Video Quality on WiFi seems to work when I change it from auto to 144p, without a relaunch the next vid started in 144p.
Same when choosing 1080p.

**Comment by MiRO92** [comment]
fixed
