### ISSUE TITLE
Crash at startup. YT 18.14.1 uYou 3.0 iPadOS 16.5.1

### ISSUE THREAD

**Issue by eugener63** [MiRO92/uYou-for-YouTube#294]
Just installed it on old iPad A1701 using AltStore with removing extensions option. 
I attached a logfile from iPad.
[YouTube-2023-06-28-161956.log](https://github.com/MiRO92/uYou-for-YouTube/files/11900702/YouTube-2023-06-28-161956.log)

**Comment by trK54Ylmz** [comment]
happened to me also, installing uYouPlus from qnblackcat did the work,

https://github.com/qnblackcat/uYouPlus/releases/tag/v18.14.1-3.0

**Comment by MiRO92** [comment]
fixed
