### ISSUE TITLE
Can’t install problem

### ISSUE THREAD

**Issue by Bob4n** [MiRO92/uYou-for-YouTube#3]
Hi
I have a problem when I unzip the file it's as "app" and not as "ipa" extension.. 
I'm I doing something false?
Best regards

**Comment by MiRO92** [comment]
I've updated the link and changed it to ZIP, now it will be downloaded as a ZIP then you have to extract the IPA from the ZIP file.

**Comment by Bob4n** [comment]
Ok thank you 👍
