### ISSUE TITLE
[Bug] Saved gifs from community posts are saved in the webp format instead

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#30]
I don't know wether iOS has no support for animated webp images, or if it's a problem with iOS 15 beta 8, but saved gifs appear as non-animated images in the photo app. After converting the saved webp image to a gif with an external tool, it is shown animated as expected.

**Comment by Macleykun** [comment]
Have you tried downloading an animated webp to your camera roll from google?
