### ISSUE TITLE
Still Crashing

### ISSUE THREAD

**Issue by CauAsak23** [MiRO92/uYou-for-YouTube#301]
just report that the latest version still has crash problem when selecting options in YT Settings section, even the sideloaded version (TrollStore) can't be used at all.
now I'm back to using uYou+ via TrollStore and it's working fine.

A9
ios 15.1 Palera1n Rootful Mode

Edit : can be confirmed for the latest ipa it can be opened but it still crashes when opening the YT Settings menu, and uYou runs normally when I try it on ios 15.4.1.
maybe uYou only crashes on earlier versions of ios 15?

**Comment by ham0de** [comment]
The same here with 13 pro 15.2 trollstore

**Comment by datphanmem** [comment]
The same here iphone 12 pro max 16.5.1

**Comment by nhanyca** [comment]
Same here with 11 Pro Max 14.4
Also Youtube gonna show black , no content after browsing for a while.
