### ISSUE TITLE
Error installing on AltStore with iOS 16.5.1

### ISSUE THREAD

**Issue by futurepr0n** [MiRO92/uYou-for-YouTube#302]
![image](https://github.com/MiRO92/uYou-for-YouTube/assets/478986/89e67a62-1aa8-4f4a-9a18-f0f0c801004f)
I was recently trying to refresh the app after updating AltStore to 1.6.3 and then received this error.

I tried some different versions of uYou but all seemed to have problems. Waiting on App ID's to expire before I can try the latest version, but wondered if it might be related to anything else like iOS 16.5.1

**Comment by augustobob** [comment]
Well, this new version doesn't works sideloaded, I tried sideloadly (Apple id) and esign (developer certificate). Though I extracted the Dylib and it worked fine  on previous yt app version

**Comment by futurepr0n** [comment]
Interesting! I didn’t end up doing anything like that but good to know of other strategies to attack this if it happens again. I ended up waiting out the app entries until expired and tried alt store with the latest uyou and that version worked. Only thing is I don’t think the pop up/out player is in this version but it at least still does audio in the background which is huge. Very appreciative of Miro and whoever else is helping this project. Thank you.
