### ISSUE TITLE
uYou v3.0.1crash on ios 16.6 installed with alterserver 1.6.1.0

### ISSUE THREAD

**Issue by laozhang123456** [MiRO92/uYou-for-YouTube#303]
v3.0.1 can be insalled to ios 16.6 with aterserver 1.6.1.0 in windows, but crash as open the App, while v3.0 run perfectly.

**Comment by kkula9999** [comment]
ios 17 also
with sideloadly (mac)

**Comment by cbtham** [comment]
To fix crash, at least for me, it's more of a version mismatch. 

For Jailbreakable phone:
For folks come from uyou 3.0.1, uninstall the tweak, upgrade your youtube app to 18.29.1. Then install the latest 3.1 tweak. Youtube will function like normal.

Non JB:
Try to get youtube 18.29.1 ipa, then manually inject the 3.1 deb while sideloading

**Comment by augustobob** [comment]
I did successfully injected into 18.27.3 and added youpip and ytuhd. Youquality and ytclassicvideoquality seems to conflict in the latest youtube version

**Comment by ThenMeN0** [comment]
> To fix crash, at least for me, it's more of a version mismatch.
> 
> For Jailbreakable phone: For folks come from uyou 3.0.1, uninstall the tweak, upgrade your youtube app to 18.29.1. Then install the latest 3.1 tweak. Youtube will function like normal.
> 
> Non JB: Try to get youtube 18.29.1 ipa, then manually inject the 3.1 deb while sideloading

Where to get official YouTube ipa?

**Comment by cbtham** [comment]
Just search online for decrypted ipa if you want to do it yourself. 

Since this repo is defunct, look for miro92's repo. there's a link there with uyou ipa that works.
