### ISSUE TITLE
google can't guarantee this is safe

### ISSUE THREAD

**Issue by hassan-waris** [MiRO92/uYou-for-YouTube#304]
I tried to sign in and I keep getting this error, google can't guarantee this is safe, how do I get around this since you plus is no longer around??

**Comment by rctfan929** [comment]
@arichorn can you provide a pre built ipa on your github?

**Comment by hassan-waris** [comment]
@arichorn thank you so much

**Comment by lilxluuc** [comment]
I found a fix for that. Download and install version 3.0.0 log in to your account than delete version 3.0.0 and install version 3.0.1 you will keep logged in.
