### ISSUE TITLE
Hiding uYou Tab Problem [uYou 3.0.1 Bug]

### ISSUE THREAD

**Issue by arichornlover** [MiRO92/uYou-for-YouTube#309]
Hey @MiRO92 There’s this weird issue that’s been going on only in uYou 3.0.1, whenever I start hiding the uYou tab and then attempt to reposition the Library or Subscriptions Tab to the left side of the YouTube App’s Pivot Bar.
and then if you try to attempt to even open the Subscriptions or Library Tab then you will not see anything but a blank screen like for example below 👇 
![IMG_2288](https://github.com/MiRO92/uYou-for-YouTube/assets/78001398/a061577d-c414-4881-9dcb-25b6bbe56614)

**Comment by MiRO92** [comment]
I just tested it and it works fine for me on uYou 3.0.2
