### ISSUE TITLE
A way to import Cercube's downloaded audios/videos

### ISSUE THREAD

**Issue by sevenpastzeero** [MiRO92/uYou-for-YouTube#31]
Is there a way - even if it is a manual way - to import Cercube's downloaded a/v into uYou?
I have a lot of downloaded a/v and it is a bit of a hassle to go write their names and get them all again.
Maybe a way to rename the files like the uYou naming scheme and a way to generate that plist file that accompanies the audio/video file.

**Comment by theoccurrence** [comment]
Without a Jailbreak this seems rather implausible, as long as Miro doesn't offer some kind of importing feature.

Multiple instances of YouTube should (at least in theory) be capable to share data with each other in the sandbox.

**Comment by MiRO92** [comment]
I just quickly checked and saw that it is possible, I will work on this later today.

**Comment by MiRO92** [comment]
I've added this feature in uYou v.1.8 (it's still not released yet)
