### ISSUE TITLE
Stops working if you start downloading a video and close the app fully

### ISSUE THREAD

**Issue by Cabbasca** [MiRO92/uYou-for-YouTube#310]
The app stops working if you start downloading a video and close the app fully.
You get stuck on the loading screen and it crashes after a while

**Comment by bex666** [comment]
I have the same issue

**Comment by Prabh-Saini** [comment]
Further: when the internet changes (eg wifi -> data), it also stops downloading

**Comment by Cabbasca** [comment]
@MiRO92 fix

**Comment by Cabbasca** [comment]
> There’s also another issue related to uYou’s downloading. if you download a thumbnail and save it to camera roll it will crash

have you fixed this thing in your fork?

**Comment by MiRO92** [comment]
I have fixed it, please wait for the next uYou update.
