### ISSUE TITLE
NOT ABLE TO SIGN IN. (YouTube - com.google.ios.youtube - 18.29.1 - 3.0.1 - IPA)

### ISSUE THREAD

**Issue by iSquaard** [MiRO92/uYou-for-YouTube#312]
- Downloaded the mentioned version, YouTube | com.google.ios.youtube | 18.29.1 | 3.0.1 | IPA
- Sideloaded via Sideloadly,
- Installed, but not able to add google account (due to bundle ID as (com.miro.uyou), instead original (com.google.ios.youtube).

**_KINDLY CHANGE THE BUNDLE ID TO (com.google.ios.youtube) EASE THE SIGNING IN._**

**Comment by iSquaard** [comment]
Hello @MiRO92 , Kindly look into this and update. I need to sign-in.

I don't want to use other tweaks (which allows sign-in effortlessly), since I find yours to be lightweight.

**Comment by lilxluuc** [comment]
I Found a fix for that. Download and install Verion 3.0.0 log in to your account than delete version 3.0.0 and install version 3.0.1 and you will keep logged in.

**Comment by christopherhomen** [comment]
I'm not able to sign in, In none of the versions

**Comment by charleshu32** [comment]
> * 下載上述版本，YouTube | com.google.ios.youtube | 18.29.1 | 3.0.1 | 異丙醇
> * 透過 Sideloadly 進行側載，
> * 已安裝，但無法新增 google 帳號（由於捆綁 ID 為 (com.miro.uyou)，而不是原始 (com.google.ios.youtube)。
> 
> **_請變更捆綁 ID (com.google.ios.youtube) 以便輕鬆登入。_**

not work

**Comment by charleshu32** [comment]
> 我找到了解決方法。下載並安裝版本 3.0.0 登入您的帳戶，然後刪除版本 3.0.0 並安裝版本 3.0.1，您將保持登入狀態。

not work
