### ISSUE TITLE
"Hide Shorts Cells" setting also breaks shorts cells in History

### ISSUE THREAD

**Issue by thonkinator** [MiRO92/uYou-for-YouTube#318]
If you enable uYou Settings > Home > Hide Shorts Cells, it will also break the shorts cells in History. So if you go to the Libray tab and hit "View All", then tap on one of the shorts cells shown at the top, it will take you there, but if you go back all of the shorts cells have been removed and replaced with a white rectangle.

**Comment by zxdposter** [comment]
me too
