### ISSUE TITLE
[Important Question] Fullscreen in Potrait mode?

### ISSUE THREAD

**Issue by xFr0z3n** [MiRO92/uYou-for-YouTube#323]
Is there any option or could you add an option that portrait mode is in fullscreen like in the default YouTube site on safari ? See the link it’s an example https://www.reddit.com/r/jailbreak/comments/ig98yx/question_any_tweak_for_youtube_to_use_full_screen/?rdt=39700

**Comment by CySxL** [comment]
YTLite has that option.
