### ISSUE TITLE
Unable to log in to this application.

### ISSUE THREAD

**Issue by Schizophren1a** [MiRO92/uYou-for-YouTube#324]
Google has failed to confirm that it is safe. Anyone know how to fix this? I tried to enable non-safe applications in google, but it says 'This setting is not available in your account.'

**Comment by Hezkezl** [comment]
+1 for me too...

Just installed this thing via sideloadly, nothing I do will let me sign in. Old workarounds (like trying to copy the sign-in url to private mode Safari) don't work at all. Really disappointed that my first attempt at using this app has met a brick wall :\

**Comment by charleshu32** [comment]
I still can't log in with 3.0ipa. How can I solve it?
