### ISSUE TITLE
Feature request: option to disable chapter skip

### ISSUE THREAD

**Issue by danielskowronski** [MiRO92/uYou-for-YouTube#326]
Some time ago, YouTube added feature that you can’t disable - chapter skip with double finger double tap. 

It’d be wonderful to have the ability to disable it, as it’s pretty random in behaviour; often wanting to rewind just 5 seconds back to hear what you just missed makes the app rewind half hour back because the app thinks you used two fingers and there are no controls to revert recent rewind. 

Locking screen controls is not enough, as for me, this happens only when I want to rewind.

**Comment by MahVRO** [comment]
Yeah this is so annoying please add this feature

**Comment by fatetrait** [comment]
Is this feature in uYou now? I cannot find it in the settings on v3.0.4.
