### ISSUE TITLE
Stuff for uYou 3.0.2 [Useful Code to help uYou! - January 28th 2024]

### ISSUE THREAD

**Issue by arichornlover** [MiRO92/uYou-for-YouTube#327]
# UPDATED January 28th 2024

Hello @MiRO92 I have some more features or fixes that can be useful to uYou!
here’s the first one

----

The code below is something I have made. a tweak that only works with v17.xx.x or higher.
being able to hide the Remix, Thanks, Download, Clip & Save buttons under the video player.
however. I wasn’t fully smart enough with the implementation so whenever it hides the button, it will have gaps.
![GAPS](https://github.com/arichornlover/uYouEnhanced/assets/60850613/62b718e0-2989-464e-899b-f025d1070491)
```
// Hide the (Remix / Thanks / Download / Clip / Save) Buttons under the Video Player - 17.x.x and up - @arichorn
%hook _ASDisplayView
- (void)layoutSubviews {
    %orig;
    for (UIView *subview in self.subviews) {
        if ([subview.accessibilityIdentifier isEqualToString:@"id.video.remix.button"]) {
            subview.hidden = hideRemixButton;
        } else if ([subview.accessibilityLabel isEqualToString:@"Thanks"]) {
            subview.hidden = hideThanksButton; // key
        } else if ([subview.accessibilityIdentifier isEqualToString:@"id.ui.add_to.offline.button"]) {
            subview.hidden = hideAddToOfflineButton; // key
        } else if ([subview.accessibilityLabel isEqualToString:@"Clip"]) {
            subview.hidden = hideClipButton; // key
        } else if ([subview.accessibilityLabel isEqualToString:@"Save to playlist"]) {
            subview.hidden = hideSaveToPlaylistButton; // key
        }
    }
}
%end
```

----

This implementation is something that is Customizable in the Video Player Overlay.
Having the ability to remove the Button Background on all 5 of the Buttons in the video player. Play/Pause, Previous, Next, Rewind & Forward
```
%hook YTMainAppControlsOverlayView
- (void)layoutSubviews {
	%orig();
    MSHookIvar<YTTransportControlsButtonView *>(self, "_previousButtonView").backgroundColor = nil;
    MSHookIvar<YTTransportControlsButtonView *>(self, "_nextButtonView").backgroundColor = nil;
    MSHookIvar<YTTransportControlsButtonView *>(self, "_seekBackwardAccessibilityButtonView").backgroundColor = nil;
    MSHookIvar<YTTransportControlsButtonView *>(self, "_seekForwardAccessibilityButtonView").backgroundColor = nil;
    MSHookIvar<YTPlaybackButton *>(self, "_playPauseButton").backgroundColor = nil;
}
%end
```

----

the option `uYou Shorts > Always Show Progress Bar` is broken but it can be fixed for by adding the extra code below!
```
%hook YTShortsPlayerViewController
- (BOOL)shouldAlwaysEnablePlayerBar { return YES; }
- (BOOL)shouldEnablePlayerBarOnlyOnPause { return NO; }
%end
```

----

Here’s the next one as a new Option, and it’s hiding the YouTube Logo on the top left, not sure if that’s needed though.

```
%hook YTHeaderLogoController
- (YTHeaderLogoController *)init {
    return NULL;
}
%end
```

----

YouTube added a feature called Suggested Videos in the Video Player. @bhackel made this option to hide it. Good job to them! 😁

```
// YTNoSuggestedVideo - https://github.com/bhackel/YTNoSuggestedVideo
%hook YTMainAppVideoPlayerOverlayViewController
- (bool)shouldShowAutonavEndscreen {
        return false;
}
%end
```

----

This is an updated version of Hide Upgrade Dialog. It simply just removes any prompt to update to the latest version of the app. However this is a very important thing for uYou to prevent issues like https://github.com/MiRO92/uYou-for-YouTube/issues/358 from ever happening.

```
// Hide Upgrade Dialog (updated)
%hook YTGlobalConfig
- (BOOL)shouldBlockUpgradeDialog { return YES;}
- (BOOL)shouldForceUpgrade { return NO;}
- (BOOL)shouldShowUpgrade { return NO;}
- (BOOL)shouldShowUpgradeDialog { return NO;}
%end
```
however, if you don’t like this version you can use this version of the Hide Upgrade Dialog by **0xilis** below
https://github.com/0xilis/LetMePass/blob/main/dylib.c

----

<details>
<summary>other</summary>
There is stuff that I was unable to solve but you can check this out below if you want! 😁
https://github.com/arichornlover/uYouEnhanced/issues/73,
https://github.com/arichornlover/uYouEnhanced/issues/57,
https://github.com/arichornlover/uYouEnhanced/issues/311 <-- conflicts new YTSpeed update
</details>

**Comment by Sauce-cod3** [comment]
Great suggestions arichorn. Both Miro, yourself and all of the other contributors are helping to keep this amazing app alive.

**Comment by MiRO92** [comment]
Once again thanks a lot for your help @arichornlover
