### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by Takato2006** [MiRO92/uYou-for-YouTube#329]
Why can't we get push notifications from uyou+ ? How to fix it ?

**Comment by Sourav-Malani** [comment]
Same :<

**Comment by spinfal** [comment]
this isnt a bug with uyou or uyou+, it depends on what you sign the app with and how you sign it.
you cant use enterprise certs, and you need to use a distribution cert with explicit id

**Comment by Sourav-Malani** [comment]
I see. How do I know my certificate type though?

**Comment by CySxL** [comment]
> I see. How do I know my certificate type though?

You need to pay for Apple Developer account or buy personal certificate online.
