### ISSUE TITLE
iSponsorBlock is missing from the latest update?

### ISSUE THREAD

**Issue by SeveredHeadofMedusa** [MiRO92/uYou-for-YouTube#33]
Since I updated to v.1.7 it’s completely gone, anyone else experiencing this?

**Comment by theoccurrence** [comment]
Well, I bet you installed an IPA without iSponsorBlock then.

iSponsorBlock has nothing to do with the dev of uYou. 

If you want iSponsorBlock, YTUHD, youPiP, etc. then you need to install something like uYou+.

https://appdb.to/app/cydia/1900000830

I would bet money that you've had uYou+ installed before.
