### ISSUE TITLE
Cast not working

### ISSUE THREAD

**Issue by ste03** [MiRO92/uYou-for-YouTube#330]
Cast hasn’t worked for me since iOS 15, when choosing the cast button the only options that appear are Google devices on my network (home hub, chrome etc) no third party devices show up. 

I’ve tried this on several networks with different tvs and still the same issue, if I use the vanilla YouTube app all my devices are shown and are able to cast 

Thanks

**Comment by Kager539** [comment]
Same here

**Comment by fusionptb** [comment]
someone find a solution?
