### ISSUE TITLE
Downloading videos errors when exiting/refreshing

### ISSUE THREAD

**Issue by Sauce-cod3** [MiRO92/uYou-for-YouTube#335]
When downloading a video and you close YouTube, lock your iPhone or it goes to sleep, the download will provide the following error “Error: The network connect was lost - code - 1005”.

Resuming the download changes the status to downloading but doesn’t actually download.

Steps to reproduce the issue

1. Download a video
2. Close YouTube or lock the screen.
3. Download errors

**Comment by b007zk** [comment]
Yeah I have the same problem. Can never download videos because of this. Major issue imo. @MiRO92 Any idea when this will be fixed?

**Comment by MiRO92** [comment]
Fixed, will push an update soon
