### ISSUE TITLE
”Hide Shorts Cells” No Longer Working

### ISSUE THREAD

**Issue by Nonymaus** [MiRO92/uYou-for-YouTube#352]
It appears as if YouTube has made a change to the shorts cells that is preventing them from being blocked via the “Hide Shorts Cells” option. 

This was a recent change (past 3-4 days) and arose without an app update.

**Comment by zediaa** [comment]
yeah same, really hoping this gets fixed!

**Comment by eureka1111** [comment]
Hi @MiRO92, can you please look into this. I am willing to donate some money if this can get fixed, I am sure there are other people who are willing to do the same.

**Comment by eureka1111** [comment]
Hi @MiRO92, can you please look into this. I am willing to donate some money if this can get fixed, I am sure there are other people who are willing to do the same.

**Comment by Sawangg** [comment]
I've got the same issue on the latest version of the app. Would love if this could get fixed!

**Comment by Asmoson** [comment]
Still have this bug, also with something similar with youtube premium/music ads

**Comment by jug-3866** [comment]
I don't know if this will work for everyone but it worked for me. I opened the YouTube website and scrolled until there was a shorts cell. From there was a small x in the corner of a shorts cell and after I clicked the x it said that it would hide the cell for 30 days. I haven't seen the shorts cell on my phone since.

**Comment by PhakeJake** [comment]
I would also donate to help get this fixed. This is a huge quality of life downgrade for me. I’ve eliminated all shorts/reels/tiktok style videos from my phone as I get trapped in them, but want uYou on my phone for casting purposes. Alternatively, I’d love a way to just hid the home tab all together. I want to eliminate all curated feeds from my life.

**Comment by Blarnix** [comment]
Having this issue as well. I've also noticed when the tweak is enabled, it causes issues with the 'Your Videos' tab and playlists, either causing some UI bug or just not showing anything in them. Super aggravating.
Example: 
![image](https://github.com/MiRO92/uYou-for-YouTube/assets/61402697/ecdab030-f853-4bf0-a421-11834d308d66)

**Comment by zediaa** [comment]
try uYouPlusExtra. I don’t know if that’s why it works for me but that’s the version I ended up on and it is fine. Shorts have been blocked for me for a couples months just fine.
