### ISSUE TITLE
Unable to log in to Google account!!!

### ISSUE THREAD

**Issue by bladeru99er** [MiRO92/uYou-for-YouTube#353]
### **Unable to log in to Google account!!!**

**I tried to log in with uYou Login V2.2 (Shortcut) but its dont work anymore!!!**

I can Log in to Google account via Scarlet but cant through AltStore.  _(I would use it through scarlet, but his license is often revoked.)_

**I looked for solutions to this problem, did and tried everything, but nothing helped. Please tell me the solution to the problem if you know!**

![photo_2023-11-29_03-24-55](https://github.com/MiRO92/uYou-for-YouTube/assets/152336639/7bb14b85-f570-4477-86b2-9c4208086ec4)

**Comment by BvrDev** [comment]
🆙 up

**Comment by qiuzhaokun** [comment]
me too,  Is it resolved?

**Comment by FearedFusionX** [comment]
The newest version is throwing that error. Try a older version because that is working for me

**Comment by AdoptMeTradingValues** [comment]
> The newest version is throwing that error. Try a older version because that is working for me

What version are you using?

**Comment by bladeru99er** [comment]
> me too,  Is it resolved?

Solved, just use Sideloadly on your pc and enable tweak injection - Sideload spoofer
