### ISSUE TITLE
Does the uyou+ work?

### ISSUE THREAD

**Issue by Almigo21** [MiRO92/uYou-for-YouTube#355]
The app lately does not respond it just open stuck on the YouTube logo and crash is there anyone who has the same issue?

iPhone 13 iOS 17.1.1
Last version of uyou+
Using AltStore

**Comment by julienaub** [comment]
Same issue, using Altstore, unjailbroken iPhone 13 Mini on iOS 17.1.2

**Comment by Nexinity7** [comment]
> The app lately does not respond it just open stuck on the YouTube logo and crash is there anyone who has the same issue?
> 
> 
> 
> iPhone 13 iOS 17.1.1
> 
> Last version of uyou+
> 
> Using AltStore 

Did you try downloading anything and then closing the app? This locks the app and you must reinstall. Also i don't think it's worth trying to download anything as it always errors out
