### ISSUE TITLE
Fullscreen rotation direction toggle

### ISSUE THREAD

**Issue by oomek** [MiRO92/uYou-for-YouTube#36]
Would you consider adding an option in uYou that changes fullscreen rotation from right to left? I have my phone on a stand in vertical position, I lay down and watch in fullscreen but the image is upside down. There is a workaround with accessibility shortcuts, but it's very cumbersome. Thanks for yout great app.

**Comment by MiRO92** [comment]
Done!

**Comment by oomek** [comment]
You are awesome?

**Comment by oomek** [comment]
I guess this feature is going to be in the next release right? Can't find it in v2.0

**Comment by MiRO92** [comment]
> I guess this feature is going to be in the next release right? Can't find it in v2.0
Yes
