### ISSUE TITLE
Can’t sign in. Installed using Trollstore 2.

### ISSUE THREAD

**Issue by hohoho123456** [MiRO92/uYou-for-YouTube#360]
I installed uYou via Trollstore 2 on my ipad pro 2018 with iPadOS 16.2. But i can’t sign in. Help.
<img width="1194" alt="Screenshot 2024-01-15 at 3 44 49 PM png" src="https://github.com/MiRO92/uYou-for-YouTube/assets/44559677/043abade-1b48-44fe-bbed-c8dc96e77fd8">

**Comment by BananaBeast9911** [comment]
Same here. Trolllstore gave the error that some of the binaries were encrypted, so some things might be broken.

**Comment by naveenfunk** [comment]
Any update on this?anyone found any solution to this?
