### ISSUE TITLE
Gesture controls for brightness is limited

### ISSUE THREAD

**Issue by ImmortanJo3** [MiRO92/uYou-for-YouTube#363]
The gesture control for brightness is limited to what seems like +/-5% unlike the volume gesture which works from 0 to 100%.

Thank you for all the work on this great tweak!

**Comment by romantra** [comment]
Is it possible to bring back this feature to modify the brightness? I'm on iOS 17.2.1

**Comment by gurs1kh** [comment]
I'm facing this issue as well, but only on my iOS 16 device. It's not an issue on my old iOS 15 device and both are on the same version of uYou.

**Comment by gurs1kh** [comment]
still an issue on v3.0.4
