### ISSUE TITLE
[Bug] [v3.0.1] "hide Channel avatar" in shorts doesn’t work

### ISSUE THREAD

**Issue by Wrestor** [MiRO92/uYou-for-YouTube#370]
**Device Information**
- iOS/iPadOS version: iOS 17.3 (21D50)
- Device model: iPhone 13 Pro
- Sideload tool: AltStore
- uYou Version: 3.0.1

**Describe the issue**
Ability to hide channel avatar in Shorts doesn’t work.

**Steps to reproduce**
1. enable "Hide channel avatar"

**Comment by MiRO92** [comment]
Thank you for your report, but this feature is not in uYou tweak. It's maybe from another tweak so please contact the developer of that tweak

**Comment by Wrestor** [comment]
@MiRO92 

? 
It's literally on your website in the changelog of version 3.0
<img src="https://github.com/MiRO92/uYou-for-YouTube/assets/54822494/b1a9ee84-6359-4e34-ad3e-195280566507" width=25% height=25%>

https://miro92.com/repo/depictions/changelog.html?p=com.miro.uyou

**Comment by MiRO92** [comment]
Oh! am very sorry, I'll definitely fix it with the next update, thanks a lot for your report
