### ISSUE TITLE
Uyou settings option in general YouTube settings disappeared

### ISSUE THREAD

**Issue by SuperAmirhamza** [MiRO92/uYou-for-YouTube#371]
There used to be an option to show access uyou settings from the general tab of YouTube and now that’s disappeared for the latest versions please can you update uyou so we can access the uyou settings again

**Comment by MiRO92** [comment]
I've just fixed it, I will push an update soon so please stay toned

**Comment by SuperAmirhamza** [comment]
Thank you so much
