### ISSUE TITLE
Playback speed limited to 2x

### ISSUE THREAD

**Issue by jas32096** [MiRO92/uYou-for-YouTube#372]
Since updating to 3.0.1 via the latest version of [uYou+](https://github.com/qnblackcat/uYouPlus/releases/tag/v19.02.1-3.0.1), I'm no longer able to get up to 3x speed, like in prior versions.

I believe this is in uyou, itself, but my apologizes, if it is not. If so, please let me know and I will open the issue there.

**Comment by MiRO92** [comment]
i'll look into this, thanks
