### ISSUE TITLE
1440p+ playback is unavailable

### ISSUE THREAD

**Issue by lawilson97** [MiRO92/uYou-for-YouTube#373]
uYou settings are set to 2160p on WiFi and 1440p on cellular. I am on 3.0.1, and have an iPhone 13 Pro on iOS 17.2.1.
![IMG_4813](https://github.com/MiRO92/uYou-for-YouTube/assets/48016167/4f6f2b39-c95b-4ffa-9f10-1eb830757f31)
![IMG_4814](https://github.com/MiRO92/uYou-for-YouTube/assets/48016167/daf47108-0fe8-4c12-ad2d-eac5ab3dfd2c)

**Comment by MiRO92** [comment]
If you read the note carefully you'll find `If the selected quality is not available, then uYou will choose a lower quality than the one you selected.` which means if 2160p is not available then it will choose a lower quality

**Comment by lawilson97** [comment]
But the selected quality IS available, the videos I’m watching were
uploaded in 4K. The app only recently started not showing 1440p/2160p
options.
