### ISSUE TITLE
Uyou Menu

### ISSUE THREAD

**Issue by KyleKatastrophe** [MiRO92/uYou-for-YouTube#375]
Hello, I disabled the uyou tab and cannot get it back. The setting is not showing in general as I found in previous tickets. 
![IMG_6462](https://github.com/MiRO92/uYou-for-YouTube/assets/63573731/8c9e44c8-242c-4da5-aeb3-4027ff125ce5)
![IMG_6461](https://github.com/MiRO92/uYou-for-YouTube/assets/63573731/09b70f7e-a155-41ab-935e-1658f02ce394)

**Comment by yodaluca23** [comment]
Duplicate https://github.com/MiRO92/uYou-for-YouTube/issues/371#issuecomment-1926252167

**Comment by MiRO92** [comment]
I've already fixed it, will push an update very soon
