### ISSUE TITLE
Download speeds are slow

### ISSUE THREAD

**Issue by aaronliu0130** [MiRO92/uYou-for-YouTube#376]
Opening this since #211 was mysteriously closed. I'd recommend using yt-dlp as the download engine.

**Comment by vux992** [comment]
Can confirm, my download speed on the app is 300kbps. Using Cox fiber 1gbps.

**Comment by aaronliu0130** [comment]
Lucky you, mine is only 32 (while my network speeds usually go to ~30mbps)

**Comment by MiRO92** [comment]
I take download links directly from the YouTube app, unlike other tweaks that decrypt the download links using their servers. As a result, I have no control over the download speed, as it is dependent on YouTube's servers. Additionally, please note that YouTube may impose download limits for certain video qualities, which can affect the speed. Thank you for your understanding

**Comment by aaronliu0130** [comment]
Thanks for the explanation. Is it possible to add link decryption from yt-dlp's code? Currently, every single quality gives me a speed of 32kb.

**Comment by MiRO92** [comment]
> Thanks for the explanation. Is it possible to add link decryption from yt-dlp's code? Currently, every single quality gives me a speed of 32kb, which is way slower than how my video loads. I can finish playing a video much faster than uYou's downloads.
> 
> Edit: They seem to use the https://github.com/tombulled/innertube API

I was decrypting the links using yt-dlp on my server back when I first released uYou, but then I removed it because I didn't want uYou to depend on my server. This decision was made due to the possibility of my server being closed at any given time, as uYou is a free service and I cannot afford to keep my server running for free indefinitely. If that were to happen, uYou would stop working, so I went ahead and removed it.

**Comment by aaronliu0130** [comment]
Is it possible for uYou to query Innertube or do something else directly? Or maybe even bundle yt-dlp's YouTube extractor? [YouTube Reborn](https://github.com/arichornlover/YouTubeRebornPlus/tree/main/Source) also has download speeds that seem normal

**Comment by yodaluca23** [comment]
> I was decrypting the links using yt-dlp on my server back when I first released uYou, but then I removed it because I didn't want uYou to depend on my server. This decision was made due to the possibility of my server being closed at any given time, as uYou is a free service and I cannot afford to keep my server running for free indefinitely. If that were to happen, uYou would stop working, so I went ahead and removed it.

Maybe you could keep both so that as long as your servers up, we can get the high download speeds, but if it ever goes down, we can still download just with slower speeds.

**Comment by aaronliu0130** [comment]
I don't think we need servers, why not just run the commands locally

**Comment by aaronliu0130** [comment]
YTMusicUltimate also released a fast downloader last month.
