### ISSUE TITLE
uYou 0.3.2 crashed youtube 19.05.5

### ISSUE THREAD

**Issue by AnCry1596** [MiRO92/uYou-for-YouTube#377]
After update uYou to 0.3.2, I can’t open YouTube App
YouTube version 19.05.5
Other tweak I installed: iSponsorBlock 1.2.1, Return YouTube Dislike 1.11.6, uYouCrashfix 1.0
I used choicy to limit only these tweak can access YouTube

**Comment by jimmysofat6864** [comment]
Came here to report the exact same thing. Crashing immediately on startup on 19.05.5 on iOS 15.5. Downgrading uYou back down to 0.3.1 seems to fix the issue. I only have tweaks recommended by uYouEnhanced and uYou+ such as uYouImport, YTNoHoverCards, YTMiniPlayerEnabler, YTReExplore, YTNoPaidPromo, uYouCrashFix, iSponsorBlock, YouQuality, YouMute, Return YouTube Dislike, YTVideoOverlay, YTUHD, YouPIP, YTABConfig.

**Comment by ghh-jb** [comment]
Same for me. YouTube 18.33 not launching.

**Comment by iCrazeiOS** [comment]
I can't reproduce the issue myself - do any of you have a crash log from cr4shed?

**Comment by AnCry1596** [comment]
> I can't reproduce the issue myself - do any of you have a crash log from cr4shed?

[text.txt](https://github.com/MiRO92/uYou-for-YouTube/files/14274207/text.txt)
I only have crashlog from KrashKop, my idevice is ios 15.6RC, rootless

**Comment by CySxL** [comment]
I don't think you ever need uYouCrashFix after 3.0.2....

**Comment by AnCry1596** [comment]
> > [text.txt](https://github.com/MiRO92/uYou-for-YouTube/files/14296966/text.txt)
> > Tested without uYou crash fix
> 
> How about 19.06.2? Currently I'm using this build with literally tons of YT tweaks including uYou 3.0.2, all working fine tho.

[text.txt](https://github.com/MiRO92/uYou-for-YouTube/files/14297181/text.txt)
I updated my YouTube to 19.06.2, and uninstall uYouCrashFix and I still can’t open YouTube app

**Comment by AnCry1596** [comment]
> > [text.txt](https://github.com/MiRO92/uYou-for-YouTube/files/14296966/text.txt)
> > Tested without uYou crash fix
> 
> How about 19.06.2? Currently I'm using this build with literally tons of YT tweaks including uYou 3.0.2, all working fine tho.

I think problem come from rootfull or rootless, I updated uyou on my 6s 13.5.1 rootfull, YouTube 17.40.5 and it work without any crashes

**Comment by yodaluca23** [comment]
uYou 3.0.2 does not support any version below 19.06.2 I believe.

**Comment by AnCry1596** [comment]
> uYou 3.0.2 does not officially support any version below 19.06.2 I believe.

I know it because I pop-up a big warning but it still work on my rootfull, problem only happened on my rootless

**Comment by jimmysofat6864** [comment]
> > uYou 3.0.2 does not officially support any version below 19.06.2 I believe.
> 
> I know it because I pop-up a big warning but it still work on my rootfull, problem only happened on my rootless

Not sure if it's a rootless/rootfull problem as I am using uYouEnhanced which comes with uYou 3.0.2 sideloaded on an iPhone 13 with iOS 17.3 (No JB) and it works fine. iPhone 7 Plus iOS 14.8 with Checkra1n (rootfull I believe) and it works fine. But on my iPad with iOS 15.5 palenra1n (rootless) and it doesn't launch with uYou 3.0.2 but launches with 3.0.1.

**Comment by CySxL** [comment]
Might due to this: https://twitter.com/poomsmart/status/1758698679412895961?s=46&t=k-TMUYT86jp0G8VvvZtniA

**Comment by CySxL** [comment]
Install this: https://github.com/PoomSmart/uYou302CrashFix/releases

**Comment by jimmysofat6864** [comment]
> Install this: https://github.com/PoomSmart/uYou302CrashFix/releases

Link is dead.

**Comment by CySxL** [comment]
Yeah it doesn't work as intended.

Try disabling the auto-update checking in uYou.
