### ISSUE TITLE
UYOU YOUTUBE PROBLEMS 

### ISSUE THREAD

**Issue by iphone8plus2019** [MiRO92/uYou-for-YouTube#378]
Hi everybody I’ve tried reaching the maker but no reply so I’m trying here so then the problem I’ve got is two things I’m on 16.4.1 xs max running serotonin jailbreak sileo tweaks do work but uyou does nothing with the two tweaks install  uyou and uYouImport —- uYouImport is what I’m
Chasing I love it because I want to import to music app and keep forever and on my second device iPhone 8plus those tweaks work perfect throw cydia 
How ever I’ve installed the ipa file and trollStore and install but there is a pop up saying some of the plug-in will not work I then go to the app and everything is working expect the most important 
EXPORT TO MUSIC APP so how else can I get this I don’t understand why the new update of uYou 3.0.2 don’t have it attach in the ipa one file download can somebody please help don’t forget which jailbreak I’m using

**Comment by MiRO92** [comment]
Export to Music works only in a full jailbreak environment

**Comment by iphone8plus2019** [comment]
Gutted and thank you for your reply with that said I'll have to use my other device until 16.4.1 has a decent jailbreak because it's xs max I can only use serotonin jailbreak :(

**Comment by xSimone** [comment]
This worked for me on 16.3 with Rootless, Dopamine 2.0.
