### ISSUE TITLE
Two Fingers Tap to Pause/Play not working

### ISSUE THREAD

**Issue by Aransh** [MiRO92/uYou-for-YouTube#380]
Really like the new idea, just updated to v3.0.2 and enabled this but this doesn't seem to work for me...
iPad on iOS 17.4, Running https://github.com/arichornlover/uYouEnhanced/releases/tag/v19.06.2-3.0.2

**Comment by MiRO92** [comment]
I tested it multiple times and it does work perfectly for me, also keep in mind that I don't offer any support other than uYou

**Comment by Aransh** [comment]
Got it, might open a ticket for uYouEnhanced then.
Thanks 🙏🏼
