### ISSUE TITLE
Full screen freezes the iPad app on sideloads

### ISSUE THREAD

**Issue by KRS0ne** [MiRO92/uYou-for-YouTube#383]
I love the app and thank you first of all. My issue is that i can’t leave full screen without closing the app. If you slide down to minimize the screen to the normal player it will trigger the hang counter and it counts to 9000ms and then stops it will keep playing the video normally but all functions will stop and you can not get uyou to do anything. This is probably the hardest update to deal with up to date. You can’t view notifications when full screen, it will also freeze. iPad Pro iOS 17.2.

**Comment by MrAbattoir** [comment]
I have the same issue. Watching a video in fullscreen is fine, but as soon as I swipe down to exit fullscreen there is no user  input allowed. The video continues to play though. 
keep up the great work.

**Comment by jet082** [comment]
This is not completed and still an issue as per https://github.com/MiRO92/uYou-for-YouTube/issues/406 https://github.com/MiRO92/uYou-for-YouTube/issues/400 and https://github.com/MiRO92/uYou-for-YouTube/issues/396

**Comment by stevenkala** [comment]
Same here, still no fix?

**Comment by P-Li0n** [comment]
I am having this issue as well! #1477

**Comment by garbofrogman** [comment]
I’m having the same problem
iPad Air M2
iPadOS 17.6.1
YouTube 19.19.5
unpublished 3.0.3
