### ISSUE TITLE
[BUG] Error while downloading videos 

### ISSUE THREAD

**Issue by TheTrueShadow** [MiRO92/uYou-for-YouTube#385]
Get error un supported download still after update error is -1002 which is unsupported url 
3.0.2 tried with different videos it still only shows up at webm download 
I even reinstalled the app also the download button still doesn’t exist in the uyou section time download is null and every other value as shown in the images causes unknown (iPad so version 15.4 install use TrollStore )
![B2014B95-E1ED-4F07-ABA5-1B42ADAEFEF1](https://github.com/MiRO92/uYou-for-YouTube/assets/80232013/739d75db-682c-40f1-b870-bce62c26b337)

![AFFB6BF4-AA81-4EAB-82B8-87A27FE4A4A5](https://github.com/MiRO92/uYou-for-YouTube/assets/80232013/8149722f-81b1-4db7-b78a-e13e5e72903a)

**Comment by TheTrueShadow** [comment]
This is what shows up in video the only way to download 
![E669016C-EDA3-4E2D-9F86-04B3C8566E80](https://github.com/MiRO92/uYou-for-YouTube/assets/80232013/101805b0-21e0-4ce4-8217-1a5f8e48c487)

**Comment by MiRO92** [comment]
Just tested on my device with the same video and it works fine.

**Comment by TheTrueShadow** [comment]
But how would I go about fixing this any ideas?
