### ISSUE TITLE
[Questions] Is there a way to manually place pre-downloaded audios/videos into uyou?

### ISSUE THREAD

**Issue by Zeannn** [MiRO92/uYou-for-YouTube#393]
I was wondering if I can use the uYou app as a music player to play audio/video files, because the downloading feature is kinda slow and sometimes buggy. I use yt-dlp to download my music and I tried placing the files into the uYou folder but it doesn't appear on the app.

**Comment by MiRO92** [comment]
Sorry, but that isn't possible, as I'm using a database and other components that can't be easily import videos without additional code
