### ISSUE TITLE
Freezes when opening youtube

### ISSUE THREAD

**Issue by Darthveder69420** [MiRO92/uYou-for-YouTube#395]
3.02 freezes youtube when you open it.

i am on ios 16.1.2 and am jailbroken with dopamine

**Comment by migdal-or** [comment]
The same for me. Why did I upgrade.
Ipad pro10.5" 2017, iOS 16.5.1, palera1n

**Comment by CrazyWolf13** [comment]
Can confirm

Ios 17.2
Palera1n

**Comment by sanderDijkxhoorn** [comment]
+1 iOS 16.0.2 dopamine

**Comment by ryukfort** [comment]
The same thing here, But I just installed another uYoutube.. and it works very well. I have the Dopamine jailbreak in iOS 16.1.2. iPhone 13 Pro.Max
