### ISSUE TITLE
#

### ISSUE THREAD

**Issue by apzrn** [MiRO92/uYou-for-YouTube#397]

**Comment by abbaskabul** [comment]
mine works well iPad Pro M1 ios 16.4.1 trollstore.

**Comment by azanol** [comment]
Same happening to me. Downloads go to 100% but then freeze. Reverted back to previous version.

**Comment by arichornlover** [comment]
Not only it effected uYou, it also broke the downloading in [YouTubeReborn](https://github.com/arichornlover/YouTube-Reborn-v5)
I’m assuming this broke after the DMCA happened >;(

**Comment by arichornlover** [comment]
Hey, downloads is technically broken, as of writing this message, I’m unable to download **.mp4** files within uYou.
but I can still download **.webm** but this format isn’t good since it does waste more storage on my device compared to a .mp4.
