### ISSUE TITLE
I'd like to inquire about YT setting crash

### ISSUE THREAD

**Issue by Theremind** [MiRO92/uYou-for-YouTube#399]
When I click on the captured settings, it comes out as a desktop, but it's the same when I downgrade and test it. Can I know why? I can't change the settings

uyou- 3.03 / 3.02 /3.01
dopamin , 15.0

![0AC65494-4A13-45E4-AD53-3F46BD991232](https://github.com/MiRO92/uYou-for-YouTube/assets/160265933/95ec231d-f5be-4942-bdef-0a9b22873eb6)

**Comment by rahadwi** [comment]
same, from 3.0.1 not fix until 3.0.3, always crash when click "video player settings"

ios : 15.1

**Comment by Theremind** [comment]
me all crash 
but The reorder tab sometimes goes in
