### ISSUE TITLE
Some videos are crashing uYou

### ISSUE THREAD

**Issue by oomek** [MiRO92/uYou-for-YouTube#40]
This video is crashing the app and many other with simillar parameters, 50 fps, resolution, I don't know exactly.

https://youtu.be/DMNxOmNzfb0

**Comment by oomek** [comment]
Many more are crashing now, what is going on?
https://youtu.be/DDxo18SHOEg

**Comment by oomek** [comment]
Now almost all videos are crashing. I have to uninstall uYou unfortunately as it's become unusable.

**Comment by qnblackcat** [comment]
pretty sure you hide too many buttons under the video player 🤷‍♂️

**Comment by oomek** [comment]
I had to enable more than 2 buttons. It stopped crashing then.
