### ISSUE TITLE
le PIP ne fonctionne pas sur IOS 17.x.x

### ISSUE THREAD

**Issue by guntil** [MiRO92/uYou-for-YouTube#402]
Depuis la version 18.x.x le PIP des vidéos ne fonctionne pas.
Nous sommes obligés de rester sur la version uYouPlus_17.39.5_2.1

Merci aux développeurs de pouvoir remettre cette option qui est fort utile.

**Comment by guntil** [comment]
Avez vous corrigé le problème depuis ?

**Comment by Nasstyle771** [comment]
I use 17.4 beta 4 and the pip works
![IMG_6667](https://github.com/MiRO92/uYou-for-YouTube/assets/159941433/3fcbebfd-2779-49d2-b8fd-cac8bcf23bf5)
