### ISSUE TITLE
Weird incorrect audio when playing from notification bar

### ISSUE THREAD

**Issue by b007zk** [MiRO92/uYou-for-YouTube#405]
If you pause the video then from the notification bar you hit play again, the audio from the video will play two audio streams on top of each other in a strange manner. At first I thought it was just doubling but it sounds as though it's playing audio from two different parts of the video at the same time. I also notice the time label in the notification bar goes from like 6 minutes to 1 minute something when you hit play and pause (this incorrect timestamp corrects after a moment in both cases but the audio remains messed up).

**Comment by plia7** [comment]
Looks like it's a similar issue or same root cause to the one I reported here: https://github.com/MiRO92/uYou-for-YouTube/issues/420
