### ISSUE TITLE
Side loaded doesn’t reduce full screen

### ISSUE THREAD

**Issue by KRS0ne** [MiRO92/uYou-for-YouTube#406]
When in sideloaded and you enter full screen it will not go away. When you close the app the video continuously plays in the background. I had to restart my iPad to get it to stop. I tried three times. It’s the same issue as 3.0.2

**Comment by bloomingful** [comment]
I can confirm that this is also present in the jailbroken tweak. Exiting fullscreen mode by sliding down or by tapping on the fullscreen button will result in a freeze as also mentioned in #383 #396 and #400 .
