### ISSUE TITLE
"hide shorts cell" option cause blank area on Subscriptions tab

### ISSUE THREAD

**Issue by ev0tto** [MiRO92/uYou-for-YouTube#408]
Steps to reproduce

1. enable "hide shorts cell" in uYou settings
2. see the subscriptions

<details><summary>enabled</summary>

![](https://github.com/MiRO92/uYou-for-YouTube/assets/80548883/8c4a0dfc-5756-4d9e-9584-fce5e14f95d1)
</details>

<details><summary>disabled</summary>

![](https://github.com/MiRO92/uYou-for-YouTube/assets/80548883/0c18dac5-ca94-45ae-bff1-0b3c3d7c7b88)
</details>

Additional Information

The issue is more pronounced on uYouEnhanced when "Hide Community Posts" is enabled.(YTNoCommunityPosts?)

<details><summary>when Hide Community posts option enabled</summary>

![](https://github.com/MiRO92/uYou-for-YouTube/assets/80548883/e9759f91-d4b7-4bf5-9beb-c10d4daeba4e)
</details>

I think this is related to the issue below.

https://github.com/arichornlover/uYouEnhanced/issues308

**Comment by arichornlover** [comment]
This issue is not related to MiRO92’s uYou.
I modified that option in uYouEnhanced because the one from uYou just wasn’t working so the issue is most likely not related to this repo.

**Comment by ev0tto** [comment]
The first two videos I attached (when enabled and when disabled) are videos of the .ipa file distributed in uYou's [release](https://github.com/MiRO92/uYou-for-YouTube/releases/tag/3.0.3). 
I think there is an issue with uYou as well.
