### ISSUE TITLE
Downloading. I use uYouEnhanced latest version + uyou 3.03

### ISSUE THREAD

**Issue by Nasstyle771** [MiRO92/uYou-for-YouTube#410]
Hi. I tried to download videos but the downloader doesn’t seem to work. It stays blocked at the end even if the download is finished and when we restart the app, the download shows Cancelled and we need to redownload it, but it still wouldnt work. Also please tell me if I posted it in the right github since I use another version but download is on uyou so I thought id go directly to the source. Tell me if that was right
![IMG_6666](https://github.com/MiRO92/uYou-for-YouTube/assets/159941433/63b1618a-34eb-4eb0-81de-935562467b85)

**Comment by nucleiis** [comment]
Same problem!

**Comment by Lynnhs1n** [comment]
Same problem

**Comment by Lynnhs1n** [comment]
![image](https://github.com/MiRO92/uYou-for-YouTube/assets/109627967/a52343f0-9746-4c7c-a556-5108ffd72387)

**Comment by castdrian** [comment]
From what I can tell this happens when apps are signed with a distribution certificate instead of a development certificate

**Comment by nucleiis** [comment]
> From what I can tell this happens when apps are signed with a distribution certificate instead of a development certificate

I tried iOS Development certificate and provisioning but no luck.
