### ISSUE TITLE
Crashing on video

### ISSUE THREAD

**Issue by Naxussy** [MiRO92/uYou-for-YouTube#412]
I seem to keep crashing whenever I click on a video. It started after i updated to uYou 3.0.3 with Sidestore on iOs 17.3.1. The page loads and even a bit of the video but it immediately crashes.

**Comment by ZsoltiHUB** [comment]
Hey! How did you resolve this issue?

**Comment by pha1n0q** [comment]
> Hey! How did you resolve this issue?

Go to uYou's settings > Video Player > Disable "Playback Speed Controls"
