### ISSUE TITLE
"Remove Youtube Ads" causes home page to hide apps, but keep the empty spaces

### ISSUE THREAD

**Issue by JustSxm** [MiRO92/uYou-for-YouTube#415]
When I disabled the toggle and show the ads this doesnt happen.

Something is going on, i dont know how to help you better, sorry.

3.0.3 crashes so im on 3.0.2, but this still happens on 3.0.3.

https://github.com/MiRO92/uYou-for-YouTube/assets/42727829/84722f7d-edbb-418f-b8b7-3d45ce571849

**Comment by JustSxm** [comment]
The issue occurs in youtube v18.17.2 and above.

**Comment by testaccount401** [comment]
I have the same issue with uYouPlus_19.12.3-3.0.3 & uYouPlus_19.13.1-3.0.3

Edit: It worked first for a couple of days and started then inside the same .ipa version. Reinstalling / resetting the settings does not help.
