### ISSUE TITLE
[Bug][Dirty Fix] Hide Save Button, Hide Share Button and Hide Create Shorts Button only work after language is set to English and Region is set to US.

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#42]
This is an extension to this bug report: https://github.com/MiRO92/uYou-for-YouTube/issues/26

As the title said, these three options work only after the language is set to English **and** the region is set to US. It has to be both at the same time. Now you can hide those three buttons, and it will even work when you set your Region back to whatever you want.

I have no explanation for this, but it seems to work. Language English, region Germany, and I'm able to hide these buttons for the first time ever.

**Comment by MiRO92** [comment]
Thanks a lot for your report, I've fixed this issue by rewriting the whole code of hiding these buttons and now it works great (also tested it in another languages such as Germany)
