### ISSUE TITLE
Compilation Error - Decrypted YouTube IPA v19.09.4

### ISSUE THREAD

**Issue by junaid143143** [MiRO92/uYou-for-YouTube#421]
https://github.com/MiRO92/uYou-for-YouTube/issues/164

==> Compiling SponsorBlockRequest.m (arm64)…
iSponsorBlock.xm:19:47: error: member reference base type 'const char[50]' is not a structure or union
==> Compiling iSponsorBlock.xm (arm64)…
            bundle = [NSBundle bundleWithPath:ROOT_PATH_NS("/Library/Application Support/iSponsorBlock.bundle")];
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/rootless.h:10:30: note: expanded from macro 'ROOT_PATH_NS'
#define ROOT_PATH_NS(nsPath) JBROOT_PATH_NSSTRING(nsPath)
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/libroot/libroot.h:20:36: note: expanded from macro 'JBROOT_PATH_NSSTRING'
#define JBROOT_PATH_NSSTRING(path) __CONVERT_PATH_NSSTRING(libroot_dyn_jbrootpath, path)
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/libroot/libroot.h:17:47: note: expanded from macro '__CONVERT_PATH_NSSTRING'
        [NSString stringWithUTF8String:converter(path.fileSystemRepresentation, tmpBuf)]; \
                                                 ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/rules.mk:390: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.61968dba.o] Error 1
rm /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.mm
make[3]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:52: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.dylib] Error 2
make[2]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make[1]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/rules.mk:146: iSponsorBlock.all.tweak.variables] Error 2
make: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
Error: Process completed with exit code 2.

**Comment by wuaan204** [comment]
same to you

**Comment by Utyranto** [comment]
I got the same error as well and I've been struggling to figure out why that is and even more so that I used the same download link for the IPA.

**Comment by JakeAi** [comment]
Same

**Comment by wuaan204** [comment]
in line 68 buildapp.yml
REPLACE
ref: master
WITH
ref: 4bcc52914e0eeca719288522938185decaa8a1cb

**Comment by arichornlover** [comment]
^

**Comment by Menojohnson** [comment]
I am having a problem compiling also. I get an error saying “ Error: Process completed with exit code 2.

**Comment by wuaan204** [comment]
> I am having a problem compiling also. I get an error saying “ Error: Process completed with exit code 2.

just follow my steps upper there

**Comment by melikootje** [comment]
> in line 68 buildapp.yml REPLACE ref: master WITH ref: 4bcc52914e0eeca719288522938185decaa8a1cb

This wont fix it in my case
