### ISSUE TITLE
Error when building 

### ISSUE THREAD

**Issue by Utyranto** [MiRO92/uYou-for-YouTube#424]
I get the following error when trying to build the app:

![image](https://github.com/MiRO92/uYou-for-YouTube/assets/82338085/f307a796-0304-47ea-8cbc-17e9165198f0)

**Comment by wuaan204** [comment]
in line 68 buildapp.yml
REPLACE
ref: master
WITH
ref: 4bcc52914e0eeca719288522938185decaa8a1cb
