### ISSUE TITLE
IPA Download

### ISSUE THREAD

**Issue by zacharciniega** [MiRO92/uYou-for-YouTube#429]
Where is the download link for the ipa? Only thing I see is the README

**Comment by paulxh** [comment]
You have to build your own IPA due to Google DMCA complaints.

**Comment by KodaFjellreven** [comment]
> You have to build your own IPA due to Google DMCA complaints.

What does that mean exactly? How do I build one myself?

**Comment by paulxh** [comment]
> > You have to build your own IPA due to Google DMCA complaints.
> 
> What does that mean exactly? How do I build one myself?

Man, [use Google](https://github.com/qnblackcat/uYouPlus/wiki/Building).

**Comment by KodaFjellreven** [comment]
> > > You have to build your own IPA due to Google DMCA complaints.
> > 
> > 
> > What does that mean exactly? How do I build one myself?
> 
> Man, [use Google](https://github.com/qnblackcat/uYouPlus/wiki/Building).

Man, thanks for helping me use google, it means a lot.

**Comment by gmanc2** [comment]
> > > You have to build your own IPA due to Google DMCA complaints.
> > 
> > 
> > What does that mean exactly? How do I build one myself?
> 
> Man, [use Google](https://github.com/qnblackcat/uYouPlus/wiki/Building).

What you linked to is unrelated to his question. I would like to know how to build your own version of YouTube. Unless you mean decrypt your own IPA rather than build.

**Comment by MiRO92** [comment]
I'm currently working on an update and will be releasing it very soon, along with the IPA links
