### ISSUE TITLE
[Feature Request] Option to remove the "Thanks" button under Videos

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#43]
![image](https://user-images.githubusercontent.com/16444679/133926858-5c816f43-42d8-40d0-86d3-dffdc2932a02.jpeg)

Like for the other buttons, users should have the option to remove this button as well.

**Comment by MiRO92** [comment]
can you please send me the link to this video so I can add support to hide it

**Comment by theoccurrence** [comment]
It's a channel-wide thing as far as I can see. Here is a video from a channel that has this button enabled: https://youtu.be/SzoR5TN5Svc

Thank you for your work 😊

**Comment by ErSpieltHD** [comment]
What's the progress on this?
