### ISSUE TITLE
(Bug) swipe gesture of brightness not working

### ISSUE THREAD

**Issue by CySxL** [MiRO92/uYou-for-YouTube#432]
Swipe gesture of brightness is not working properly on iOS16/17.

It can only adjust the brightness once for like approximately 4%, then it refuses to work again. You can only adjust the brightness in +/-4% range of the current brightness level.

Tested on iOS 16.3/iPhone 14 Pro Max/Dopamine 2.0.11/uYou 3.0.3 installed as deb/YouTube 19.10.5 and above.

and iOS 17.2/iPhone 15 Pro Max/Sideloadly/uYou injected to IPA/YouTube 19.10.5 and above.

**Comment by MiRO92** [comment]
fixed
