### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by EdenJahh** [MiRO92/uYou-for-YouTube#435]
So does anyone know how to build the ipa or where to get it?

**Comment by MagicDude17** [comment]
im also kinda lost. i am looking into it and i will update you if i find something

**Comment by d3ibis** [comment]
@EdenJahh @MagicDude17  Its simple, there is a repo, u need to fork it & just run the Github action, u need to have a decrypted IPA.

I did it today for latest version & worked, there is one bug I was going to submit :D

**Comment by syedrumi** [comment]
> @EdenJahh @MagicDude17 Its simple, there is a repo, u need to fork it & just run the Github action, u need to have a decrypted IPA.
> 
> I did it today for latest version & worked, there is one bug I was going to submit :D

bro its simple for you...many of us dont even know the terms you are using...if there is a step by step guide that would be helpful
thanks

**Comment by d3ibis** [comment]
> > @EdenJahh @MagicDude17 Its simple, there is a repo, u need to fork it & just run the Github action, u need to have a decrypted IPA.
> 
> > 
> 
> > I did it today for latest version & worked, there is one bug I was going to submit :D
> 
> 
> 
> bro its simple for you...many of us dont even know the terms you are using...if there is a step by step guide that would be helpful
> 
> thanks

Brother, read this guide (Method 1 - Github), u just need to fork the repo, grap a decrypted IPA, upload it to Google Drive or any cloud service, paste the link in the workflow and wait for 2-4 minutes & u'll have the ready IPA

https://github.com/qnblackcat/uYouPlus/wiki/Building

![image](https://github.com/MiRO92/uYou-for-YouTube/assets/17270352/7484343c-4421-4ba2-aa4f-0981bf6e86c5)

![image](https://github.com/MiRO92/uYou-for-YouTube/assets/17270352/5517ecd0-49db-44b1-a9fb-4e64127d3b9e)

**Comment by MagicDude17** [comment]
What is a fork? How do I get it. How do I get a decrypted ipa. What even is a decrypted ipa?

**Comment by d3ibis** [comment]
@MagicDude17 using ur Github account, fork [this repo](https://github.com/qnblackcat/uYouPlus) <- u will see **Fork** button next to watch, it'll (copy) the repo into ur profile...1st step done (**THIS IS A ONE TIME STEP**)

- Now will explain regarding decrypted app...

Appstore Apps are all **encrypted**, you can't overwrite them or edit/tweak them while they're encrypted. so we need a decrypted app/ipa in order to inject these tweaks/modifications into it.

Luckily, there are websites providing these ready-decrypted IPAs (or if u have a jailbroken iPhone, u can decrypt it by urself in minutes). Also there are some Telegram bots u give them app link in Appstore & they'll give you the decrypted one.

**Back to track now**, You have the decrypted IPA, already forked the mentioned repo, follow steps mentioned in my previous comment (upload IPA to google drive...etc and grab the direct link to download) and go to **YOUR REPO** now bcoz u forked this one into ur profile.

Click on action tab, run the workflow and wait for 10 min max & u'll have the new modified IPA...

I already created one for latest version released today, u can find it [here](https://github.com/d3ibis/uYouPlus/releases)

Trust me, its really simple, u just need to find the decrypted ipa (u can google it), upload the ipa, paste the direct download link in the workflow & wait couple of minutes ^_^

**Comment by Supernoww** [comment]
This helped so much, thanks!!

**Comment by Guit3ristM3n** [comment]
Thxxxx you are the goat !!

**Comment by MagicDude17** [comment]
thanks it worked. but it doesnt accept my decrypted ipa. what do i have to do? i just copied the download file for the ipa from google drive. What am i missing?

**Comment by d3ibis** [comment]
> thanks it worked perfectly.

It has some bugs with downloading, I'm trying something different now until he updates this...

Glad it worked! next time u'll just need the ipa file & **put in mind to sync ur fork when he pushes updates**

**Comment by MagicDude17** [comment]
hey, quick update. it worked at first, but it doesnt accept my decrypted ipa. what do i have to do? i just copied the download file for the ipa from google drive. What am i missing?

**Comment by d3ibis** [comment]
> hey, quick update. it worked at first, but it doesnt accept my decrypted ipa. what do i have to do? i just copied the download file for the ipa from google drive. What am i missing?

Try to download the ipa from google drive, when it finished go to Downloads inside Chrome and copy the **direct download link from there** (This is how I'm doing it always)

**Comment by ijonathang** [comment]
Hi friend :) 

I'm looking for a decrypted IPA, I don't know if you can help me with it.

Thanks by the way!

**Comment by d0g4-c3m** [comment]
@d3ibis do you know any active telegram bots to decrypt ipa’s? If so, can you give me a link or a name?

**Comment by d3ibis** [comment]
> @d3ibis do you know any active telegram bots to decrypt ipa’s? If so, can you give me a link or a name?

Yeah sure, there is an active one but linked to a group and can't use it as standalone...

The group is useful in general, but u can just use the decrypt bot

Group name: AppTesters

https://t.me/AppleTesters

How to use: 

```
/request and app link from Appstore
``` 
and wait for couple of minutes...

![image](https://github.com/MiRO92/uYou-for-YouTube/assets/17270352/e5aa1ae4-4e1b-4191-a661-0d1164147804)

**Comment by qulonny** [comment]
> > @d3ibis do you know any active telegram bots to decrypt ipa’s? If so, can you give me a link or a name?
> 
> Yeah sure, there is an active one but linked to a group and can't use it as standalone...
> 
> The group is useful in general, but u can just use the decrypt bot
> 
> Group name: AppTesters
> 
> https://t.me/AppleTesters
> 
> How to use:
> 
> ```
> /request and app link from Appstore
> ```
> 
> and wait for couple of minutes...
> 
> ![image](https://private-user-images.githubusercontent.com/17270352/321500669-e5aa1ae4-4e1b-4191-a661-0d1164147804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjc2NjAsIm5iZiI6MTcxMzE2NzM2MCwicGF0aCI6Ii8xNzI3MDM1Mi8zMjE1MDA2NjktZTVhYTFhZTQtNGUxYi00MTkxLWE2NjEtMGQxMTY0MTQ3ODA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3NDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMzM2ZDIyNzk5NTliNDMwOGRiY2NiZjVjMzc3MmYxNDM0MWZjYWIyMTgxZTY2YTJiNTU1MDZkMjY2MjE4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jnGgLQOXn1hMT60po3pGAoE6Zz-P7vdSoMDaGE80REs)

Can you help me? I wasted an hour trying to to do this. Same error. Google drive ipa or zip, from downloads. Nothing WORKS>

**Comment by qulonny** [comment]
> > hey, quick update. it worked at first, but it doesnt accept my decrypted ipa. what do i have to do? i just copied the download file for the ipa from google drive. What am i missing?
> 
> Try to download the ipa from google drive, when it finished go to Downloads inside Chrome and copy the **direct download link from there** (This is how I'm doing it always)

Can you help me? Tried from google drive, downloads ipa or zip, nothing works for me. Im tired. 
![chrome_GlTxwEHCgd](https://github.com/MiRO92/uYou-for-YouTube/assets/167062114/67f2055e-676f-4946-9c62-1f11f8e5746c)

**Comment by d3ibis** [comment]
> > > hey, quick update. it worked at first, but it doesnt accept my decrypted ipa. what do i have to do? i just copied the download file for the ipa from google drive. What am i missing?
> > 
> > 
> > Try to download the ipa from google drive, when it finished go to Downloads inside Chrome and copy the **direct download link from there** (This is how I'm doing it always)
> 
> Can you help me? Tried from google drive, downloads ipa or zip, nothing works for me. Im tired. ![chrome_GlTxwEHCgd](https://private-user-images.githubusercontent.com/167062114/322396514-67f2055e-676f-4946-9c62-1f11f8e5746c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjk4MzgsIm5iZiI6MTcxMzE2OTUzOCwicGF0aCI6Ii8xNjcwNjIxMTQvMzIyMzk2NTE0LTY3ZjIwNTVlLTY3NmYtNDk0Ni05YzYyLTFmMTFmOGU1NzQ2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwODI1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTcwMmQyNWMwODRlY2JkYTFmOWIzYzU3NTcxYWJmM2E5MTU3MjhkZDY5MjYzNjZlNmJkOTIyY2NjMDRjYzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.owpNKKapEYfWBzicL7D7Q4fag9qmM349PGtNRVS9Nkw)

Use [THIS](https://litterbox.catbox.moe/) to upload ur ipa.  it'll give u a direct link.

**Comment by syedrumi** [comment]
You need to allow permission on google drive anyone with link

**Comment by qulonny** [comment]
> Use [THIS](https://litterbox.catbox.moe/) to upload ur ipa. it'll give u a direct link.

Thank you.

**Comment by qulonny** [comment]
> You need to allow permission on google drive anyone with link
I allowed. Don't know why it didn't work.

**Comment by d3ibis** [comment]
> > You need to allow permission on google drive anyone with link
> > I allowed. Don't know why it didn't work.

Use the site I provided, much better. I'm making my own site to upload files, will published soon.
