### ISSUE TITLE
Working on latest - Not saving

### ISSUE THREAD

**Issue by d3ibis** [MiRO92/uYou-for-YouTube#436]
ThanQ for this amazing tool <3

I have the latest version 3.0.3 & I managed to inject it with latest YT version 19.12.3

Everything is working fine EXCEPT saving, its downloading video & audio, when it reaches for 100% nothing happened (not saving to either Folder or CameraRoll) & Iwaited for hours, still not saving/completing the download.

![IMG_0442](https://github.com/MiRO92/uYou-for-YouTube/assets/17270352/e8537491-26d7-4269-8b03-6e03d767543e)

Awaiting for your reply @MiRO92 <3

**Comment by nucleiis** [comment]
Same here, I tried to use a developer certificate without luck

**Comment by d3ibis** [comment]
> Same here, I tried to use a developer certificate without luck

I fixed it by replacing the dylib with 3.0.1

Now facing another issue, when playing any video it'll crash 😅 but when watshing shorts & downloading them working perfectly! 😂
