### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by YaBoiJaydenO** [MiRO92/uYou-for-YouTube#438]
Can open the app  but as soon as I press a video to watch, it crashes. 

https://github.com/MiRO92/uYou-for-YouTube/assets/60756686/29e301dd-b160-4cab-b07e-6eba16d61d79

**Comment by mrkssntr** [comment]
Same started today, shorts work though.
Turning off Sponserblock seems to fix the issue

**Comment by alextaymx** [comment]
Disabling Sponsorblock works  👍

**Comment by HuyVDSE** [comment]
Disabling Sponsorblock works 😄

**Comment by LonelyIlands** [comment]
Does anyone know how to get the ipa?

**Comment by frajertoms** [comment]
How do i turn off the sponsorblock?

**Comment by mrkssntr** [comment]
> How do i turn off the sponsorblock?

![image](https://github.com/MiRO92/uYou-for-YouTube/assets/26551860/9249fafc-d8e9-4a56-842d-90e598fcf6d0)

**Comment by arichornlover** [comment]
Y’all aren’t gonna believe this but. This is completely unrelated to MiRO92’s uYou.

**Comment by mrchoc** [comment]
disabling sponsorblock doesnt prevent crashing for me

**Comment by TheNightRider12** [comment]
Updating to the latest YouTube version + latest uYouEnhanced commits and building the IPA seems to have fixed the issue for me.

**Comment by Niki8173** [comment]
Same here, disabling sponsorblock doesn’t help

**Comment by creativegamer03** [comment]
> > How do i turn off the sponsorblock?
> 
> 
> 
> ![image](https://github.com/MiRO92/uYou-for-YouTube/assets/26551860/9249fafc-d8e9-4a56-842d-90e598fcf6d0)
> 
> 

Is the option also available in the tweak version? I can't find it.

![image](https://github.com/MiRO92/uYou-for-YouTube/assets/66676126/c2ea2d49-0130-4aa9-8582-cd6df38309e3)

Also, after downgrading YouTube several times, I was able to find out that 19.10.7 works well with the tweak.

**Comment by LiquidDeath911** [comment]
I am having this issue as well.

**Comment by TheNightRider12** [comment]
Please make issue posts in the appropriate repos. These issues aren’t related to this repo. Everything works fine for me on the updated YouTube version. Since I build it myself.

**Comment by arichornlover** [comment]
> Y’all aren’t gonna believe this but. This is completely unrelated to MiRO92’s uYou.

I did say this in this post. And btw this issue that is here is definitely unrelated to MiRO92’s uYou because the `App crashing` problem is fixed. iSponosrBlock updated so the issue can be closed.

However, videos do crash if uYou’s playback speed options are enabled.

**Comment by LiquidDeath911** [comment]
> Please make issue posts in the appropriate repos. These issues aren’t related to this repo. Everything works fine for me on the updated YouTube version. Since I build it myself.

It is related to this repo though. I installed the tweak from MiRO’s repo and the YouTube app crashes when tapping on any videos.

**Comment by MiRO92** [comment]
I've fixed this issue, will release an update soon
