### ISSUE TITLE
iOS 15 support

### ISSUE THREAD

**Issue by t0mi** [MiRO92/uYou-for-YouTube#44]
I can't sign uYou for iOS 15. I get this error:

Signature failed: Does not support encrypted ipa packets

**Comment by theoccurrence** [comment]
It would help, if you revealed your signing method.

**Comment by t0mi** [comment]
Oh sorry. I want to sign on my windows pc with 3uTools. 
Cercube works, but not uYou.

**Comment by theoccurrence** [comment]
I don't know which IPA you used, but 3uTools can only sign decrypted IPAs.

Try a different IPA like https://appdb.to/app/cydia/1900000830 or try a different signing method. I'm on iOS 15 and it works great for me.

**Comment by t0mi** [comment]
![image](https://user-images.githubusercontent.com/51470532/134617382-b2860634-4a97-4be7-a308-113e7b28b397.jpeg)

I used this ipa. The ipa from the GitHub description.

**Comment by theoccurrence** [comment]
Try a different signing method, like AltStore

**Comment by Macleykun** [comment]
AltStore indeed works, tried it on two ios15 devices.

**Comment by MiRO92** [comment]
@t0mi can you please try the new update and let me know if it's working on iOS 15?
Thank you

**Comment by t0mi** [comment]
I don't get it work with windows. But I friend signed it with Mac. It's work great now. :)

**Comment by Macleykun** [comment]
Perhaps close the issue then aswell?
