### ISSUE TITLE
Notorized by apple 

### ISSUE THREAD

**Issue by melikootje** [MiRO92/uYou-for-YouTube#443]
Hey,

i was wondering if you guys can make this app notorized so i can use it on my altstore pal subscription..

thanks in advance!

greetings,
Meliko

**Comment by yodaluca23** [comment]
I doubt Apple would notarize any tweaked apps, as they're copyrighted, and could also be seen as malicious...

**Comment by melikootje** [comment]
Notarizing is different from app review tho, see https://www.macrumors.com/2024/01/25/alternative-app-store-notarization-process/

it only checks if it doesnt have any malware or executable code in terms of security, so i think it could just go well

**Comment by yodaluca23** [comment]
> Notarizing is different from app review tho, see https://www.macrumors.com/2024/01/25/alternative-app-store-notarization-process/
> 
> 
> 
> it only checks if it doesnt have any malware or executable code in terms of security, so i think it could just go well

Yes, that's exactly what I am saying, it will likely be seen as phishing...
