### ISSUE TITLE
Youtube 19.14.2 uyou 3.0.3 crash when click on any video

### ISSUE THREAD

**Issue by tumo07** [MiRO92/uYou-for-YouTube#444]
Crashes when click on any video, shorts works, let the video auto preview works it just crash when click on any video
Toggled off playback speed controls in uyou settings fixed it
Log file said it is error with setplaybackspeed
Here is log file: https://file.io/xT03uD3nCNcc
Also this may help: https://github.com/qnblackcat/uYouPlus/issues/1422#issuecomment-2066929578

**Comment by ZsoltiHUB** [comment]
I have the same issue. Found anything yet?

**Comment by dymbox** [comment]
Same here, even downgraded down to 19.12.3, still crashes in same manner. iOS 15.3.1
Toggling off playback speed controls helped after respring

**Comment by Bogdan-Hasanov** [comment]
> Same here, even downgraded down to 19.12.3, still crashes in same manner. iOS 15.3.1
> Toggling off playback speed controls helped after respring

That worked. It's been a week with original yt, and now it's fine again. Thanks a lot

**Comment by DethSaucin** [comment]
Where is this setting located? I can’t seem to find it.

**Comment by ShuNegus** [comment]
> Where is this setting located? I can’t seem to find it.

Settings -> General -> uYou (Show uYou settings) -> Video player -> Playback speed control

**Comment by L10nhunter** [comment]
This works.

**Comment by SushiRoll55** [comment]
This did not work for me, but disabling iSponsorBlock did.

**Comment by jimmysofat6864** [comment]
I have iSponsorBlock enabled and disabled Speed controls and that seemed to work for me. Crashlogs are attached below. 
[text-0C87020BD285-1.txt](https://github.com/MiRO92/uYou-for-YouTube/files/15214261/text-0C87020BD285-1.txt)
[text-69CDD6F9C96B-1.txt](https://github.com/MiRO92/uYou-for-YouTube/files/15214262/text-69CDD6F9C96B-1.txt)
[text-9183A41B1188-1.txt](https://github.com/MiRO92/uYou-for-YouTube/files/15214263/text-9183A41B1188-1.txt)
[text-931861DF3A57-1.txt](https://github.com/MiRO92/uYou-for-YouTube/files/15214264/text-931861DF3A57-1.txt)
[text-A119877100DD-1.txt](https://github.com/MiRO92/uYou-for-YouTube/files/15214265/text-A119877100DD-1.txt)

**Comment by creativegamer03** [comment]
this tweak needs to be updated with the latest version of iSponsorBlock. latest build from iSponsorBlock no longer causes crashing, but the version used by this tweak currently uses the old version. hoping the dev is currently doing it

**Comment by b007zk** [comment]
I have this happening on the version uYouPlus 19.08-2.3.0.3. disabling isponsorblock and playback speed control doesn't work. Still crashes after clickong on any video.
