### ISSUE TITLE
"Download the IPA/ZIP file from the link above", but the link doesn't works

### ISSUE THREAD

**Issue by punto2018** [MiRO92/uYou-for-YouTube#446]
Hi, I would like to install the ipa in one of the several methods, or also resigning it by me, but the link provided to download the ipa don't works. Am I making somthing wrong?

**Comment by xoniq** [comment]
https://github.com/MiRO92/uYou-for-YouTube/releases

Was it that hard to just think; well let’s try the releases list then.

**Comment by erazemk** [comment]
@xoniq Not sure what you see, but for at least two weeks I only saw the default "source" zips, which just have the readme.
<img width="741" alt="image" src="https://github.com/MiRO92/uYou-for-YouTube/assets/46302511/7305fff7-caf7-47e3-9e40-36a7e990d60c">

**Comment by tepRuslan** [comment]
Inside the downloaded archive only ReadMe.Md.
There are no .ipa files in the archive.
Neither in Zip, nor in tar.

**Comment by AliChaos** [comment]
> https://github.com/MiRO92/uYou-for-YouTube/releases
> 
> Was it that hard to just think; well let’s try the releases list then.

Are you literally retarded?

**Comment by tepRuslan** [comment]
> > https://github.com/MiRO92/uYou-for-YouTube/releases
> > Was it that hard to just think; well let’s try the releases list then.
> 
> Are you literally retarded?

How about you?
Look at erazemk's screenshot above. There are no other files there except Source code, and they don't contain .ipa files.

**Comment by AliChaos** [comment]
> > > https://github.com/MiRO92/uYou-for-YouTube/releases
> 
> > > Was it that hard to just think; well let’s try the releases list then.
> 
> > 
> 
> > Are you literally retarded?
> 
> 
> 
> How about you?
> 
> Look at erazemk's screenshot above. There are no other files there except Source code, and they don't contain .ipa files.

No shit sherlock......
So you are retarded too, just like xoniq
He was telling OP that he should look in Releases but there is nothing 
You didn't understand anything 🤦‍♂️🤦‍♂️
