### ISSUE TITLE
YouTube videos not showing up on Home Screen on launch without scrolling down

### ISSUE THREAD

**Issue by EhalloMatt** [MiRO92/uYou-for-YouTube#448]
If I launch uYou, I don't see any YouTube videos without scrolling down, and then, some aren't even showing. It's just a blank space. I'm on IOS 17.4.1, I installed the ipa via AltStore, and UYou is on version 3.0.3
![image](https://github.com/MiRO92/uYou-for-YouTube/assets/40703994/a289592a-4297-41f8-bb09-325f21866045)
![image](https://github.com/MiRO92/uYou-for-YouTube/assets/40703994/b2cbc8f4-6497-49dd-bda2-e3d0fa7e46b2)
![image](https://github.com/MiRO92/uYou-for-YouTube/assets/40703994/eefeceec-f765-4c95-8186-7fc5c3238e69)

**Comment by DethSaucin** [comment]
I’m having the same issue as well, it started today. I upgraded from version 18 to the newest version available today and I am still encountering the same issue. No first video and no shorts below it until I scroll down and it populates the rest of the videos until I get to the next section of videos and shorts and it goes blank again. Looks like every odd section of videos / shorts doesn’t populate.

**Comment by Dburkhart61** [comment]
So theres no fix? It was working fine for me till last night

**Comment by Funtimes909** [comment]
New user here, Having the same issue

**Comment by DethSaucin** [comment]
I feel like if there was a way to disable YouTube shorts on the home page it might temporarily solve the issue but I can’t find a toggle anywhere in any of the settings to turn off shorts

**Comment by dds111** [comment]
Same issue here. Is there any solution?

**Comment by qnguye** [comment]
same issue, hope developer fix it :)

**Comment by defrt** [comment]
Same here. Its because of ad blocking. If you disable ad block from uyou settings it works fine. But it defeats the purpose

**Comment by arichornlover** [comment]
> Same here. Its because of ad blocking. If you disable ad block from uyou settings it works fine. But it defeats the purpose

I do hope if MiRO92 does update it
But the best we could do is find workarounds and be patient ✨👍

**Comment by defrt** [comment]
@arichornlover I use cercube now and its an older build. No ads whatsoever and no blank screen. Maybe cercube method implemented?

**Comment by somebasicgoats** [comment]
uyou -> other settings -> disable Remove Youtube Ads. Unfortunately ads come back on home screen

**Comment by qnguye** [comment]
Mine got fixed about a week ago. Not sure what developer did :)
