### ISSUE TITLE
App soft crashes when minimizing from landscape fullscreen

### ISSUE THREAD

**Issue by Alius17** [MiRO92/uYou-for-YouTube#452]
App freezes when minimizing mid landscape fullscreen video, shows top bar, gets stuck with audio/vide and then soft crashes and returns to youtube home. Fresh install via altstore, no options selected, tested on ipad pro 12.9" 2015, and iphone 15pro. App created with updated fork on may 1st 2024 with youtube 19.15.1 decrypted.

**Comment by 4193883-eng** [comment]
same

**Comment by MishuPwns** [comment]
Same, Works on iPad Pro 9,7 on iPadOS 16.7.1 (palera1n) but not on iPad 10 on iPadOS 16.5.1 (dopamine). Install by using official youtube 19.26.5 from appstore and uYou 3.0.4 from official repo.
