### ISSUE TITLE
Uyou+ Nav bar disssapearing

### ISSUE THREAD

**Issue by plasticnote** [MiRO92/uYou-for-YouTube#46]
whenever you click on the [uyou+] tab while watching a video. the nav bar to get to home, subscriptions , etc disappears for some reason. The only way to bring it back is to either click on the channel info on the video that you are watching or completely restart the app itself. Also white you're on the channel info if you press back while youre still on the [uyou] tab, the app completely crashes. I only have an ipad pro and I do not know if this issue occurs on other devices. I have uploaded a footage below. 

This was on uyou+ ver 1.7  latest

https://user-images.githubusercontent.com/88959194/134731485-acf64f4a-717f-463b-98bf-fa69a551b76d.mp4

.

**Comment by qnblackcat** [comment]
Since you‘re using a modified version of uYou, are you sure the bug is related to uYou??? 🤷‍♂️

**Comment by plasticnote** [comment]
> Since you‘re using a modified version of uYou, are you sure the bug is related to uYou??? 🤷‍♂️

Happens on the non modded version as well. I tried just now. Maybe its only on Ipad? I dont know about on Iphone since I dont own one

**Comment by daveydecoy** [comment]
Yup, it’s easy to recreate but. I can confirm that on v2.0 repo version. 

iPad Pro 12.9 2015 gen 1 128gb 
iOS 14.4.2 - checkra1n 12.4 (diy a9+ fix)

https://user-images.githubusercontent.com/15191747/134823266-b4ca6605-a7d8-4ed2-972d-ec07c950569b.MOV
