### ISSUE TITLE
certain settings do not save after session

### ISSUE THREAD

**Issue by flezatre** [MiRO92/uYou-for-YouTube#461]
hello, the issue i’ve came across were only with certain settings not working, two of them being the “iPad layout” and “disable age restriction”. when i change the settings and restart the app to apply them, they don’t even appear as toggled.

**Comment by MiRO92** [comment]
I tried them both and they are working fine for me

**Comment by superJK92iscool** [comment]
Not for me, on uYouEnhanced, which uses this as a base
