### ISSUE TITLE
No IPA

### ISSUE THREAD

**Issue by AliChaos** [MiRO92/uYou-for-YouTube#462]
Where did the IPA go?
There is no .ipa in the .zip, just a Read Me File

**Comment by veosxx** [comment]
+1 no ipa on tread

**Comment by sevenpastzeero** [comment]
YouTube/Google issued warnings to all repos that contain ipas of YouTube app. So legally, MiRO92 can't host it anymore. No one will.

**Comment by AliChaos** [comment]
> YouTube/Google issued warnings to all repos that contain ipas of YouTube app. So legally, MiRO92 can't host it anymore. No one will.

And? Only because it is illegal now doesn't mean there won't be another one, or even MiRO92 will still host and update uYou 😂😂

**Comment by jimmysofat6864** [comment]
> > YouTube/Google issued warnings to all repos that contain ipas of YouTube app. So legally, MiRO92 can't host it anymore. No one will.
> 
> And? Only because it is illegal now doesn't mean there won't be another one, or even MiRO92 will still host and update uYou 😂😂

Well yea people with jb devices are gonna be just fine

**Comment by AliChaos** [comment]
> > > YouTube/Google issued warnings to all repos that contain ipas of YouTube app. So legally, MiRO92 can't host it anymore. No one will.
> 
> > 
> 
> > And? Only because it is illegal now doesn't mean there won't be another one, or even MiRO92 will still host and update uYou 😂😂
> 
> 
> 
> Well yea people with jb devices are gonna be just fine 

The minority is on jb devices

**Comment by jimmysofat6864** [comment]
Yea and you also in the minority as well who can’t build and inject the iPA
urself would have taken 2 seconds to google that.

**Comment by jimmysofat6864** [comment]
If you're that lazy just follow the buld instructons on https://github.com/arichornlover/uYouEnhanced/releases/tag/v19.21.2-3.0.4 to get your own iPA it's basically the same thing.

**Comment by MiRO92** [comment]
I'm currently working on an update and will be releasing it very soon, along with the IPA links
