### ISSUE TITLE
[Bug] "Hiding buttons under the video player" doesn't work on sideloaded version (IPA)

### ISSUE THREAD

**Issue by qnblackcat** [MiRO92/uYou-for-YouTube#47]
- iOS 14.3/14.5/15.0: Tested on at least 3 devices.

- YouTube 16.37.3 & uYou 2.0 from your Github.

- Sideload tool: AltStore (free account), appdb pro, iOS App Signer (Development certificate & Wildcard profile). 

- Describe the bug: Basically, **Hiding YouTube buttons under the video player** doesn't work at all if you use the IPA. It works perfectly with uYou from **Cydia**.

**Comment by mobochi** [comment]
Same the issue also in uYou 2.1 IPA version

**Comment by ErSpieltHD** [comment]
You can't hide the buttons (like uYouLocal etc.) on shorts too. Please fix.

**Comment by AlphaOrBeta** [comment]
I have the same problem, I don't know for you, but for me there are no uyou buttons as well like uyou and uyou local. For a time of around 2 weeks after I first installed uyou (specifically uyou plus) in February of this year everything worked as expected, but then for some reason it just didn't work anymore. (I never updated the version) So I don't know why it stopped working. Does anybody else have the same issue of uyou buttons missing?
