### ISSUE TITLE
PIP causing device to overheat. Very very hot.

### ISSUE THREAD

**Issue by xSimone** [MiRO92/uYou-for-YouTube#471]
Hello,

uYou is causing my iPhone 14 pro to overheat, it becomes scalding hot. The reason is because I believe PIP is buggy on iOS 16.3 and the CPU is going into overdrive for reasons that don't make sense. 

I have used uYou plus and noticed with their settings toggle you can disable PIP or switch between PIP or have it minimised into dynamic Island which stops the overheating issue. UYou some reason won't allow this and every time I minimise the app it goes into PIP no matter what. 

The settings for PIP in the YouTube app is missing too. 

I'd use uYou Plus but it doesn't have the option to download music into my music app. It forces me to use Filza and doesn't have any metadata with the files so it's essentially useless. 

Miro if you're reading this, please give us an option to turn off PIP or toggle it on and off with preferences to have it off to begin with when minimised etc. 

Thank you for this awesome app.

**Comment by xSimone** [comment]
I worded this all wrong and may have confused you MiRO, sorry.

So what I meant to say is uPIP isn't working with uYou properly.

Right now uPIP settings aren't showing in uYou now. 

Unless I am missing something?

**Comment by MiRO92** [comment]
I removed PiP support for uYou a while ago, so I don’t provide support for other tweaks you might be using to add PiP to YouTube

**Comment by xSimone** [comment]
Oh, I'm an idiot. uPIP is by Poomsmart.

Sorry about that.

Well, I removed uPIP, but PIP still seems to be functioning on your version of uYou.

https://www.youtube.com/watch?v=jfKfPfyJRdk

Lofi Girl is a particular live video that seems to cause PIP to show up.

Is there any way to ensure PIP stops functioning 100%?

**Comment by xSimone** [comment]
Or when you say "I removed PIP support" you mean, you removed support to toggle its settings without the need for YouTube Premium?
