### ISSUE TITLE
[Feature Request] An option to disable "Custom Double Tap To Seek Time"

### ISSUE THREAD

**Issue by qnblackcat** [MiRO92/uYou-for-YouTube#48]
- iOS 14.3/checkra1n/Substitute.

- YouTube 16.37.4.

- uYou 2.0. uYou is the only YouTube tweak I use.

- **Custom Double Tap To Seek Time** is buggy on my phone. Each time value of Skip Time in uYou and in YouTube give a different result: unable to skip time, or wrong Skip time,... Would be great if I can disable **Custom Double Tap To Seek Time**.

- In the first video, I set the **Skip Time in uYou** at 5s, **Skip Time in YouTube** at 10s. Skip forward works (5s), but Skip backward skips 15s.
https://drive.google.com/file/d/1b6aVFoxqiLSc0ka3bbf_GaQkhyy5E7EW/view?usp=sharing

- In the second video, I set the **Skip Time in uYou** at 5s, **Skip Time in YouTube** at 5s. I couldn't Skip forward at all. Skip backward skips 10s.
https://drive.google.com/file/d/1f6x-Y0FazaejqfQBE1hbTV5-5LmrKgSw/view?usp=sharing

**Comment by MiRO92** [comment]
Done!
