### ISSUE TITLE
Heating and lag issues

### ISSUE THREAD

**Issue by Luminex23** [MiRO92/uYou-for-YouTube#484]
Hello, since I installed uYou Enhanced, I've been experiencing a problem that happens out of nowhere. The issue is that while I'm watching videos, the phone starts to heat up a lot, and the app begins to lag severely, to the point where the phone doesn't even respond when I try to turn it off. I've never had this problem with any other YouTube app, but I do with uYou Enhanced. Please help me.

**Comment by MiRO92** [comment]
am sorry but I don't offer support to "uYou Enhanced"
