### ISSUE TITLE
Speed control not working and cannot be removed from uYou or uYouEnhanced

### ISSUE THREAD

**Issue by cyoussef8** [MiRO92/uYou-for-YouTube#485]
Cannot remove speed control ( - 1x +) from uYou or uYouEnhanced or from Video Overlay Menu. It also doesn't function when you click "-" or "1x" or "+".

**Comment by cyoussef8** [comment]
Build: [uYouEnhanced_19.22.6-3.0.4] 

Youtube v. 19.22.6

**Comment by qzxyzy** [comment]
How tf do u have 3.0.4 ?

**Comment by cyoussef8** [comment]
I built it myself by following the instructions. I have a forked copy of uYouEnhanced Repo on Github.

**Comment by Grelo4ka** [comment]
I confirm the issue still persists with the latest build

**Comment by MiRO92** [comment]
I’ve just fixed it and will release an update soon. Thank you for reporting this!

**Comment by Grelo4ka** [comment]
Thank you @MiRO92 , you are doing an incredible job!
