### ISSUE TITLE
[Bug] YouTube videos unresponsive directly after search

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#49]
This is an old bug, that I didn't come around reporting. Basically you can't open a Video directly after searching. Tapping on them does nothing, except highlighting them really shortly.

To fix this, you have to scroll the page a tiny bit. Here a video demonstrating this behavior:

https://user-images.githubusercontent.com/16444679/135061136-8a871057-fcb8-493e-abdb-c4f9508299e3.MOV

Tested sideloaded IPA on iPhone 12 Max (iOS 15)

**Comment by MiRO92** [comment]
I've tested it and it works fine on my iOS 14 devices,  maybe it's a YT app bug on iOS 15

**Comment by theoccurrence** [comment]
It doesn't happen with normal YouTube
