### ISSUE TITLE
uyou 3.0.4 dont skip paid promotions on videos

### ISSUE THREAD

**Issue by fusionptb** [MiRO92/uYou-for-YouTube#492]
on oldest version 3.0.1 the app show on the bar where a paid promotion are on the video (on green) but in 3.0.4 it dosnt show and dont skip the promotions inside the video!

**Comment by yodaluca23** [comment]
That is not this tweak, your probably thinking of https://github.com/Galactic-Dev/iSponsorBlock

**Comment by fusionptb** [comment]
yep. sorry im a little confused, its the mod of uyou... uyou plus, found the version 3.0.3 and works great. thanks!
