### ISSUE TITLE
Youtube home screen thumbnails videos not clickable sometimes

### ISSUE THREAD

**Issue by plia7** [MiRO92/uYou-for-YouTube#494]
Hello,

I have iOS 14.4.1 with Taurine jailbreak. I also have Youtube version 19.09.4 with uYou 3.0.3.

I noticed today that when I try to click on videos from the home screen, they are not clickable.

Does it work for you?

I tried to update to Youtube version 19.20.2 with uYou 3.0.4 but I still see this issue from time to time.

One possible workaround that's not ideal: Add things from home screen to “watch later” playlist and then those links open from said playlist.

Thanks.

**Comment by salvlox** [comment]
yep same
sometimes opening shorts and clicking something in there kinda unlocks and make thumbnails open the video again

**Comment by plia7** [comment]
> yep same sometimes opening shorts and clicking something in there kinda unlocks and make thumbnails open the video again

After installing 19.20.2 with uyou 3.0.4 to see the problem is still there, I tried to go back to 19.09.4 with uyou 3.0.3 but it crashes when I try to open it after reinstalling it with appstore++. I have a full ipa I extracted from it before using CrackerXI but when I install the ipa with trollstore - The font inside the app looks different than the original font. Any idea how to resolve?

**Comment by plia7** [comment]
> yep same
> sometimes opening shorts and clicking something in there kinda unlocks and make thumbnails open the video again

I was able to install youtube version 19.09.4 ipa with trollstore, fix the font issue by respring and then installed uyou 3.0.3. Everything works good now, I don’t see the issue anymore. Closing the ticket.
