### ISSUE TITLE
Playback speed buttons don't work on latest YouTube

### ISSUE THREAD

**Issue by Xalusc** [MiRO92/uYou-for-YouTube#496]
The playback speed buttons when watching a video don't do anything on the latest YouTube version (19.38.2).

**Comment by MiRO92** [comment]
I’ve just fixed it and will release an update soon. Thank you for reporting this!

**Comment by doggie015** [comment]
> I’ve just fixed it and will release an update soon. Thank you for reporting this!

Exactly how soon do you plan for that to be?

**Comment by git-anish** [comment]
> I’ve just fixed it and will release an update soon. Thank you for reporting this!

@MiRO92 sorry to ping you on a closed thread, was this ever fixed? I didn't see an update after 3.0.4
