### ISSUE TITLE
[Feature Request] Option to disable YouTube‘s new view for videos in playlists

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#50]
Don't we all just love, when YouTube introduces a new feature, that obstructs the videos you want to watch?

YouTube introduced some kind of preview for playlists, when you start videos from them. It's just an annoying extra click every time.

I'm referring to this: ![image](https://user-images.githubusercontent.com/16444679/135061843-db541192-57b2-4a87-bc53-b7fdd8c7e85c.png)

**Comment by ErSpieltHD** [comment]
@theoccurrence They should rather make it scalable than removing it

**Comment by theoccurrence** [comment]
> @theoccurrence They should rather make it scalable than removing it imo

That's a valid opinion, I guess. How about making your own feature request instead of downvoting others?
