### ISSUE TITLE
[Feature Request] Manual sort option for downloaded videos

### ISSUE THREAD

**Issue by tranpaul33** [MiRO92/uYou-for-YouTube#53]
I am requesting to add a manual sort option for downloaded videos.  Thank you

**Comment by ErSpieltHD** [comment]
This is needed asap.

I still don't get why you created a whole new "uYou" section and didn't go with the normal YT mechanics. Like making downloads go to a "Downloads" playlist like YT does. @MiRO92 @qnblacn
