### ISSUE TITLE
[Bug] Video lengths don‘t show up in playlist previews and history

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#54]
uYou doesn't show video lengths in playlists and history anymore since a couple of updates ago.

Here is what it should look like:
![image](https://user-images.githubusercontent.com/16444679/135258380-7a0e2c2a-57f4-41a5-a7e4-0e1c7fc01d53.png)

But it looks like this with uYou:
![image](https://user-images.githubusercontent.com/16444679/135258447-19c0c79a-1736-40d8-a9af-45c3341093c4.png)

Tested sideloaded IPA on iPhone 12 Max (iOS 15)

**Comment by Macleykun** [comment]
Same with the subscriptions tab!

**Comment by darrickteng** [comment]
I have this issue too with uYou 2.0 and uYou 2.1. The video lengths don't show up in any playlist. They are also missing in the history section

Hopefully the bug gets addressed soon

**Comment by Macleykun** [comment]
@MiRO92 are you able to recreate the issue aswell?
