### ISSUE TITLE
[Bug] The audio miniplayer‘s close button sometimes doesn‘t work

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#55]
I encountered this small bug on two occasions with the new update, but I don't know how to trigger/recreate it yet. I will update this issue, once I find out.

Basically uYou's audio miniplayer can't be dismissed when I encounter this bug, as the close button doesn't work. Completely closing YouTube fixes this behavior.

This video shows the bug in action:

https://user-images.githubusercontent.com/16444679/135452273-6ca08838-1e33-49a0-9de5-41f0e4ff02e2.MOV

Tested sideloaded IPA with iPhone 12 Pro Max (iOS 15)

**Comment by MiRO92** [comment]
I can't fix the issue if I can't replicate it, for now, I will close this issue until you figure out how this bug happen. thank you

**Comment by theoccurrence** [comment]
That's alright. I wasn't sure, if I should open an issue for every little bug that I find anyways. Next time I'll close it myself or won't even open an issue if I don't know how to replicate it.
