### ISSUE TITLE
[Bug] Auto select fails on 50 fps video

### ISSUE THREAD

**Issue by inheritanceXIV** [MiRO92/uYou-for-YouTube#56]
If a video has a play back speed/option of 50 fps it won't be auto selected. App will default to the lowest 60fps or 30 fps option.

**Comment by MiRO92** [comment]
Can you please share the link to the video that has 50fps?

**Comment by qnblackcat** [comment]
> Can you please share the link to the video that has 50fps?

https://youtu.be/O12Ve5AFu7o

**Comment by MiRO92** [comment]
Oh, I didn't pay attention when you said 50fps, I've already removed the 50fps option from uYou so I don't think you're using the latest version of uYou, and I only support the latest versions of my tweaks.

**Comment by inheritanceXIV** [comment]
I am using the latest version, 2.0 is there a reason 50 fps videos are not supported as a auto select playback resolution?

**Comment by oomek** [comment]
I've encountered the same issue. When a video is 720p50 or 1080p50 the quality stays at 480p

https://youtu.be/BWYRIV8YVdk
