### ISSUE TITLE
App (sideloaded) crashes when opening the uYou tab and have at least 1 downloaded item

### ISSUE THREAD

**Issue by worriorbg** [MiRO92/uYou-for-YouTube#58]
iOS 14.8
iPhone 12 mini
Sideloaded with Cydia Impactor 16.38.2

- Fresh install (sideload)
- Switched to uYou tab and changed some settings for the video overlay and changed download location to camera
- Picked a video on the home tab and tapped the "3 dot" button and then selected uYou from the menu
- Selected 480p quality and download started
- When one switches to the uYou tab->Downloading - app crashes
- When app is opened again and only picking the uYou from the tabBar - app crashes and no uYou settings aren't available anymore

Attaching a crash log:
[YouTube  8.10.21, 15-08.crash.zip](https://github.com/MiRO92/uYou-for-YouTube/files/7311431/YouTube.8.10.21.15-08.crash.zip)

**Comment by theoccurrence** [comment]
I also experienced this crash, but wasn't able to recreate it, so I didn't open an issue.

I fixed it by deleting the app and installing it again. I haven't gotten this crash ever since.

**Comment by iRayanKhan** [comment]
I can reproduce the same on a iPhone 12PM 15.0.
