### ISSUE TITLE
fix error while trying to downloading playlists

### ISSUE THREAD

**Issue by golfboyyy** [MiRO92/uYou-for-YouTube#62]
when i try to download a playlist it says “Error! Couldn’t find any video in this playlist.”
![435AFD14-E514-4E85-BCDA-A74FEF7D673E](https://user-images.githubusercontent.com/81543562/138560181-80c42b8b-20a2-418e-86f2-ab200b1a0d1d.png)

**Comment by Whahahahaha** [comment]
I also have this issue, had it with V2.0, still there after updating to 2.1.
Haven’t found any playlist where it does work.

**Comment by secret-asianman** [comment]
I am still having this issue as well.

**Comment by Peiprjs** [comment]
Same here. I am on uYouPlus, the latest.

**Comment by piotrszpruta** [comment]
Still there

**Comment by CycIoneTM** [comment]
Still no fix?
