### ISSUE TITLE
pip no longer works automatically.

### ISSUE THREAD

**Issue by ConceptAttached** [MiRO92/uYou-for-YouTube#63]
Lastest version 2.0 broke pip for iOS 15.2, when switch to main menu pip doesn't work.

**Comment by ConceptAttached** [comment]
Down grading to older version works.

**Comment by Macleykun** [comment]
Pip works for me on the latest version as of today.

**Comment by roykim98** [comment]
I'm also seeing this issue on 2.1

**Comment by qnblackcat** [comment]
just install YouPiP https://github.com/PoomSmart/YouPiP/
