### ISSUE TITLE
Slide down gesture has 1 second lag

### ISSUE THREAD

**Issue by oomek** [MiRO92/uYou-for-YouTube#66]
There is a significant delay when I slide the video down to minimize it, or when I press the arrow down button in top left corner. Original Youtube is very responsive to this gesture, but uYou for some reason lags for up to 1 second.
I'm on v2.1

**Comment by MiRO92** [comment]
all of my testing devices are working fine, you might have something else which causing that lag.

**Comment by oomek** [comment]
Are you sure we're talking about the same thing?
Fulscreen to window slide down gesture is instant. Window to small bar at the bottom gesture has this long delay. I have iphone 7 Plus. Teied reinstalling uYou but this lag is still there.

**Comment by tamtamree** [comment]
same here
iphone 7, ios 15.1, uYou 2.1
https://files.catbox.moe/8nnl39.mp4

**Comment by oomek** [comment]
Here's my recording
https://user-images.githubusercontent.com/2974860/140612403-3edcc505-6dcc-4b69-89e4-2145f4e46398.mp4

**Comment by oomek** [comment]
The lag is gone after installing IOS 15.2 beta 4. Who would have thought this delay was caused by the bug in IOS 15.1
