### ISSUE TITLE
Paid promotion did not skip

### ISSUE THREAD

**Issue by Nick1603** [MiRO92/uYou-for-YouTube#67]
The paid promotion Whithorn the video did not skip unlike previous version and couldn’t find the settings for it either.

**Comment by theoccurrence** [comment]
Sounds like an iSponsorBlock problem. You sure you even have a version of uYou installed with iSponsorBlock in it?

**Comment by Macleykun** [comment]
This can be closed as skipping with iSponsorblock works (this also isn’t related to uYou at all).
Suggest closing this issue.
