### ISSUE TITLE
Add altstore:// link (and use .ipa instead of zipping it)

### ISSUE THREAD

**Issue by Macleykun** [MiRO92/uYou-for-YouTube#68]
Heya!

From the uncover site, i learned you can also direct download ipa's with altstore like so:
`altstore://install?url=https://unc0ver.dev/downloads/7.0.0/48073ecf35dcf43d0607ec779079e8a4d69e90c2/unc0ver_Release_7.0.0.ipa`

I tried replacing the link of uncover with yours. But it doesn't seem to work well. I though it was maybe because of the zip, but i haven't tested that yet.

However i do think it's best you don't zip your ipa's, it barely saves any bandwith (3MB)
105M    ./YouTube_16.42.3_uYou_2.1.ipa
102M    ./YouTube_16.42.3_uYou_2.1.zip

I think it'll be a smart idea to include the altstore link to the latest ipa you give, so that users only have to click once :).

I hope you'll see this issue, and i look forward to your opinion about this!

**Comment by MiRO92** [comment]
Thanks a lot, I'll add that in the next update.
