### ISSUE TITLE
PiP not working anymore in version 2.1

### ISSUE THREAD

**Issue by magnanig** [MiRO92/uYou-for-YouTube#69]
YouTube native PiP stopped working in version 2.1 on my iPhone XR. I can’t even enable it in YouTube settings.

I’ve rollbacked to version 2.0 and now it is back to work correctly. Probably last YouPiP bug fixes broke something.

**Comment by theoccurrence** [comment]
Are you sure you didn't install uYou+ 2.0 (including uYou, youPiP, iSponsorBlock and other tweaks) from a different source like AppDB?

**Comment by magnanig** [comment]
Yes, I’ve downloaded the last .ipa from the README page (version 2.1).

If I go in the YouTube general settings I have no PiP configuration, contrary to the previous version (2.0), that was perfectly working.

I allegate the screenshot of YouTube general settings, where PiP configuration should be (it is in Italian but you can see the PiP entry missing).

![9A7822CC-544F-4260-A2AD-3270A62A3343](https://user-images.githubusercontent.com/64785214/139714649-577fd627-1b91-4d19-ad38-e54c2f0ce94b.jpeg)

**Comment by qnblackcat** [comment]
> Yes, I’ve downloaded the last .ipa from the README page (version 2.1).
> 
> If I go in the YouTube general settings I have no PiP configuration, contrary to the previous version (2.0), that was perfectly working.
> 
> I allegate the screenshot of YouTube general settings, where PiP configuration should be (it is in Italian but you can see the PiP entry missing).
> 
> ![9A7822CC-544F-4260-A2AD-3270A62A3343](https://user-images.githubusercontent.com/64785214/139714649-577fd627-1b91-4d19-ad38-e54c2f0ce94b.jpeg)

You‘re using **uYou**, NOT **uYou+**. 🤦‍♂️

**Comment by magnanig** [comment]
Yeah, I was using uYou+ 2.0, then from the app I received the message telling me to update to the 2.1. The link brought me to this repo and I thought it was the update for the whole application. In more, in the uYou description page it is said uYou adds PiP so I thought it was the native PiP and I confused the two apps.

Sorry for the mistake and thanks for the answer.
