### ISSUE TITLE
[Bug] AppDB developer identity workaround does not work anymore

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#70]
Downloads have once again stopped working in the newest version, despite setting the identity type to developer, before sideloading. This worked in 2.0.

![image](https://user-images.githubusercontent.com/16444679/139696931-345d31f7-6c11-4bfb-b1ee-bf3e6c1c9017.jpeg)

![image](https://user-images.githubusercontent.com/16444679/139696685-d4151dbd-3fe9-40d5-b073-fe5d7321338e.png)

**Comment by niXta1** [comment]
Same...

**Comment by theoccurrence** [comment]
I will stay on 2.0 for now, working downloads are more important for me than an option to deactivate custom double tap to seek time.

Has anybody found out what the "Fullscreen Videos on the Right" Option in Other Settings does? There's no documentation and as far as I can tell - it has no function.

**Comment by HaikuOezu** [comment]
I have the same problem and I'm installing via Sideloadly so I can't use the workaround... any ideas on what's actually causing the issue? :/
