### ISSUE TITLE
Make it so there is less icons (especially the speed controls) in the video screen. 

### ISSUE THREAD

**Issue by throwaway2342** [MiRO92/uYou-for-YouTube#71]
For example,,,,,try to make it so that you have to press the 3 dots in the top right to access all those features.....or at the very least make it so some of them are hidden

**Comment by qnblackcat** [comment]
do you ever go to uYou settings? There are options to  hide all icons in there

**Comment by throwaway2342** [comment]
> do you ever go to uYou settings? There are options to hide all icons in there

can you tell me word for word where it is because i couldn't find it but maybe i didn't look for it enough

**Comment by qnblackcat** [comment]
uYou settings => Video Controls Overlay

**Comment by MiRO92** [comment]
already exist in uYou's settings

**Comment by throwaway2342** [comment]
I still can’t find the settings

sorry to say this after the topic was closed

**Comment by theoccurrence** [comment]
> I still can’t find the settings
> 
> 
> 
> sorry to say this after the topic was closed 

My man, are you sure you're in the uYou settings and not in the YouTube settings?

![image](https://user-images.githubusercontent.com/16444679/140083298-2bf942cc-1b68-41fa-a547-7112a5c252d6.jpeg)
