### ISSUE TITLE
Error fetching channel list for account

### ISSUE THREAD

**Issue by BrianGilbert** [MiRO92/uYou-for-YouTube#72]
After updating to uYou v2.1 I am getting this error when trying to log in using my google/youtube account, I can authenticate the account though.

I have tried removing and re-adding account.

Steps to reproduce:
- Install v2.1 of uYou
- view youtube anonymously
- click user icon at top right
- select Sign in button
- error message displayed below my email address

**Comment by MiRO92** [comment]
Oh sorry, it was a mistake by me, I'll fix it and release an update soon.
