### ISSUE TITLE
youtube and uyou Settings keep resetting on ios 15.1

### ISSUE THREAD

**Issue by throwaway2342** [MiRO92/uYou-for-YouTube#75]
anyone having this problem as well?

**Comment by qnblackcat** [comment]
How did you sideload the IPA?

**Comment by throwaway2342** [comment]
Using an UDID service called signumsign.me

**Comment by qnblackcat** [comment]
I believe it is a known issue of Signum (and Signulous as well). Nothing wrong with the IPA. Try another sideload tool/ signing service if you can

**Comment by MiRO92** [comment]
This issue is not related to uYou, so i will close it.

**Comment by throwaway2342** [comment]
Thank you
