### ISSUE TITLE
not able to install on tvos via slideload

### ISSUE THREAD

**Issue by hle5128** [MiRO92/uYou-for-YouTube#76]
Can you make this compatible with tvos ?

**Comment by MiRO92** [comment]
Sorry but i can't

**Comment by Keagel** [comment]
Is there a reason? Is it not feasible? Not enough demand?

**Comment by JHarding86** [comment]
Yes also interested in reasoning... Do you need hardware?

**Comment by dpyy** [comment]
Would pay for a port.
