### ISSUE TITLE
Still show website ads in search results.

### ISSUE THREAD

**Issue by ConceptAttached** [MiRO92/uYou-for-YouTube#79]
When I search products name like iPhone,pixel,the YouTube search results will show ads from retailers,only for one time, after refreshing the page the ads will go away.  Please try to fix.

**Comment by theoccurrence** [comment]
Might be a duplicate of https://github.com/MiRO92/uYou-for-YouTube/issues/11

**Comment by MiRO92** [comment]
fixed
