### ISSUE TITLE
IOS iPad version Doesnt show the Video Length in Subscription and History Tab

### ISSUE THREAD

**Issue by LiJT** [MiRO92/uYou-for-YouTube#81]
Hello! Could you do a little fix regarding this issue? I can no longer see the Video time length on each corner of the video thumbnail anymore?

**Comment by theoccurrence** [comment]
Duplicate 

https://github.com/MiRO92/uYou-for-YouTube/issues/54

**Comment by Macleykun** [comment]
Like @theoccurrence  said, duplicate so suggest closing this.
