### ISSUE TITLE
[Feature Request] Replace Next and Previous buttons in lockscreen with 15 second forward and backward skip when playing longer videos.

### ISSUE THREAD

**Issue by chadify** [MiRO92/uYou-for-YouTube#84]
I often play podcasts in background with uYou and it'd be great if I can skip 15 seconds back/forward using double/triple tap using my Airpods Pro.
![photo_2021-11-26_12-19-16](https://user-images.githubusercontent.com/72332949/143571047-41535558-9c6a-4c12-baea-d12c1129bc73.jpg)

**Comment by Macleykun** [comment]
You can’t do this unless your jailbroken.
Suggest closing this issue.
