### ISSUE TITLE
[Bug] Forcing video quality doesn’t fully work with 50fps videos

### ISSUE THREAD

**Issue by PoomSmart** [MiRO92/uYou-for-YouTube#85]
Latest uYou (Nov 27).

Example video: https://youtu.be/LoiK4A4Eioo

The forced video quality set to 1080p60, but the video defaults to 480p.

1080p and 720p are affected.

**Comment by PoomSmart** [comment]
The available options from 1080p are 1080p (which is 30 FPS) and 1080p60 (which is 60 FPS). Where would 50 FPS belong is a good question.

**Comment by theoccurrence** [comment]
Looks like handling 50 FPS videos was removed on purpose, there was another already closed issue concerning this.

https://github.com/MiRO92/uYou-for-YouTube/issues/56
