### ISSUE TITLE
[Feature Request] Bring back the dislike count

### ISSUE THREAD

**Issue by theoccurrence** [MiRO92/uYou-for-YouTube#86]
YouTube is currently rolling out changes that hide the dislike count on videos. I don't know if Google will remove this in the future, but it is still possible to get the dislike count from Google's API.

**Comment by hilabius** [comment]
Possibly by using https://www.returnyoutubedislike.com/ to track dislikes even after the API changes

**Comment by oomek** [comment]
I would very much like that addition.

**Comment by zcccccc1** [comment]
API documentation has been released at https://returnyoutubedislikeapi.com/swagger/index.html.

**Comment by Macleykun** [comment]
Use this variant if uYou: https://github.com/qnblackcat/uYouPlus
Issue can be closed :)

**Comment by qnblackcat** [comment]
https://github.com/PoomSmart/Return-YouTube-Dislikes/
