### ISSUE TITLE
[Bug] uYou 2.1 settings crash with YouTube 16.45.4

### ISSUE THREAD

**Issue by abheizthe** [MiRO92/uYou-for-YouTube#87]
uYou 2.1 settings (under YT Settings) is crashing with YouTube 14.45.4 (using uYouPlus)

![84B4134B-192F-4D82-A2A5-6D91180337C2](https://user-images.githubusercontent.com/54247318/143767073-885ce6a4-b826-4f73-9e9b-b126aaa1914e.png)

**Comment by qnblackcat** [comment]
uYou 2.1 does not officially support YouTube 16.45.4. All issues related to uYou+ should go here: https://github.com/qnblackcat/uYouPlus/issues/

Also, I'm using uYou+ right now and there is no crash at all.
