### ISSUE TITLE
(bug）can’t keep 1080p even i have opened high picture quality.

### ISSUE THREAD

**Issue by LucasIsGood** [MiRO92/uYou-for-YouTube#88]
![IMG_0023](https://user-images.githubusercontent.com/56297860/143805568-20abad94-8e69-42e5-a17a-bc3874c3dff9.png)
![IMG_0025](https://user-images.githubusercontent.com/56297860/143805572-0f9f9af7-25e1-4c68-960a-de7772a936a3.png)

i don’t know why lol

**Comment by LucasIsGood** [comment]
anybody knows why i need your help

**Comment by qnblackcat** [comment]
uYou doesn't have that option. You're using uYou+, NOT uYou. 
All issues related to uYou+ should go here: [uYou+ issues]( https://github.com/qnblackcat/uYouPlus/issues/).
_Please don't bother MiRO with issues that unrelated to uYou_
