### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by TomiKovacs** [MiRO92/uYou-for-YouTube#89]
In selecting video quality on a video, instead of having “Auto”, “Higher Picture Quality” and “Data Saver”, only show the specific resolutions.

**Comment by WoodpeckerBaby** [comment]
I believe there is a tweak for that. It's trivial to add. 

Better Cercube supports this.

**Comment by Macleykun** [comment]
Not sure what your talking about.
I’m uYou’s settings the resolution can be selected by default.
Within the video that’s playing you can edit the resolution aswell.
It’s true that trough the official YouTube settings you can’t do this, but given the top option these can be ignored and will be overwritten by uYou.
