### ISSUE TITLE
Can't save video when installing via appdb pro

### ISSUE THREAD

**Issue by miuirussia** [MiRO92/uYou-for-YouTube#9]
```
ERR: Unable to move file from file:///var/mobile/Library/Caches/com.apple.nsurlsessiond/Download ...
```

App from here: https://appdb.to/app/cydia/1900000830

**Comment by MiRO92** [comment]
It's an entitlement issue, Please try using another way/service for signing the IPA.

I'll try to take a deep look at it once I get more free time

**Comment by miuirussia** [comment]
Can you describe the problem to them, what exactly is wrong:

https://twitter.com/appdb_official/status/1433344439611764737

**Comment by miuirussia** [comment]
@MiRO92
