### ISSUE TITLE
Very low wifi speed in app

### ISSUE THREAD

**Issue by stasikkk777** [MiRO92/uYou-for-YouTube#91]
It can barely render a 1080p video and when downloading some mp3s, the speed is 57kbs. In the normal yt app, it is all perfect. Please solve this issue, because otherwise this tweak is insanely good!

**Comment by Macleykun** [comment]
Note that this may or may not have to do with uYou at all.
Is this still happening? Even with a stable and fast WiFi connection?

**Comment by MiRO92** [comment]
fixed
