### ISSUE TITLE
[Bug] YouTube crashes when you configure channel notifications

### ISSUE THREAD

**Issue by qnblackcat** [MiRO92/uYou-for-YouTube#94]
**Device info**
- iOS/iPadOS version: 14.3
- Device model: 6s
- checkra1n/Substitute
- YouTube version: 16.42.3 and 16.46.5
- uYou: 2.1

**Describe the bug**
- Whenever you try to configure the notifications from a channel the app crashes

https://user-images.githubusercontent.com/52943116/145702511-332b5ca8-ae5c-475f-80b9-f11925b1f0c1.MOV

**How to Reproduce the bug**

**Crash log from Cr4shed**
https://pastebin.com/nBVfB34q

**Comment by ErSpieltHD** [comment]
Will you fix this or just close it as well @qnblackcat

**Comment by arichorn** [comment]
theres one way to fix the bug.. downgrade uyou back to the first release version of uyou

**Comment by DelofJ** [comment]
Ok but it's not a solution
This problem has been open for a year and MiRO92 still hasn't replied, the latest ipa of uYou is taken from youtube 16.42.3 which is dated october 24, 2021, is MiRO92 still active on uYou ?

**Comment by qnblackcat** [comment]
Workaround: configure the notification under any videos instead of go to the channel

**Comment by arichorn** [comment]
This topic has been migrated to #152 I added a ton of changes that uYou deserves to add. And including this Notification Bug!
