### ISSUE TITLE
[Feature Request] uYou Music

### ISSUE THREAD

**Issue by homanh** [MiRO92/uYou-for-YouTube#95]
I've been looking for a replacement for Vanced since moving to iOS.

Ironically YouTube Music Vanced was more important to me than normal YouTube since I usually don't want to lock my phone when viewing a YouTube video whereas I always do when using YouTube Music.

There are several reasons to use YouTube Music rather than regular YouTube when listening to songs whilst driving etc. including:

- YouTube Music has very good AI algorithm generated playlists
- YouTube Music songs played won't mess up YouTube _history_, or suggestions. Where it gets so cluttered after listening for a few hours that you can't really use the history unless scrolling heavily.
- YouTube will sometimes jump from a song to a non-music video, whereas YouTube Music will always find songs to play.

**Comment by arichorn** [comment]
#152 I’ll move your feature request to this topic! Making it easy for MiRO92 to come across! and trying to help y’all get your features added
