### ISSUE TITLE
links won't open in app

### ISSUE THREAD

**Issue by Zankdon** [MiRO92/uYou-for-YouTube#96]
Hello, 
I realised, that YouTube links from different sources won't open in this app.

best regards
Zankten

**Comment by qnblackcat** [comment]
It is impossible to make deep-link work. Even when you have a paid developer account

**Comment by Macleykun** [comment]
Suggest closing as it’s out of scope.

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
Found out [this](https://github.com/christianselig/OpenInApolloExtension) safari extension that lets the Reddit Apollo iOS Client, open reddit.com links in that app. Maybe something similar could be done? ![image](https://user-images.githubusercontent.com/79347623/173207259-c99a46be-9276-46a0-81a2-6b217fee8dd9.png)
