### ISSUE TITLE
PiP doesn't work properly

### ISSUE THREAD

**Issue by dzxcvp** [MiRO92/uYou-for-YouTube#97]
PiP doesn't work properly.
Sometimes it stucks on loading.
Background plays with PiP playing in front, very  confusing.
iOS 15.1 iPhone X

**Comment by Macleykun** [comment]
Ya updated to latest?
It isn’t clear what exactly isn’t working with pip.

**Comment by Dylan96** [comment]
> Ya updated to latest?
> It isn’t clear what exactly isn’t working with pip.

Pip isn’t working on live streams, returns “uyou did not find any quality to download”.
